/** Stufe 2: Leistungen des Clusters "Bauen, Wohnen und Grundstücke". */
export const LEISTUNGEN = [
  {
    id: 'bauantrag',
    cluster: 'bauen-wohnen',
    name: 'Baugenehmigung beantragen',
    sprechName: 'Baugenehmigung beantragen',
    synonyme: ['bauantrag', 'baugenehmigung', 'bauen', 'haus bauen', 'anbau', 'garage bauen', 'carport', 'dachausbau', 'wintergarten', 'bauamt', 'genehmigung bauen', 'nutzungsänderung'],
    leikaBezug: 'Baugenehmigung - Erteilung (LeiKa 99056001)',
    kurzbeschreibung: 'Errichtung, Änderung und Nutzungsänderung baulicher Anlagen sind genehmigungspflichtig, soweit die Landesbauordnung nichts anderes bestimmt. Der Bauantrag wird über die Gemeinde bei der unteren Bauaufsichtsbehörde eingereicht.',
    zustaendigkeit: {
      stelle: 'Untere Bauaufsichtsbehörde beim Landkreis oder der kreisfreien Stadt; Einreichung über die Standortgemeinde',
      ebene: 'kommunal',
      hinweis: 'Die Gemeinde erteilt das gemeindliche Einvernehmen nach § 36 BauGB und leitet den Antrag weiter.',
    },
    voraussetzungen: [
      'Das Vorhaben ist planungsrechtlich zulässig: im Geltungsbereich eines Bebauungsplans nach § 30 BauGB, im unbeplanten Innenbereich nach § 34 BauGB oder als privilegiertes Vorhaben im Außenbereich nach § 35 BauGB.',
      'Der Bauantrag ist von einer bauvorlageberechtigten Person zu unterschreiben - in der Regel Architektin, Architekt oder Bauingenieurin mit entsprechender Eintragung.',
      'Die bauordnungsrechtlichen Anforderungen sind erfüllt: Abstandsflächen, Brandschutz, Standsicherheit, Erschließung, Stellplätze, Barrierefreiheit.',
      'Bei Denkmälern, Wasserschutz-, Natur- oder Landschaftsschutzgebieten sind zusätzliche Genehmigungen nötig.',
    ],
    unterlagen: [
      { was: 'Bauantragsformular des Landes, meist in dreifacher Ausfertigung', pflicht: true },
      { was: 'Amtlicher Lageplan auf Grundlage der Liegenschaftskarte, meist Maßstab 1:500', pflicht: true, hinweis: 'Vom Katasteramt oder einem öffentlich bestellten Vermessungsingenieur.' },
      { was: 'Bauzeichnungen: Grundrisse, Schnitte, Ansichten, meist Maßstab 1:100', pflicht: true },
      { was: 'Baubeschreibung', pflicht: true },
      { was: 'Berechnung von Grundflächenzahl, Geschossflächenzahl und Brutto-Rauminhalt', pflicht: true },
      { was: 'Standsicherheitsnachweis', pflicht: true, hinweis: 'Je nach Gebäudeklasse mit Prüfung durch einen Prüfingenieur.' },
      { was: 'Nachweis des Wärme- und Schallschutzes', pflicht: true },
      { was: 'Entwässerungsplan und Nachweis der Erschließung', pflicht: true },
      { was: 'Brandschutznachweis', pflicht: false, hinweis: 'Ab bestimmten Gebäudeklassen zwingend.' },
      { was: 'Nachweis der Stellplätze', pflicht: false },
      { was: 'Zustimmung der Nachbarn', pflicht: false, hinweis: 'Nur bei Abweichungen und Befreiungen; die Nachbarunterschrift auf den Plänen beschleunigt das Verfahren erheblich.' },
    ],
    gebuehren: [
      { position: 'Baugenehmigung', betrag: 'meist 0,5 bis 1 Prozent der Rohbaukosten', art: 'landesrecht', hinweis: 'Nach den Baugebührenordnungen der Länder. Für ein Einfamilienhaus typischerweise 500 bis 2.500 Euro.' },
      { position: 'Bauvoranfrage', betrag: 'etwa 50 bis 500 Euro', art: 'landesrecht' },
      { position: 'Prüfung des Standsicherheitsnachweises', betrag: 'etwa 500 bis 3.000 Euro', art: 'landesrecht' },
      { position: 'Befreiungen und Abweichungen', betrag: 'etwa 100 bis 1.000 Euro je Befreiung', art: 'landesrecht' },
      { position: 'Amtlicher Lageplan', betrag: 'etwa 300 bis 1.200 Euro', art: 'sonstige' },
    ],
    fristen: [
      'Gemeindliches Einvernehmen: gilt nach zwei Monaten als erteilt (§ 36 Abs. 2 BauGB).',
      'Genehmigungsfiktion: In vielen Ländern gilt die Genehmigung nach Ablauf von drei Monaten ab vollständigen Unterlagen als erteilt - die Details unterscheiden sich.',
      'Geltungsdauer der Baugenehmigung: in der Regel drei Jahre, meist einmal verlängerbar.',
      'Nachbarwiderspruch: ein Monat ab Zustellung; ohne Zustellung ein Jahr ab Kenntnis.',
      'Baubeginnsanzeige: meist eine Woche vor Beginn.',
    ],
    bearbeitungsdauer: 'Drei bis sechs Monate im Regelfall; im vereinfachten Verfahren kürzer, bei Befreiungen oder Beteiligung mehrerer Fachbehörden deutlich länger.',
    ablauf: [
      { nr: 1, titel: 'Planungsrecht klären', detail: 'Sehen Sie den Bebauungsplan im Geoportal der Gemeinde ein: Art und Maß der baulichen Nutzung, Baugrenzen, Geschosszahl, Dachform. Bei fehlendem Plan gilt § 34 BauGB - Einfügen in die Eigenart der näheren Umgebung.', akteur: 'Bürger' },
      { nr: 2, titel: 'Verfahrensart bestimmen', detail: 'Genehmigungspflichtig, im vereinfachten Verfahren, genehmigungsfrei mit Anzeige oder verfahrensfrei - das entscheidet die Landesbauordnung nach Größe und Art des Vorhabens.', akteur: 'Bürger' },
      { nr: 3, titel: 'Bauvoranfrage erwägen', detail: 'Bei unklarer Lage klärt sie einzelne Fragen verbindlich vorab, ist deutlich günstiger und meist drei Jahre gültig.', akteur: 'Bürger' },
      { nr: 4, titel: 'Entwurfsverfasser beauftragen', detail: 'Die bauvorlageberechtigte Person erstellt Pläne und Nachweise und begleitet das Verfahren.', akteur: 'Bürger' },
      { nr: 5, titel: 'Antrag einreichen', detail: 'Über die Gemeinde, zunehmend digital über das Bauportal des Landes.', akteur: 'Bürger' },
      { nr: 6, titel: 'Beteiligungsverfahren', detail: 'Gemeinde, Naturschutz, Denkmalschutz, Straßenbaulastträger, Brandschutzdienststelle und Nachbarn werden je nach Vorhaben beteiligt.', akteur: 'Behörde' },
      { nr: 7, titel: 'Genehmigung und Baubeginn', detail: 'Nach Erteilung: rote Prüfvermerke beachten, Baubeginn anzeigen, Grundstück abstecken lassen, Baustellenschild aufstellen, Auflagen dokumentieren.', akteur: 'Bürger' },
      { nr: 8, titel: 'Fertigstellung anzeigen', detail: 'Nach Abschluss ist die Fertigstellung anzuzeigen; je nach Land folgt eine Schlussabnahme oder eine Bescheinigung der Sachverständigen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 29 bis 38 Baugesetzbuch - Zulässigkeit von Vorhaben',
      '§ 36 Baugesetzbuch - Gemeindliches Einvernehmen',
      'Landesbauordnungen - Verfahren, Abstandsflächen, Bauvorlageberechtigung',
      'Baunutzungsverordnung - Art und Maß der baulichen Nutzung',
      'Gebäudeenergiegesetz (GEG)',
    ],
    online: {
      moeglich: true,
      hinweis: 'Der digitale Bauantrag ist in fast allen Ländern verfügbar; teilweise ist die digitale Einreichung inzwischen verpflichtend. Nachbarbeteiligung und Prüfvermerke laufen dann ebenfalls elektronisch.',
    },
    haeufigeFehler: [
      'Bauen ohne Genehmigung - der Schwarzbau kann eine Beseitigungsanordnung und ein Bußgeld nach sich ziehen.',
      'Abstandsflächen zum Nachbargrundstück unterschätzen.',
      'Annehmen, ein verfahrensfreies Vorhaben sei auch materiell frei - Bebauungsplan und Nachbarrecht gelten weiter.',
      'Die Genehmigung verfallen lassen, weil nicht binnen drei Jahren begonnen wurde.',
      'Nutzungsänderungen für genehmigungsfrei halten - der Wechsel von Laden zu Gaststätte oder von Büro zu Wohnung ist regelmäßig genehmigungspflichtig.',
      'Denkmalrechtliche Erlaubnis vergessen.',
    ],
    faq: [
      { frage: 'Brauche ich für ein Gartenhaus eine Genehmigung?', antwort: 'Das entscheidet die Landesbauordnung. Die Grenzen für verfahrensfreie Gebäude liegen je nach Land bei etwa 10 bis 75 Kubikmetern Brutto-Rauminhalt, im Außenbereich sind sie deutlich enger. Auch verfahrensfreie Gebäude müssen Abstandsflächen und Bebauungsplan einhalten.' },
      { frage: 'Was ist eine Bauvoranfrage?', antwort: 'Ein Antrag auf verbindliche Vorabklärung einzelner Fragen - etwa der grundsätzlichen Bebaubarkeit. Der Bauvorbescheid bindet die Behörde meist drei Jahre und ist deutlich günstiger als ein gescheiterter Bauantrag.' },
      { frage: 'Was tue ich, wenn der Nachbar Widerspruch einlegt?', antwort: 'Der Widerspruch hat aufschiebende Wirkung nur eingeschränkt; die Bauaufsicht oder das Verwaltungsgericht entscheidet über die Fortsetzung. Eine vorherige Nachbarunterschrift auf den Plänen vermeidet das meist.' },
      { frage: 'Wie lange dauert das?', antwort: 'Rechnen Sie mit drei bis sechs Monaten ab vollständigen Unterlagen. Unvollständige Anträge sind der häufigste Verzögerungsgrund.' },
    ],
    verwandt: ['bauvoranfrage', 'denkmalschutz-erlaubnis', 'abgeschlossenheitsbescheinigung', 'grundsteuer'],
    eskalation: 'Bei Außenbereichsvorhaben, Denkmälern, Nachbarwidersprüchen, Schwarzbauten oder Befreiungen an die Bauaufsichtsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Bauordnungsrecht ist Landesrecht mit erheblichen Unterschieden. Verfahrensfreiheit, Fristen und Gebühren immer für das konkrete Land prüfen.' },
    stand: '2026-08',
  },
  {
    id: 'bauvoranfrage',
    cluster: 'bauen-wohnen',
    name: 'Bauvoranfrage stellen',
    sprechName: 'Bauvoranfrage stellen',
    synonyme: ['bauvoranfrage', 'bauvorbescheid', 'vorbescheid', 'darf ich bauen', 'bebaubarkeit', 'grundstück bebaubar'],
    leikaBezug: 'Vorbescheid - Erteilung (LeiKa 99056001)',
    kurzbeschreibung: 'Die Bauvoranfrage klärt einzelne Fragen eines Bauvorhabens verbindlich vorab - typischerweise, ob ein Grundstück überhaupt bebaubar ist. Der Bauvorbescheid bindet die Behörde für die geklärten Fragen.',
    zustaendigkeit: { stelle: 'Untere Bauaufsichtsbehörde, Einreichung über die Gemeinde', ebene: 'kommunal' },
    voraussetzungen: [
      'Ein konkretes Vorhaben ist grob beschreibbar.',
      'Die zu klärenden Fragen sind eindeutig formuliert - je präziser die Frage, desto belastbarer die Antwort.',
    ],
    unterlagen: [
      { was: 'Antragsformular für den Vorbescheid', pflicht: true },
      { was: 'Lageplan', pflicht: true },
      { was: 'Skizzen oder Vorentwurf', pflicht: false, hinweis: 'Deutlich weniger aufwendig als beim Bauantrag - oft genügt eine Handskizze mit Maßen.' },
      { was: 'Beschreibung der Fragestellung', pflicht: true },
      { was: 'Nachweis der Verfügungsberechtigung oder Zustimmung des Eigentümers', pflicht: false },
    ],
    gebuehren: [
      { position: 'Bauvorbescheid', betrag: 'etwa 50 bis 500 Euro', art: 'landesrecht', hinweis: 'Je nach Umfang der Fragestellung und Land.' },
    ],
    fristen: [
      'Geltungsdauer des Vorbescheids: meist drei Jahre, teils verlängerbar.',
      'Bearbeitungsfristen wie beim Bauantrag, meist kürzer.',
    ],
    bearbeitungsdauer: 'Ein bis drei Monate.',
    ablauf: [
      { nr: 1, titel: 'Frage formulieren', detail: 'Zum Beispiel: Ist die Errichtung eines Zweifamilienhauses mit zwei Vollgeschossen und Satteldach auf dem Flurstück X planungsrechtlich zulässig? Vage Fragen erzeugen vage Antworten.', akteur: 'Bürger' },
      { nr: 2, titel: 'Unterlagen zusammenstellen', detail: 'Lageplan und eine grobe Skizze genügen meist.', akteur: 'Bürger' },
      { nr: 3, titel: 'Einreichen', detail: 'Über die Gemeinde an die Bauaufsicht.', akteur: 'Bürger' },
      { nr: 4, titel: 'Vorbescheid erhalten', detail: 'Er ist ein Verwaltungsakt und bindet die Behörde im Rahmen der gestellten Fragen. Auf dieser Basis kann der Kaufvertrag geschlossen oder die Planung beauftragt werden.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      'Landesbauordnungen - Vorbescheid',
      '§ 29 ff. Baugesetzbuch',
    ],
    online: { moeglich: true, hinweis: 'Über die digitalen Bauportale der Länder.' },
    haeufigeFehler: [
      'Zu unbestimmte Fragen stellen.',
      'Erwarten, dass der Vorbescheid den Bauantrag ersetzt - er klärt nur Teilfragen.',
      'Die Geltungsdauer verstreichen lassen.',
    ],
    faq: [
      { frage: 'Lohnt sich das?', antwort: 'Ja, besonders vor einem Grundstückskauf oder bei ungewöhnlichen Vorhaben. Ein negativer Vorbescheid für ein paar hundert Euro ist besser als ein abgelehnter Bauantrag nach Architektenhonorar.' },
      { frage: 'Darf ich mit dem Vorbescheid bauen?', antwort: 'Nein. Er klärt nur Fragen verbindlich vor; die Baugenehmigung ist weiterhin nötig.' },
    ],
    verwandt: ['bauantrag', 'denkmalschutz-erlaubnis'],
    eskalation: 'Bei Grundstückskäufen mit unklarem Baurecht oder Außenbereichslagen an die Bauaufsichtsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Landesrecht; Geltungsdauer und Gebühren unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'denkmalschutz-erlaubnis',
    cluster: 'bauen-wohnen',
    name: 'Denkmalrechtliche Erlaubnis beantragen',
    sprechName: 'Denkmalrechtliche Erlaubnis',
    synonyme: ['denkmalschutz', 'denkmal', 'denkmalrechtliche erlaubnis', 'altbau sanieren', 'fenster denkmal', 'denkmalgeschütztes haus', 'denkmalliste', 'steuerabschreibung denkmal'],
    leikaBezug: 'Denkmalrechtliche Erlaubnis (LeiKa 99062001)',
    kurzbeschreibung: 'Veränderungen an Baudenkmälern und in ihrer Umgebung bedürfen einer denkmalrechtlichen Erlaubnis - zusätzlich zu einer etwaigen Baugenehmigung. Das gilt auch für Fenster, Farbanstriche, Dacheindeckungen und Solaranlagen.',
    zustaendigkeit: {
      stelle: 'Untere Denkmalschutzbehörde bei Kreis oder kreisfreier Stadt, fachlich begleitet vom Landesamt für Denkmalpflege',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Das Gebäude ist als Denkmal eingetragen oder unterliegt als Teil eines Ensembles oder Denkmalbereichs dem Schutz.',
      'Die geplante Maßnahme verändert das Erscheinungsbild oder die Substanz.',
      'Auch Maßnahmen in der Umgebung eines Denkmals können erlaubnispflichtig sein.',
    ],
    unterlagen: [
      { was: 'Antragsformular', pflicht: true },
      { was: 'Beschreibung der geplanten Maßnahme', pflicht: true },
      { was: 'Fotos des Bestands', pflicht: true },
      { was: 'Zeichnungen, Detailpläne, Materialmuster', pflicht: false, hinweis: 'Bei Fenstern etwa Profilschnitte, Glasart, Sprossenteilung.' },
      { was: 'Restauratorische Befunduntersuchung', pflicht: false, hinweis: 'Bei substanziellen Eingriffen oft gefordert.' },
    ],
    gebuehren: [
      { position: 'Denkmalrechtliche Erlaubnis', betrag: 'etwa 50 bis 500 Euro', art: 'landesrecht', hinweis: 'Einige Länder erheben für Erhaltungsmaßnahmen keine Gebühr.' },
      { position: 'Bescheinigung für die Steuerabschreibung', betrag: 'etwa 100 bis 1.000 Euro oder nach Bausumme', art: 'landesrecht' },
    ],
    fristen: [
      'Vor Beginn der Maßnahme beantragen - eine nachträgliche Genehmigung ist die Ausnahme.',
      'Bescheinigung für die Steuerabschreibung: möglichst vor Baubeginn abstimmen, sonst droht der Verlust der Förderfähigkeit.',
    ],
    bearbeitungsdauer: 'Vier Wochen bis mehrere Monate, je nach Eingriffstiefe und Beteiligung des Landesamts.',
    ablauf: [
      { nr: 1, titel: 'Denkmaleigenschaft klären', detail: 'Fragen Sie bei der unteren Denkmalschutzbehörde nach der Eintragung. In einigen Ländern gilt das nachrichtliche, in anderen das konstitutive Eintragungsprinzip.', akteur: 'Bürger' },
      { nr: 2, titel: 'Frühzeitig Beratung suchen', detail: 'Die Denkmalpflege berät kostenfrei. Ein Abstimmungsgespräch vor der Planung spart Zeit und Geld und erhöht die Bewilligungschancen erheblich.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag stellen', detail: 'Mit Fotos und präziser Maßnahmenbeschreibung, oft zusammen mit dem Bauantrag.', akteur: 'Bürger' },
      { nr: 4, titel: 'Erlaubnis mit Auflagen', detail: 'Typische Auflagen betreffen Materialien, Handwerkstechniken, Farbgebung und die Dokumentation der Arbeiten.', akteur: 'Behörde' },
      { nr: 5, titel: 'Förderung und Steuervorteile nutzen', detail: 'Erhöhte Absetzungen nach § 7i und § 10f EStG für Herstellungskosten an Denkmälern setzen die Bescheinigung der Denkmalbehörde voraus - und die Abstimmung vor Beginn der Arbeiten. Daneben gibt es Zuschüsse von Land, Denkmalstiftungen und Kommune.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Denkmalschutzgesetze der Länder',
      '§ 7i, 10f, 11b Einkommensteuergesetz - Erhöhte Absetzungen bei Baudenkmälern',
      'Landesbauordnungen für die Verzahnung mit dem Baugenehmigungsverfahren',
    ],
    online: { moeglich: true, hinweis: 'Zunehmend über die digitalen Bauportale; die fachliche Abstimmung erfolgt meist im Ortstermin.' },
    haeufigeFehler: [
      'Fenster tauschen oder streichen ohne Erlaubnis - der häufigste Verstoß, oft mit Rückbauanordnung und Bußgeld.',
      'Mit den Arbeiten beginnen, bevor die Bescheinigung für die Steuerabschreibung abgestimmt ist.',
      'Annehmen, Innenräume seien nicht geschützt - der Schutz kann Grundrisse, Treppen, Stuck und Türen erfassen.',
      'Solaranlagen ohne Abstimmung montieren.',
    ],
    faq: [
      { frage: 'Darf ich in einem Denkmal Solaranlagen anbringen?', antwort: 'Häufig ja, mit Auflagen zur Anordnung und Sichtbarkeit. Mehrere Länder haben den Denkmalschutz zugunsten erneuerbarer Energien gelockert - die Abstimmung bleibt aber nötig.' },
      { frage: 'Welche Steuervorteile gibt es?', antwort: 'Bei vermieteten Denkmälern können Herstellungskosten für Erhaltungsmaßnahmen über zwölf Jahre erhöht abgeschrieben werden, bei Eigennutzung über zehn Jahre als Sonderausgaben. Voraussetzung ist die Bescheinigung der Denkmalbehörde.' },
      { frage: 'Muss ich mein Denkmal sanieren?', antwort: 'Es besteht eine Erhaltungspflicht im Rahmen der Zumutbarkeit. Ist die Erhaltung wirtschaftlich unzumutbar, kann das im Einzelfall geltend gemacht werden.' },
    ],
    verwandt: ['bauantrag', 'bauvoranfrage', 'grundsteuer'],
    eskalation: 'Bei Abrissabsichten, Zumutbarkeitsfragen oder Rückbauanordnungen an die Denkmalschutzbehörde weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Denkmalschutz ist Landesrecht - Eintragungsprinzip, Erlaubnispflichten und Gebühren unterscheiden sich deutlich.' },
    stand: '2026-08',
  },
  {
    id: 'abgeschlossenheitsbescheinigung',
    cluster: 'bauen-wohnen',
    name: 'Abgeschlossenheitsbescheinigung beantragen',
    sprechName: 'Abgeschlossenheitsbescheinigung',
    synonyme: ['abgeschlossenheitsbescheinigung', 'wohnungseigentum', 'teilungserklärung', 'eigentumswohnung bilden', 'aufteilung haus', 'weg'],
    leikaBezug: 'Abgeschlossenheitsbescheinigung (LeiKa 99056012)',
    kurzbeschreibung: 'Wer ein Gebäude in Wohnungseigentum aufteilen will, braucht eine Bescheinigung der Bauaufsichtsbehörde, dass die Wohnungen baulich abgeschlossen sind. Sie ist Voraussetzung für die Eintragung im Grundbuch.',
    zustaendigkeit: {
      stelle: 'Untere Bauaufsichtsbehörde beziehungsweise Bauamt der Stadt oder des Kreises',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Die Wohnungen sind baulich vollständig gegeneinander und gegen fremde Räume abgeschlossen - eigener abschließbarer Zugang, eigene Küche, eigenes Bad und WC.',
      'Aufteilungsplan mit eindeutiger Nummerierung aller Räume je Sondereigentumseinheit.',
      'Stellplätze gelten als abgeschlossen, wenn sie dauerhaft markiert sind.',
    ],
    unterlagen: [
      { was: 'Antragsformular', pflicht: true },
      { was: 'Aufteilungsplan in mehrfacher Ausfertigung', pflicht: true, hinweis: 'Maßstäblich, meist 1:100, mit fortlaufender Nummerierung aller Räume jeder Einheit - von einer bauvorlageberechtigten Person erstellt.' },
      { was: 'Grundbuchauszug', pflicht: true },
      { was: 'Baugenehmigung oder Bestandsnachweis des Gebäudes', pflicht: false },
    ],
    gebuehren: [
      { position: 'Abgeschlossenheitsbescheinigung', betrag: 'etwa 100 bis 800 Euro', art: 'landesrecht', hinweis: 'Häufig gestaffelt nach der Zahl der Einheiten.' },
      { position: 'Notarielle Teilungserklärung und Grundbucheintragung', betrag: 'nach Notar- und Gerichtskostengesetz', art: 'bundeseinheitlich' },
    ],
    fristen: ['Keine Frist. Die Bescheinigung ist unbefristet gültig, solange sich die baulichen Verhältnisse nicht ändern.'],
    bearbeitungsdauer: 'Vier bis zwölf Wochen.',
    ablauf: [
      { nr: 1, titel: 'Aufteilungsplan erstellen lassen', detail: 'Durch eine bauvorlageberechtigte Person. Jede Einheit erhält eine Nummer, jeder Raum wird zugeordnet - auch Keller und Stellplätze.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag einreichen', detail: 'Bei der Bauaufsichtsbehörde mit Plänen und Grundbuchauszug.', akteur: 'Bürger' },
      { nr: 3, titel: 'Prüfung', detail: 'Geprüft wird nur die bauliche Abgeschlossenheit, nicht die Genehmigungsfähigkeit oder Wohnqualität.', akteur: 'Behörde' },
      { nr: 4, titel: 'Teilungserklärung beim Notar', detail: 'Mit der Bescheinigung und dem Aufteilungsplan wird die Teilungserklärung notariell beurkundet.', akteur: 'Bürger' },
      { nr: 5, titel: 'Grundbuchanlage', detail: 'Das Grundbuchamt legt für jede Einheit ein eigenes Wohnungsgrundbuch an.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 3, 7 Wohnungseigentumsgesetz - Begründung von Wohnungseigentum',
      '§ 7 Abs. 4 WEG - Aufteilungsplan und Abgeschlossenheitsbescheinigung',
      'Allgemeine Verwaltungsvorschrift für die Ausstellung von Bescheinigungen nach dem WEG',
    ],
    online: { moeglich: true, hinweis: 'In vielen Kommunen digital einreichbar.' },
    haeufigeFehler: [
      'Aufteilungspläne selbst zeichnen - sie müssen von einer bauvorlageberechtigten Person stammen.',
      'Keller und Stellplätze in der Nummerierung vergessen.',
      'Annehmen, die Bescheinigung ersetze eine Baugenehmigung für einen Umbau.',
      'In Gebieten mit Umwandlungsverbot nach § 250 BauGB die Genehmigungspflicht für die Umwandlung von Miet- in Eigentumswohnungen übersehen.',
    ],
    faq: [
      { frage: 'Prüft die Behörde die Wohnqualität?', antwort: 'Nein, nur die bauliche Abgeschlossenheit. Bauordnungsrechtliche Mängel bleiben davon unberührt.' },
      { frage: 'Darf ich mein Mietshaus einfach aufteilen?', antwort: 'In Gebieten mit angespanntem Wohnungsmarkt kann die Umwandlung nach § 250 BauGB genehmigungspflichtig sein. Zudem haben Mieter ein Vorkaufsrecht.' },
    ],
    verwandt: ['bauantrag', 'grundsteuer'],
    eskalation: 'Bei Umwandlungsverboten, Milieuschutzgebieten oder Altbauten ohne Bestandsschutz an das Bauamt weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Bundesrechtliche Grundlage im WEG, Gebühren landes- und kommunalrechtlich.' },
    stand: '2026-08',
  },
];
