/** Stufe 2: Leistungen des Clusters "Bildung, Schule und Kultur". */
export const LEISTUNGEN = [
  {
    id: 'schulanmeldung',
    cluster: 'bildung-kultur',
    name: 'Kind zur Schule anmelden',
    sprechName: 'Schulanmeldung',
    synonyme: ['einschulung', 'schulanmeldung', 'kind einschulen', 'eingeschult', 'wird eingeschult', 'kommt in die schule', 'schulanfang', 'grundschule anmelden', 'schulwechsel', 'schulpflicht', 'sprengelschule', 'gestattungsantrag schule', 'zurückstellung'],
    leikaBezug: 'Schulanmeldung und Einschulung (LeiKa 99065001)',
    kurzbeschreibung: 'Kinder werden im Jahr vor der Einschulung an der zuständigen Grundschule angemeldet. Die Anmeldung ist Pflicht; über Zurückstellung, vorzeitige Einschulung und den Besuch einer anderen Schule entscheiden Schulleitung und Schulamt.',
    zustaendigkeit: {
      stelle: 'Zuständige Grundschule beziehungsweise das Schulamt; für Beförderung und Betreuung das Schulverwaltungsamt der Kommune',
      ebene: 'land',
      hinweis: 'Schulrecht ist Landesrecht - Stichtage, Sprengelbindung und Verfahren unterscheiden sich erheblich zwischen den Ländern.',
    },
    voraussetzungen: [
      'Das Kind wird bis zum landesrechtlichen Stichtag - meist 30. Juni oder 30. September - sechs Jahre alt.',
      'Wohnsitz im Schulbezirk beziehungsweise Sprengel, soweit das Land eine Sprengelbindung kennt.',
      'Nachweis der Masernimpfung oder Immunität nach dem Masernschutzgesetz - ohne Nachweis darf die Schule das Kind zwar aufnehmen, muss es aber dem Gesundheitsamt melden.',
      'Teilnahme an der schulärztlichen Untersuchung, in fast allen Ländern verpflichtend.',
    ],
    unterlagen: [
      { was: 'Geburtsurkunde des Kindes', pflicht: true },
      { was: 'Personalausweis der Sorgeberechtigten', pflicht: true },
      { was: 'Meldebescheinigung', pflicht: false },
      { was: 'Impfnachweis Masern', pflicht: true },
      { was: 'Sorgerechtsnachweis bei getrennt lebenden Eltern', pflicht: false },
      { was: 'Bei Schulwechsel: letztes Zeugnis und Abmeldebescheinigung der bisherigen Schule', pflicht: false },
      { was: 'Bei Gestattungsantrag: Begründung, etwa Betreuungssituation oder Geschwisterkind', pflicht: false },
    ],
    gebuehren: [
      { position: 'Schulanmeldung und Schulbesuch an öffentlichen Schulen', betrag: '0,00 Euro', art: 'landesrecht' },
      { position: 'Lernmittel', betrag: '0 Euro bis Eigenanteil je nach Land', art: 'landesrecht', hinweis: 'Einige Länder haben vollständige Lernmittelfreiheit, andere Eigenanteile oder Ausleihsysteme.' },
      { position: 'Betreuung im Ganztag oder Hort', betrag: 'kommunal, meist einkommensabhängig', art: 'kommunal' },
      { position: 'Schülerbeförderung', betrag: 'Übernahme ab Mindestentfernung', art: 'kommunal', hinweis: 'Typisch ab 2 Kilometern in der Grundschule und 3 bis 4 Kilometern an weiterführenden Schulen.' },
    ],
    fristen: [
      'Anmeldung meist im Herbst des Vorjahres, teils schon im Frühjahr - die Schule lädt schriftlich ein.',
      'Gestattungsanträge für eine andere Schule: gleichzeitig mit der Anmeldung.',
      'Zurückstellung: Antrag meist bis zum Frühjahr vor der Einschulung, mit schulärztlicher Stellungnahme.',
      'Widerspruch gegen Schulentscheidungen: ein Monat.',
    ],
    bearbeitungsdauer: 'Die Anmeldung selbst dauert einen Termin. Entscheidungen über Zurückstellung oder Gestattung fallen meist im Frühjahr vor der Einschulung.',
    ablauf: [
      { nr: 1, titel: 'Einladung abwarten oder selbst aktiv werden', detail: 'Die Kommune ermittelt schulpflichtige Kinder über das Melderegister und lädt schriftlich ein. Kommt keine Einladung, melden Sie sich selbst bei der zuständigen Schule.', akteur: 'Bürger' },
      { nr: 2, titel: 'Zuständige Schule ermitteln', detail: 'In Ländern mit Sprengelbindung ist die Schule durch die Adresse festgelegt. In anderen Ländern besteht freie Schulwahl mit Kapazitätsvorbehalt.', akteur: 'Bürger' },
      { nr: 3, titel: 'Anmeldetermin wahrnehmen', detail: 'Meist mit dem Kind; häufig verbunden mit einer Einschätzung der Sprachentwicklung.', akteur: 'Bürger' },
      { nr: 4, titel: 'Schulärztliche Untersuchung', detail: 'Vom Gesundheitsamt organisiert; sie prüft Seh- und Hörvermögen, Sprache, Motorik und den Impfstatus.', akteur: 'Behörde' },
      { nr: 5, titel: 'Besondere Anträge stellen', detail: 'Zurückstellung bei fehlender Schulfähigkeit, vorzeitige Einschulung für jüngere Kinder, Gestattung für eine andere Schule, Feststellung sonderpädagogischen Förderbedarfs.', akteur: 'Bürger' },
      { nr: 6, titel: 'Betreuung und Beförderung organisieren', detail: 'Ganztag, Hort und Schülerfahrkarte werden meist getrennt bei der Kommune beantragt - oft mit eigenen Fristen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Schulgesetze der Länder - Schulpflicht, Stichtage, Schulbezirke',
      '§ 20 Abs. 8 ff. Infektionsschutzgesetz - Masernschutz',
      'Schülerbeförderungssatzungen der Kommunen',
      '§ 28 Zweites Buch Sozialgesetzbuch - Bildung und Teilhabe',
    ],
    online: { moeglich: true, hinweis: 'Wachsende Zahl von Kommunen bietet die Online-Anmeldung; der persönliche Termin bleibt meist Teil des Verfahrens.' },
    haeufigeFehler: [
      'Die Einladung ignorieren - die Anmeldung ist Pflicht, nicht Angebot.',
      'Den Gestattungsantrag zu spät stellen.',
      'Den Masernnachweis nicht rechtzeitig besorgen.',
      'Betreuung und Schulweg erst nach der Einschulung regeln.',
      'Die Zurückstellung ohne schulärztliche Grundlage beantragen.',
    ],
    faq: [
      { frage: 'Kann ich mein Kind an einer anderen Schule anmelden?', antwort: 'In Ländern mit Schulbezirken brauchen Sie einen Gestattungsantrag mit Begründung - etwa Betreuung durch Großeltern, Arbeitsweg oder Geschwisterkind. In Ländern mit freier Schulwahl entscheidet die Kapazität.' },
      { frage: 'Mein Kind ist noch nicht so weit.', antwort: 'Eine Zurückstellung ist in den meisten Ländern möglich, meist auf Antrag mit schulärztlicher Stellungnahme. Die Voraussetzungen wurden vielerorts verschärft - die Regel ist die fristgerechte Einschulung.' },
      { frage: 'Wird der Schulweg bezahlt?', antwort: 'Ab bestimmten Mindestentfernungen übernimmt die Kommune die Kosten, meist ab 2 Kilometern in der Grundschule. Bei gefährlichen Schulwegen kann auch darunter übernommen werden.' },
    ],
    verwandt: ['kita-platz', 'bildung-und-teilhabe', 'wohnsitz-anmeldung'],
    eskalation: 'Bei sonderpädagogischem Förderbedarf, abgelehnten Gestattungsanträgen oder Schulverweigerung an Schulleitung und Schulamt weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Schulrecht ist Landesrecht - Stichtage, Sprengel und Zurückstellungsregeln unterscheiden sich deutlich.' },
    stand: '2026-08',
  },
  {
    id: 'bafoeg',
    cluster: 'bildung-kultur',
    name: 'BAföG beantragen',
    sprechName: 'BAföG beantragen',
    synonyme: ['bafög', 'ausbildungsförderung', 'studienfinanzierung', 'bafög antrag', 'schüler bafög', 'studierendenwerk', 'bafög amt', 'aufstiegs bafög'],
    leikaBezug: 'Ausbildungsförderung nach dem BAföG (LeiKa 99065010)',
    kurzbeschreibung: 'BAföG fördert Schülerinnen, Schüler und Studierende, wenn die eigenen Mittel und die der Eltern nicht ausreichen. Für Studierende ist es zur Hälfte Zuschuss und zur Hälfte zinsloses Darlehen, für Schülerinnen und Schüler voller Zuschuss.',
    zustaendigkeit: {
      stelle: 'Amt für Ausbildungsförderung beim Studierendenwerk für Studierende; beim Kreis oder der Stadt für Schülerinnen und Schüler',
      ebene: 'land',
      hinweis: 'Für Meister- und Fortbildungsförderung ist das Aufstiegs-BAföG bei anderen Stellen angesiedelt.',
    },
    voraussetzungen: [
      'Förderungsfähige Ausbildung an einer anerkannten Einrichtung.',
      'Deutsche Staatsangehörigkeit oder eine der im BAföG genannten aufenthaltsrechtlichen Konstellationen.',
      'Altersgrenze: grundsätzlich Beginn der Ausbildung vor dem 45. Lebensjahr, mit Ausnahmen.',
      'Bedürftigkeit: Einkommen und Vermögen der Auszubildenden sowie Einkommen der Eltern werden angerechnet; elternunabhängige Förderung ist in bestimmten Fällen möglich.',
      'Bei Studierenden: Nachweis über Leistungen nach dem vierten Fachsemester.',
      'Ein Fachrichtungswechsel ist nur aus wichtigem Grund und in der Regel bis zum Beginn des vierten Semesters unschädlich.',
    ],
    unterlagen: [
      { was: 'Formblätter 1 bis 9 je nach Konstellation', pflicht: true },
      { was: 'Immatrikulations- oder Schulbescheinigung', pflicht: true },
      { was: 'Einkommensnachweise der Eltern aus dem vorletzten Kalenderjahr', pflicht: true, hinweis: 'Steuerbescheide; bei erheblichem Einkommensrückgang ist ein Aktualisierungsantrag möglich.' },
      { was: 'Nachweise über eigenes Einkommen und Vermögen', pflicht: true },
      { was: 'Mietvertrag bei auswärtiger Unterbringung', pflicht: false },
      { was: 'Leistungsnachweis nach dem 4. Fachsemester', pflicht: false },
    ],
    gebuehren: [
      { position: 'Antrag', betrag: '0,00 Euro', art: 'keine' },
      { position: 'Förderungshöchstsatz für Studierende', betrag: 'Grundbedarf plus Wohn- und Versicherungszuschläge', art: 'bundeseinheitlich', hinweis: 'Die Sätze werden regelmäßig angepasst - erfragen Sie den aktuellen Höchstsatz beim Amt für Ausbildungsförderung.' },
      { position: 'Studienstartgeld', betrag: 'einmalig 1.000 Euro', art: 'bundeseinheitlich', hinweis: 'Für Erstantragsteller unter 25 aus Familien mit Sozialleistungsbezug; seit dem 29. BAföG-Änderungsgesetz.' },
      { position: 'Darlehensanteil', betrag: '50 Prozent, zinslos', art: 'bundeseinheitlich', hinweis: 'Die Rückzahlung ist auf 77 Monatsraten und einen Höchstbetrag gedeckelt; sie beginnt fünf Jahre nach Ende der Förderungshöchstdauer.' },
    ],
    fristen: [
      'Zahlung ab dem Antragsmonat - nicht rückwirkend. Ein formloser Antrag zu Monatsbeginn sichert den Monat.',
      'Folgeantrag: mindestens zwei Monate vor Ablauf des Bewilligungszeitraums, sonst entsteht eine Zahlungslücke.',
      'Leistungsnachweis: zum Ende des vierten Fachsemesters.',
      'Widerspruch: ein Monat.',
    ],
    bearbeitungsdauer: 'Sechs Wochen bis mehrere Monate, zu Semesterbeginn deutlich länger. Vorausleistungen und Abschlagszahlungen sind möglich.',
    ablauf: [
      { nr: 1, titel: 'Sofort formlos beantragen', detail: 'Ein kurzes Schreiben oder die Online-Antragstellung sichert den Monat. Unterlagen können nachgereicht werden.', akteur: 'Bürger' },
      { nr: 2, titel: 'Unterlagen sammeln', detail: 'Vor allem die Steuerbescheide der Eltern aus dem vorletzten Kalenderjahr - das ist erfahrungsgemäß der zeitkritische Teil.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag online stellen', detail: 'Über BAföG Digital oder das Portal des Landes, mit BundID oder Online-Ausweisfunktion.', akteur: 'Bürger' },
      { nr: 4, titel: 'Prüfung', detail: 'Das Amt ermittelt Bedarf, rechnet Einkommen und Vermögen an und setzt den Förderbetrag fest.', akteur: 'Behörde' },
      { nr: 5, titel: 'Sonderfälle prüfen', detail: 'Aktualisierungsantrag bei aktuell gesunkenem Elterneinkommen, Vorausleistung bei Zahlungsverweigerung der Eltern, elternunabhängige Förderung nach längerer Erwerbstätigkeit, Verlängerung bei Behinderung, Schwangerschaft oder Kinderbetreuung.', akteur: 'Bürger' },
      { nr: 6, titel: 'Rückzahlung planen', detail: 'Sie beginnt fünf Jahre nach Ende der Förderungshöchstdauer, ist zinslos und auf einen Höchstbetrag gedeckelt. Bei geringem Einkommen kann sie auf Antrag freigestellt werden.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 1 ff. Bundesausbildungsförderungsgesetz - Grundsatz und förderungsfähige Ausbildungen',
      '§ 7 BAföG - Erstausbildung und Fachrichtungswechsel',
      '§ 11 ff. BAföG - Bedarf, Einkommen und Vermögen',
      '§ 15 BAföG - Förderungsdauer',
      '§ 18 ff. BAföG - Darlehensrückzahlung',
      '§ 24 BAföG - Aktualisierungsantrag',
      '§ 36 BAföG - Vorausleistung',
    ],
    online: { moeglich: true, hinweis: 'Vollständig digital über BAföG Digital möglich, inklusive Identifikation mit der Online-Ausweisfunktion und Upload der Nachweise.' },
    haeufigeFehler: [
      'Erst nach Semesterbeginn beantragen - es gibt keine Rückwirkung.',
      'Den Folgeantrag zu spät stellen.',
      'Den Aktualisierungsantrag nicht kennen, obwohl das Elterneinkommen aktuell deutlich niedriger ist.',
      'Den Leistungsnachweis nach dem vierten Semester vergessen.',
      'Bei Zahlungsverweigerung der Eltern keine Vorausleistung beantragen.',
      'Fachrichtungswechsel ohne Beratung vornehmen und den Anspruch verlieren.',
    ],
    faq: [
      { frage: 'Muss ich alles zurückzahlen?', antwort: 'Studierende zahlen die Hälfte als zinsloses Darlehen zurück, gedeckelt auf einen Höchstbetrag und höchstens 77 Monatsraten. Schüler-BAföG ist voller Zuschuss.' },
      { frage: 'Meine Eltern verdienen zu viel, wollen aber nichts zahlen.', antwort: 'Beantragen Sie Vorausleistung nach § 36 BAföG. Das Amt zahlt dann und holt sich das Geld bei den Eltern.' },
      { frage: 'Meine Eltern verdienen jetzt deutlich weniger als vor zwei Jahren.', antwort: 'Stellen Sie einen Aktualisierungsantrag nach § 24 Abs. 3 BAföG - dann wird das laufende Kalenderjahr zugrunde gelegt.' },
      { frage: 'Bekomme ich auch Wohngeld?', antwort: 'Nein. Wer dem Grunde nach BAföG-berechtigt ist, ist vom Wohngeld ausgeschlossen.' },
    ],
    verwandt: ['wohngeld', 'schulanmeldung', 'bildung-und-teilhabe'],
    eskalation: 'Bei Fachrichtungswechsel, Überschreiten der Förderungshöchstdauer, Auslandsförderung oder Härtefällen an das Amt für Ausbildungsförderung und die Sozialberatung des Studierendenwerks weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesgesetz; Sätze und Freibeträge werden regelmäßig angepasst - immer als Stand kennzeichnen.' },
    stand: '2026-08',
  },
  {
    id: 'schuelerbefoerderung',
    cluster: 'bildung-kultur',
    name: 'Schülerbeförderung und Schülerfahrkarte beantragen',
    sprechName: 'Schülerbeförderung',
    synonyme: ['schülerticket', 'schülerfahrkarte', 'schulweg', 'schulbus', 'fahrtkosten schule', 'schülerbeförderung', 'deutschlandticket schule'],
    leikaBezug: 'Schülerbeförderung - Kostenübernahme (LeiKa 99065015)',
    kurzbeschreibung: 'Die Kommune übernimmt die notwendigen Kosten des Schulwegs, wenn der Weg zur nächstgelegenen zuständigen Schule eine Mindestentfernung überschreitet oder besonders gefährlich ist.',
    zustaendigkeit: {
      stelle: 'Schulverwaltungsamt der Stadt oder des Kreises als Schulträger; die Ausgabe der Fahrkarten erfolgt häufig über die Schule',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Besuch der nächstgelegenen zuständigen Schule der gewählten Schulform - wer freiwillig eine weiter entfernte Schule besucht, erhält meist nur die Kosten bis zur nächstgelegenen.',
      'Mindestentfernung nach Satzung: typischerweise 2 Kilometer in der Grundschule, 3 bis 4 Kilometer an weiterführenden Schulen.',
      'Unabhängig von der Entfernung bei anerkannt gefährlichem Schulweg oder bei Behinderung.',
    ],
    unterlagen: [
      { was: 'Antragsformular des Schulträgers', pflicht: true },
      { was: 'Schulbescheinigung', pflicht: true },
      { was: 'Meldebescheinigung oder Adressnachweis', pflicht: false },
      { was: 'Bei Behinderung: ärztliches Attest oder Schwerbehindertenausweis', pflicht: false },
      { was: 'Bei gefährlichem Schulweg: Begründung und gegebenenfalls Stellungnahme der Schule', pflicht: false },
    ],
    gebuehren: [
      { position: 'Fahrkarte bei Anspruch', betrag: '0,00 Euro', art: 'kommunal', hinweis: 'Einige Länder erheben einen Eigenanteil.' },
      { position: 'Schülerticket ohne Anspruch', betrag: 'vergünstigter Tarif des Verkehrsverbunds', art: 'sonstige', hinweis: 'Vielerorts als Deutschlandticket für Schülerinnen und Schüler zu einem reduzierten Preis.' },
      { position: 'Erstattung von Fahrtkosten mit dem Privat-Pkw', betrag: 'Kilometerpauschale nach Satzung', art: 'kommunal', hinweis: 'Nur wenn kein zumutbares öffentliches Verkehrsmittel verfügbar ist.' },
    ],
    fristen: [
      'Antrag möglichst vor Schuljahresbeginn, oft mit Frist im Frühjahr.',
      'Nachträgliche Erstattung ist häufig ausgeschlossen oder auf das laufende Schuljahr begrenzt.',
    ],
    bearbeitungsdauer: 'Zwei bis sechs Wochen; zum Schuljahresbeginn länger.',
    ablauf: [
      { nr: 1, titel: 'Anspruch prüfen', detail: 'Entfernung auf dem kürzesten zumutbaren Fußweg messen, nicht Luftlinie. Die Satzung des Schulträgers nennt die Grenzen.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag stellen', detail: 'Meist über die Schule, zunehmend auch online.', akteur: 'Bürger' },
      { nr: 3, titel: 'Fahrkarte erhalten', detail: 'Ausgabe über Schule oder Verkehrsunternehmen.', akteur: 'Behörde' },
      { nr: 4, titel: 'Bei Ablehnung', detail: 'Prüfen Sie die Begründung: Wurde die richtige Schule als nächstgelegene angesetzt? Ist der Weg tatsächlich zumutbar? Widerspruch ist binnen eines Monats möglich.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Schulgesetze der Länder - Schülerbeförderung',
      'Schülerbeförderungssatzungen der Kreise und kreisfreien Städte',
      '§ 28 Abs. 4 Zweites Buch Sozialgesetzbuch - Schülerbeförderung im Rahmen von Bildung und Teilhabe',
    ],
    online: { moeglich: true, hinweis: 'In vielen Kommunen online beantragbar.' },
    haeufigeFehler: [
      'Luftlinie statt Fußweg messen.',
      'Die Antragsfrist vor Schuljahresbeginn verpassen.',
      'Bei freiwilliger Wahl einer entfernteren Schule volle Erstattung erwarten.',
      'Bei geringem Einkommen die Übernahme über Bildung und Teilhabe nicht prüfen.',
    ],
    faq: [
      { frage: 'Ab welcher Entfernung wird gezahlt?', antwort: 'Das regelt die Satzung des Schulträgers. Verbreitet sind 2 Kilometer für die Grundschule und 3 bis 4 Kilometer für weiterführende Schulen.' },
      { frage: 'Mein Kind geht auf eine weiter entfernte Schule.', antwort: 'Dann werden in der Regel nur die Kosten bis zur nächstgelegenen zuständigen Schule übernommen - es sei denn, es gibt einen anerkannten Grund für die Wahl.' },
      { frage: 'Der Schulweg ist gefährlich, aber kurz.', antwort: 'Bei anerkannt gefährlichen Schulwegen wird auch unterhalb der Mindestentfernung übernommen. Begründen Sie konkret - fehlende Gehwege, unbeleuchtete Strecken, stark befahrene Straßen ohne Querungshilfe.' },
    ],
    verwandt: ['schulanmeldung', 'bildung-und-teilhabe'],
    eskalation: 'Bei abgelehnten Anträgen, Inklusionsbedarf oder Streit über die zuständige Schule an das Schulverwaltungsamt weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Landesgesetzlicher Rahmen, kommunale Satzung im Detail - Entfernungsgrenzen und Eigenanteile unterscheiden sich.' },
    stand: '2026-08',
  },
];
