/** Stufe 2: Leistungen des Clusters "Eheschließung, Partnerschaft und Sterbefall". */
export const LEISTUNGEN = [
  {
    id: 'eheschliessung',
    cluster: 'ehe-tod',
    name: 'Eheschließung anmelden',
    sprechName: 'Eheschließung anmelden',
    synonyme: ['heiraten', 'hochzeit', 'eheschließung', 'trauung', 'standesamt heiraten', 'aufgebot', 'anmeldung eheschließung', 'trautermin', 'ehe anmelden'],
    leikaBezug: 'Eheschließung - Anmeldung (LeiKa 99012004)',
    kurzbeschreibung: 'Vor jeder Eheschließung prüft das Standesamt die Ehefähigkeit. Angemeldet wird beim Standesamt des Wohnorts eines der Verlobten; getraut werden darf danach bei jedem Standesamt in Deutschland.',
    zustaendigkeit: {
      stelle: 'Standesamt am Wohnsitz eines der Verlobten für die Anmeldung; das Trauungsstandesamt kann frei gewählt werden',
      ebene: 'kommunal',
      hinweis: 'Wohnen die Verlobten in verschiedenen Gemeinden, können Sie sich das Anmeldestandesamt aussuchen. Es leitet die Unterlagen an das Trauungsstandesamt weiter.',
    },
    voraussetzungen: [
      'Beide Verlobte sind volljährig - Ehen mit Minderjährigen sind seit 2017 unzulässig.',
      'Beide sind ledig, geschieden oder verwitwet; bestehende Ehen oder Lebenspartnerschaften müssen aufgelöst sein.',
      'Keine Verwandtschaft in gerader Linie und keine Geschwisterehe.',
      'Beide erscheinen persönlich zur Anmeldung; ist einer verhindert, kann er die Anmeldung schriftlich mit beglaubigtem Vordruck erklären.',
      'Bei ausländischen Verlobten: Ehefähigkeitszeugnis des Heimatstaates oder Befreiung durch das Oberlandesgericht.',
    ],
    unterlagen: [
      { was: 'Gültige Personalausweise oder Reisepässe beider Verlobter', pflicht: true },
      { was: 'Beglaubigter Ausdruck aus dem Geburtenregister', pflicht: true, hinweis: 'Nicht die alte Geburtsurkunde, sondern der aktuelle Ausdruck - meist nicht älter als sechs Monate. Auszustellen vom Standesamt des Geburtsortes.' },
      { was: 'Erweiterte Meldebescheinigung mit Familienstand', pflicht: true, hinweis: 'Vom Bürgeramt des Wohnorts, meist nicht älter als vier Wochen.' },
      { was: 'Bei Vorehe: Eheurkunde der letzten Ehe mit Auflösungsvermerk oder rechtskräftiges Scheidungsurteil', pflicht: false },
      { was: 'Bei verwitweten Personen: Sterbeurkunde des Ehegatten', pflicht: false },
      { was: 'Bei gemeinsamen Kindern: deren Geburtsurkunden', pflicht: false },
      { was: 'Bei ausländischer Staatsangehörigkeit: Ehefähigkeitszeugnis, Übersetzungen, Apostille oder Legalisation', pflicht: false, hinweis: 'Der aufwendigste Teil - planen Sie mehrere Monate ein.' },
    ],
    gebuehren: [
      { position: 'Anmeldung der Eheschließung, beide deutsch', betrag: 'etwa 40 bis 60 Euro', art: 'kommunal' },
      { position: 'Anmeldung mit Auslandsbezug', betrag: 'etwa 70 bis 120 Euro', art: 'kommunal' },
      { position: 'Trauung außerhalb der öffentlichen Sprechzeiten oder am Wochenende', betrag: 'etwa 60 bis 250 Euro zusätzlich', art: 'kommunal' },
      { position: 'Trauung an einem Außentrauort', betrag: 'etwa 100 bis 500 Euro', art: 'kommunal', hinweis: 'Schlösser, Leuchttürme, Museen - je nach Ort sehr unterschiedlich.' },
      { position: 'Eheurkunde', betrag: 'etwa 12 bis 15 Euro', art: 'kommunal' },
      { position: 'Stammbuch', betrag: 'etwa 20 bis 60 Euro', art: 'sonstige', hinweis: 'Freiwillig.' },
    ],
    fristen: [
      'Die Anmeldung ist sechs Monate gültig. Findet die Trauung später statt, ist die Prüfung zu wiederholen.',
      'Anmeldung frühestens sechs Monate vor dem gewünschten Termin.',
      'Ehefähigkeitszeugnisse ausländischer Staaten sind meist sechs Monate gültig.',
      'Beliebte Termine - Schnapszahlen, Samstage im Sommer - sind oft ein Jahr im Voraus vergeben; Termine reservieren viele Standesämter aber erst nach der Anmeldung.',
    ],
    bearbeitungsdauer: 'Bei rein deutschen Fällen zwei bis vier Wochen bis zur Freigabe. Mit Auslandsbezug drei bis zwölf Monate, insbesondere wenn eine Befreiung vom Ehefähigkeitszeugnis beim Oberlandesgericht nötig ist.',
    ablauf: [
      { nr: 1, titel: 'Beratungstermin beim Standesamt', detail: 'Klären Sie früh, welche Unterlagen in Ihrem Fall nötig sind - das hängt von Staatsangehörigkeit, Vorehen und Kindern ab.', akteur: 'Bürger' },
      { nr: 2, titel: 'Urkunden beschaffen', detail: 'Geburtenregisterausdruck beim Geburtsstandesamt, erweiterte Meldebescheinigung beim Bürgeramt, Scheidungsurteile beim Gericht.', akteur: 'Bürger' },
      { nr: 3, titel: 'Anmeldung persönlich vornehmen', detail: 'Beide Verlobte erscheinen, die Angaben werden protokolliert, die Ehefähigkeit wird geprüft.', akteur: 'Bürger' },
      { nr: 4, titel: 'Namensführung besprechen', detail: 'Sie können einen gemeinsamen Ehenamen bestimmen, Ihre Namen behalten oder einen Begleitnamen voranstellen oder anfügen. Die Erklärung kann bei der Trauung oder später abgegeben werden.', akteur: 'Bürger' },
      { nr: 5, titel: 'Termin festlegen', detail: 'Nach der Freigabe wird der Trautermin verbindlich gebucht - im eigenen oder in einem anderen Standesamt.', akteur: 'Bürger' },
      { nr: 6, titel: 'Trauung', detail: 'Beide erklären vor der Standesbeamtin oder dem Standesbeamten, die Ehe eingehen zu wollen. Trauzeugen sind seit 1998 freiwillig, höchstens zwei. Anschließend erhalten Sie die Eheurkunde.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 1303 ff. Bürgerliches Gesetzbuch - Ehefähigkeit und Eheverbote',
      '§ 1310 BGB - Mitwirkung des Standesbeamten',
      '§ 12 ff. Personenstandsgesetz - Anmeldung und Prüfung',
      '§ 1355 BGB - Ehename',
      'Artikel 13 EGBGB - Eheschließung mit Auslandsbezug',
    ],
    online: {
      moeglich: true,
      hinweis: 'Viele Standesämter bieten die Voranmeldung und die Terminreservierung online an; die eigentliche Anmeldung erfordert persönliches Erscheinen.',
    },
    haeufigeFehler: [
      'Eine alte Geburtsurkunde statt des beglaubigten Ausdrucks aus dem Geburtenregister vorlegen.',
      'Bei Auslandsbezug zu spät beginnen - Beschaffung, Übersetzung und Legalisation von Dokumenten dauern oft Monate.',
      'Den Trautermin buchen, bevor die Ehefähigkeit geprüft ist.',
      'Die Sechsmonatsfrist der Anmeldung verstreichen lassen.',
      'Annehmen, kirchliche Trauung ersetze die standesamtliche - rechtlich wirksam ist nur letztere.',
    ],
    faq: [
      { frage: 'Können wir in einer anderen Stadt heiraten?', antwort: 'Ja. Angemeldet wird am Wohnort, geheiratet werden darf bei jedem deutschen Standesamt. Ihr Anmeldestandesamt leitet die Unterlagen weiter.' },
      { frage: 'Welche Namen können wir führen?', antwort: 'Sie können einen gemeinsamen Ehenamen wählen - den Geburtsnamen oder aktuellen Namen eines Partners -, beide Namen behalten, oder eine Person stellt ihren Namen als Begleitnamen voran oder hängt ihn an. Ein gemeinsamer Doppelname für beide ist nach dem reformierten Namensrecht seit Mai 2025 ebenfalls möglich.' },
      { frage: 'Brauchen wir Trauzeugen?', antwort: 'Nein, seit 1998 freiwillig. Sie können bis zu zwei benennen; sie müssen volljährig sein und sich ausweisen.' },
      { frage: 'Was kostet das insgesamt?', antwort: 'Für einen einfachen Fall im Trauzimmer während der Sprechzeiten meist 60 bis 100 Euro inklusive Urkunde. Wochenendtermine, Außentrauorte und Auslandsbezug erhöhen das deutlich.' },
    ],
    verwandt: ['ehefaehigkeitszeugnis', 'personenstandsurkunde', 'kirchenaustritt', 'meldebescheinigung'],
    eskalation: 'Bei Auslandsbezug, Verdacht auf Scheinehe, ungeklärtem Personenstand oder Befreiungsverfahren beim Oberlandesgericht an das Standesamt weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Verfahren bundeseinheitlich, Gebühren kommunal sehr unterschiedlich - besonders bei Außentrauorten.' },
    stand: '2026-08',
  },
  {
    id: 'ehefaehigkeitszeugnis',
    cluster: 'ehe-tod',
    name: 'Ehefähigkeitszeugnis für eine Heirat im Ausland',
    sprechName: 'Ehefähigkeitszeugnis',
    synonyme: ['ehefähigkeitszeugnis', 'im ausland heiraten', 'ledigkeitsbescheinigung', 'heirat ausland', 'befreiung ehefähigkeitszeugnis'],
    leikaBezug: 'Ehefähigkeitszeugnis - Ausstellung (LeiKa 99012004)',
    kurzbeschreibung: 'Wer im Ausland heiraten will, braucht meist ein deutsches Ehefähigkeitszeugnis. Es bestätigt, dass der Eheschließung nach deutschem Recht nichts entgegensteht, und wird vom Standesamt des Wohnorts ausgestellt.',
    zustaendigkeit: {
      stelle: 'Standesamt des Wohnorts; bei Wohnsitz im Ausland das Standesamt des letzten inländischen Wohnsitzes oder das Standesamt I in Berlin',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Deutsche Staatsangehörigkeit oder Wohnsitz in Deutschland.',
      'Die Eheschließung ist nach deutschem Recht zulässig.',
      'Die Personalien und der Personenstand des ausländischen Partners sind nachgewiesen.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass beider Verlobter', pflicht: true },
      { was: 'Beglaubigter Ausdruck aus dem Geburtenregister', pflicht: true },
      { was: 'Erweiterte Meldebescheinigung', pflicht: true },
      { was: 'Nachweise über frühere Ehen und deren Auflösung', pflicht: false },
      { was: 'Urkunden des ausländischen Partners mit Übersetzung und Apostille oder Legalisation', pflicht: true },
    ],
    gebuehren: [
      { position: 'Ehefähigkeitszeugnis', betrag: 'etwa 40 bis 90 Euro', art: 'kommunal', hinweis: 'Bei Auslandsbezug am oberen Rand.' },
      { position: 'Beglaubigungen und Übersetzungen', betrag: 'je nach Umfang', art: 'sonstige' },
    ],
    fristen: [
      'Das Zeugnis ist sechs Monate gültig.',
      'Beantragen Sie es früh - die Beschaffung ausländischer Urkunden dauert oft Monate.',
    ],
    bearbeitungsdauer: 'Zwei bis acht Wochen, bei komplexem Auslandsbezug länger.',
    ablauf: [
      { nr: 1, titel: 'Anforderungen des Ziellandes klären', detail: 'Fragen Sie bei der zuständigen Auslandsvertretung oder der dortigen Behörde, welche Dokumente in welcher Form verlangt werden - Apostille, Legalisation, beglaubigte Übersetzung.', akteur: 'Bürger' },
      { nr: 2, titel: 'Unterlagen beschaffen', detail: 'Deutsche Urkunden beim jeweiligen Standesamt, ausländische im Heimatstaat des Partners.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag beim Standesamt stellen', detail: 'Persönlich oder schriftlich, meist mit Vollmacht des Partners.', akteur: 'Bürger' },
      { nr: 4, titel: 'Prüfung und Ausstellung', detail: 'Das Standesamt prüft die Ehefähigkeit nach deutschem Recht.', akteur: 'Behörde' },
      { nr: 5, titel: 'Nach der Auslandsheirat', detail: 'Die Ehe ist in Deutschland grundsätzlich anerkannt. Eine Nachbeurkundung im deutschen Eheregister beim Standesamt des Wohnorts ist freiwillig, erleichtert aber alle späteren Nachweise - etwa für Namensführung und Rentenansprüche.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 39 Personenstandsgesetz - Ehefähigkeitszeugnis',
      'Artikel 13 EGBGB - anwendbares Recht',
      '§ 34 Personenstandsgesetz - Nachbeurkundung von Auslandseheschließungen',
    ],
    online: { moeglich: true, hinweis: 'Antragstellung in einigen Kommunen online; die Urkunden müssen im Original vorgelegt werden.' },
    haeufigeFehler: [
      'Zu spät beginnen.',
      'Apostille oder Legalisation vergessen.',
      'Nach der Auslandstrauung die Nachbeurkundung unterlassen und später bei Rente oder Namensführung Nachweisprobleme bekommen.',
    ],
    faq: [
      { frage: 'Ist meine Ehe aus dem Ausland in Deutschland gültig?', antwort: 'Grundsätzlich ja, wenn die Formvorschriften des Eheschließungsortes eingehalten wurden und keine deutschen Eheverbote entgegenstehen. Eine Nachbeurkundung ist freiwillig, aber praktisch.' },
      { frage: 'Mein Partner ist Nicht-EU-Bürger - was ist zu beachten?', antwort: 'Zusätzlich zum Ehefähigkeitszeugnis werden Aufenthaltsfragen relevant. Für den Nachzug nach Deutschland ist ein Visum der deutschen Auslandsvertretung nötig.' },
    ],
    verwandt: ['eheschliessung', 'personenstandsurkunde', 'auslaender-aufenthaltserlaubnis'],
    eskalation: 'Bei Staaten ohne Ehefähigkeitszeugnis, bei Befreiungsverfahren des Oberlandesgerichts oder bei Zweifeln an ausländischen Urkunden an das Standesamt weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Verfahren bundesrechtlich, Gebühren und Aufwand kommunal unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'sterbefall',
    cluster: 'ehe-tod',
    name: 'Sterbefall beurkunden und Sterbeurkunde erhalten',
    sprechName: 'Sterbefall und Sterbeurkunde',
    synonyme: ['sterbefall', 'todesfall', 'sterbeurkunde', 'gestorben', 'verstorben', 'todesbescheinigung', 'tod anzeigen', 'sterbefall melden'],
    leikaBezug: 'Sterbefall - Beurkundung (LeiKa 99012009)',
    kurzbeschreibung: 'Jeder Sterbefall ist spätestens am dritten Werktag beim Standesamt des Sterbeortes anzuzeigen. Das Standesamt beurkundet den Tod und stellt Sterbeurkunden aus, die für Renten, Versicherungen, Banken und das Nachlassgericht gebraucht werden.',
    zustaendigkeit: {
      stelle: 'Standesamt des Sterbeortes',
      ebene: 'kommunal',
      hinweis: 'Bei Todesfällen im Ausland ist eine Nachbeurkundung beim Standesamt des letzten Wohnorts oder beim Standesamt I in Berlin möglich.',
    },
    voraussetzungen: [
      'Anzeigepflichtig sind: das Krankenhaus oder die Einrichtung, in der der Tod eintrat, sonst Angehörige, Wohnungsinhaber oder jede Person, die beim Tod zugegen war.',
      'In der Praxis übernimmt fast immer das Bestattungsunternehmen die Anzeige.',
      'Für die Bestellung weiterer Urkunden: Angehöriger in gerader Linie, Ehegatte, Geschwister oder rechtliches Interesse.',
    ],
    unterlagen: [
      { was: 'Todesbescheinigung des Arztes', pflicht: true, hinweis: 'Wird bei der Leichenschau ausgestellt und enthält den vertraulichen Teil zur Todesursache.' },
      { was: 'Personalausweis oder Reisepass der verstorbenen Person', pflicht: true },
      { was: 'Geburtsurkunde beziehungsweise beglaubigter Registerausdruck der verstorbenen Person', pflicht: true },
      { was: 'Bei Verheirateten: Eheurkunde oder beglaubigter Ausdruck aus dem Eheregister', pflicht: false },
      { was: 'Bei Geschiedenen: rechtskräftiges Scheidungsurteil', pflicht: false },
      { was: 'Bei Verwitweten: Sterbeurkunde des vorverstorbenen Ehegatten', pflicht: false },
      { was: 'Personalausweis der anzeigenden Person', pflicht: true },
    ],
    gebuehren: [
      { position: 'Beurkundung des Sterbefalls', betrag: '0,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Erste Sterbeurkunde', betrag: 'etwa 12 bis 15 Euro', art: 'kommunal' },
      { position: 'Jede weitere Ausfertigung im selben Vorgang', betrag: 'etwa 5 bis 8 Euro', art: 'kommunal' },
      { position: 'Urkunden für gesetzliche Renten- und Sozialversicherungszwecke', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Nach § 68 PStG gebührenfrei - ausdrücklich danach fragen.' },
    ],
    fristen: [
      'Anzeige des Sterbefalls: spätestens am dritten Werktag nach dem Tod.',
      'Bestattung: nach Landesrecht meist zwischen vier und zehn Tagen nach Eintritt des Todes, Feuerbestattungen teils später.',
      'Rentenzahlung: Der Sterbefall ist der Rentenversicherung unverzüglich zu melden; überzahlte Renten werden zurückgefordert.',
      'Ausschlagung einer Erbschaft: sechs Wochen ab Kenntnis von Erbfall und Berufungsgrund, sechs Monate bei Auslandsaufenthalt.',
    ],
    bearbeitungsdauer: 'Die Beurkundung erfolgt meist binnen ein bis drei Werktagen, damit die Bestattung stattfinden kann.',
    ablauf: [
      { nr: 1, titel: 'Arzt zur Leichenschau rufen', detail: 'Bei erwartetem Tod der Hausarzt, sonst der ärztliche Bereitschaftsdienst oder Notarzt. Er stellt die Todesbescheinigung aus.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bestattungsunternehmen beauftragen', detail: 'Es übernimmt Überführung, Behördengänge und meist die Anzeige beim Standesamt. Vergleichen Sie Angebote - die Preise unterscheiden sich erheblich.', akteur: 'Bürger' },
      { nr: 3, titel: 'Sterbefall beim Standesamt anzeigen', detail: 'Mit Todesbescheinigung und Personenstandsurkunden. Bestellen Sie gleich mehrere Sterbeurkunden - fünf bis zehn sind üblich.', akteur: 'Bürger' },
      { nr: 4, titel: 'Bestattung organisieren', detail: 'Grabstelle bei der Friedhofsverwaltung, Termin, Trauerfeier. Es gilt Friedhofszwang; Ausnahmen wie Seebestattung oder Bestattungswald sind geregelt.', akteur: 'Bürger' },
      { nr: 5, titel: 'Stellen informieren', detail: 'Rentenversicherung, Krankenkasse, Lebens- und Sterbegeldversicherungen, Banken, Vermieter, Versorger, Rundfunkbeitrag, Arbeitgeber, Vereine, Abo-Verträge.', akteur: 'Bürger' },
      { nr: 6, titel: 'Nachlass regeln', detail: 'Testament beim Nachlassgericht abliefern - dazu ist jeder verpflichtet, der eines besitzt. Erbschein beantragen, wenn er verlangt wird. Über die Ausschlagung binnen sechs Wochen entscheiden, wenn Überschuldung droht.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 28 ff. Personenstandsgesetz - Anzeige und Beurkundung des Sterbefalls',
      '§ 68 Personenstandsgesetz - Gebührenfreiheit',
      'Bestattungsgesetze der Länder',
      '§ 1942 ff. Bürgerliches Gesetzbuch - Annahme und Ausschlagung der Erbschaft',
      '§ 2259 BGB - Ablieferungspflicht für Testamente',
    ],
    online: {
      moeglich: true,
      hinweis: 'Weitere Sterbeurkunden können bei vielen Standesämtern online nachbestellt werden. Die Erstanzeige läuft praktisch immer über das Bestattungsunternehmen.',
    },
    haeufigeFehler: [
      'Zu wenige Sterbeurkunden bestellen - fast jede Stelle verlangt ein Original.',
      'Die Gebührenfreiheit für Renten- und Sozialversicherungszwecke nicht nutzen.',
      'Das Testament nicht beim Nachlassgericht abliefern.',
      'Die Sechswochenfrist für die Erbausschlagung verstreichen lassen und für Schulden haften.',
      'Bankkonten der verstorbenen Person nutzen, ohne die Erbenstellung zu klären.',
    ],
    faq: [
      { frage: 'Wie viele Sterbeurkunden brauche ich?', antwort: 'Rechnen Sie mit fünf bis zehn: Rentenversicherung, Krankenkasse, Versicherungen, Banken, Nachlassgericht, Vermieter, Versorger.' },
      { frage: 'Wer trägt die Bestattungskosten?', antwort: 'Zunächst die Erben, daneben trifft die bestattungspflichtigen Angehörigen nach Landesrecht eine Pflicht. Reicht das Vermögen nicht, übernimmt das Sozialamt auf Antrag die erforderlichen Kosten nach § 74 SGB XII.' },
      { frage: 'Wie schnell muss die Bestattung stattfinden?', antwort: 'Das regelt das Landesrecht, meist innerhalb von vier bis zehn Tagen. Erdbestattungen haben oft kürzere Fristen als Feuerbestattungen.' },
      { frage: 'Was ist mit dem Erbschein?', antwort: 'Er ist nicht immer nötig. Banken akzeptieren häufig ein notarielles Testament mit Eröffnungsprotokoll. Ein Erbschein wird beim Nachlassgericht beantragt und kostet nach Nachlasswert.' },
    ],
    verwandt: ['bestattung', 'personenstandsurkunde', 'wohnsitz-abmeldung'],
    eskalation: 'Bei ungeklärter Todesursache, Todesfällen im Ausland, unbekannten Erben oder Bestattungskostenübernahme an Standesamt, Ordnungsamt oder Sozialamt weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Beurkundung bundeseinheitlich, Bestattungsrecht ist Landesrecht mit deutlich unterschiedlichen Fristen.' },
    stand: '2026-08',
  },
  {
    id: 'bestattung',
    cluster: 'ehe-tod',
    name: 'Bestattung und Grabstelle regeln',
    sprechName: 'Bestattung und Grabstelle',
    synonyme: ['bestattung', 'beerdigung', 'grab', 'grabstelle', 'friedhof', 'urne', 'einäscherung', 'feuerbestattung', 'seebestattung', 'bestattungskosten', 'sozialbestattung'],
    leikaBezug: 'Bestattung - Friedhofsangelegenheiten (LeiKa 99012009)',
    kurzbeschreibung: 'Die Bestattung ist landesrechtlich geregelt und wird über die Friedhofsverwaltung organisiert. Angehörige sind bestattungspflichtig; reicht das Vermögen nicht, übernimmt das Sozialamt die erforderlichen Kosten.',
    zustaendigkeit: {
      stelle: 'Friedhofsverwaltung der Gemeinde oder des Kirchenträgers, Ordnungsamt bei Bestattungspflicht, Sozialamt bei Kostenübernahme',
      ebene: 'kommunal',
      hinweis: 'Die Fristen und die Zulässigkeit von Bestattungsarten bestimmt das Bestattungsgesetz des jeweiligen Landes.',
    },
    voraussetzungen: [
      'Sterbeurkunde beziehungsweise Bestattungserlaubnis des Standesamts.',
      'Bei Feuerbestattung zusätzlich die zweite Leichenschau durch einen Amtsarzt oder eine dafür bestimmte Ärztin.',
      'Bestattungspflichtig sind nach Landesrecht in der Regel in dieser Reihenfolge: Ehegatte oder Lebenspartner, volljährige Kinder, Eltern, Geschwister, Großeltern, Enkel.',
    ],
    unterlagen: [
      { was: 'Sterbeurkunde', pflicht: true },
      { was: 'Bestattungsverfügung oder Testament mit Wünschen der verstorbenen Person', pflicht: false, hinweis: 'Der Wille der verstorbenen Person ist maßgeblich, soweit er bekannt ist.' },
      { was: 'Nachweis über ein bestehendes Nutzungsrecht an einer Grabstelle', pflicht: false },
      { was: 'Bei Sozialbestattung: Nachweise über Vermögen und Einkommen der Bestattungspflichtigen', pflicht: false },
    ],
    gebuehren: [
      { position: 'Bestattung insgesamt', betrag: 'etwa 3.000 bis 10.000 Euro', art: 'sonstige', hinweis: 'Sarg oder Urne, Bestatterleistungen, Friedhofsgebühren, Grabmal, Trauerfeier. Anonyme oder Baumbestattungen sind deutlich günstiger.' },
      { position: 'Friedhofsgebühren für Grabnutzung', betrag: 'etwa 500 bis 4.000 Euro je nach Grabart und Laufzeit', art: 'kommunal' },
      { position: 'Einäscherung', betrag: 'etwa 250 bis 600 Euro', art: 'sonstige' },
      { position: 'Zweite Leichenschau vor Feuerbestattung', betrag: 'etwa 40 bis 130 Euro', art: 'landesrecht' },
      { position: 'Sozialbestattung', betrag: 'Übernahme der erforderlichen Kosten', art: 'einkommensabhaengig', hinweis: 'Nach § 74 SGB XII, wenn den Verpflichteten die Kostentragung nicht zuzumuten ist. Der Antrag ist vor der Beauftragung zu stellen.' },
    ],
    fristen: [
      'Bestattungsfristen je Land, meist vier bis zehn Tage nach Eintritt des Todes.',
      'Urnenbeisetzung meist innerhalb von sechs Wochen nach der Einäscherung.',
      'Grabnutzungsrechte laufen je nach Grabart 15 bis 30 Jahre; Verlängerung rechtzeitig beantragen.',
      'Antrag auf Sozialbestattung möglichst vor Beauftragung des Bestatters.',
    ],
    bearbeitungsdauer: 'Die Organisation dauert in der Regel drei bis zehn Tage. Kostenübernahmeanträge beim Sozialamt zwei bis acht Wochen.',
    ablauf: [
      { nr: 1, titel: 'Willen der verstorbenen Person ermitteln', detail: 'Bestattungsverfügung, Vorsorgevertrag, Testament oder mündlich geäußerte Wünsche gehen den Vorstellungen der Angehörigen vor.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bestattungsart wählen', detail: 'Erd- oder Feuerbestattung; Wahl-, Reihen-, Urnen-, Rasen-, Baum- oder anonymes Grab. Seebestattung und Bestattungswald sind zulässig, Aschenverstreuung im Privatgarten in fast allen Ländern nicht.', akteur: 'Bürger' },
      { nr: 3, titel: 'Angebote vergleichen', detail: 'Bestatter sind verpflichtet, Preise transparent zu machen. Die Unterschiede sind erheblich - holen Sie zwei bis drei Angebote ein.', akteur: 'Bürger' },
      { nr: 4, titel: 'Grabstelle bei der Friedhofsverwaltung erwerben', detail: 'Sie erwerben ein Nutzungsrecht auf Zeit, nicht das Grundstück. Achten Sie auf Laufzeit, Verlängerbarkeit und Pflegepflichten.', akteur: 'Bürger' },
      { nr: 5, titel: 'Bei fehlenden Mitteln: Sozialamt einschalten', detail: 'Antrag auf Übernahme der Bestattungskosten nach § 74 SGB XII - möglichst bevor Sie den Bestatter beauftragen. Übernommen werden nur die erforderlichen Kosten einer einfachen, würdigen Bestattung.', akteur: 'Bürger' },
      { nr: 6, titel: 'Grabpflege regeln', detail: 'Nach der Friedhofssatzung sind Sie zur Pflege verpflichtet. Pflegefreie Grabarten oder Dauergrabpflegeverträge nehmen diese Last ab.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Bestattungsgesetze der Länder',
      'Kommunale Friedhofs- und Friedhofsgebührensatzungen',
      '§ 74 Zwölftes Buch Sozialgesetzbuch - Bestattungskosten',
      '§ 1968 Bürgerliches Gesetzbuch - Kostentragung durch den Erben',
    ],
    online: { moeglich: false, hinweis: 'Grabstellen und Bestattungstermine werden meist telefonisch oder persönlich vereinbart; einige Kommunen bieten Online-Formulare für Grabnutzungsrechte.' },
    haeufigeFehler: [
      'Den Bestatter beauftragen, bevor ein Antrag auf Sozialbestattung gestellt ist - dann kann die Übernahme scheitern.',
      'Nur ein Angebot einholen.',
      'Die Grabpflegepflicht und die Verlängerung des Nutzungsrechts übersehen.',
      'Annehmen, man könne die Asche mit nach Hause nehmen - in fast allen Ländern unzulässig.',
      'Als Erbe zahlen, obwohl man die Erbschaft ausschlagen wollte - die Bestattungspflicht bleibt bestehen, die Kostentragung kann aber getrennt zu beurteilen sein.',
    ],
    faq: [
      { frage: 'Muss ich die Bestattung bezahlen, wenn ich das Erbe ausschlage?', antwort: 'Die Bestattungspflicht nach Landesrecht bleibt auch bei Ausschlagung bestehen. Die Kosten können Sie unter Umständen vom Erben oder bei Mittellosigkeit vom Sozialamt ersetzt bekommen.' },
      { frage: 'Gibt es Sterbegeld?', antwort: 'Das gesetzliche Sterbegeld der Krankenkassen wurde 2004 abgeschafft. Nur Beamte und Angehörige einzelner Versorgungssysteme erhalten noch Sterbegeld.' },
      { frage: 'Was ist eine Sozialbestattung?', antwort: 'Übernahme der erforderlichen Bestattungskosten durch das Sozialamt, wenn die Verpflichteten sie nicht tragen können. Sie ist würdig, aber schlicht: einfacher Sarg, Reihengrab, keine aufwendige Trauerfeier.' },
      { frage: 'Gilt in Deutschland Friedhofszwang?', antwort: 'Ja, mit engen Ausnahmen: Seebestattung, Bestattungswälder mit Friedhofsstatus, in Bremen unter Voraussetzungen die Ausbringung der Asche auf bestimmten Flächen.' },
    ],
    verwandt: ['sterbefall', 'sozialhilfe'],
    eskalation: 'Bei fehlenden Angehörigen, ungeklärter Bestattungspflicht oder eiligen Kostenübernahmen an Ordnungsamt und Sozialamt weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Bestattungsrecht ist Landesrecht und unterscheidet sich erheblich - Fristen, zulässige Bestattungsarten und Pflichten immer für das konkrete Land prüfen.' },
    stand: '2026-08',
  },
  {
    id: 'personenstandsurkunde',
    cluster: 'ehe-tod',
    name: 'Personenstandsurkunden bestellen',
    sprechName: 'Urkunden vom Standesamt bestellen',
    synonyme: ['urkunde bestellen', 'geburtsurkunde nachbestellen', 'eheurkunde', 'sterbeurkunde bestellen', 'lebenspartnerschaftsurkunde', 'beglaubigter registerausdruck', 'internationale urkunde', 'apostille'],
    leikaBezug: 'Personenstandsurkunde - Ausstellung (LeiKa 99012012)',
    kurzbeschreibung: 'Geburts-, Ehe-, Lebenspartnerschafts- und Sterbeurkunden stellt das Standesamt aus, das den Personenstandsfall beurkundet hat. Beglaubigte Registerausdrucke enthalten mehr Angaben als die Urkunden.',
    zustaendigkeit: {
      stelle: 'Standesamt des Ereignisortes - Geburtsort, Eheschließungsort, Sterbeort',
      ebene: 'kommunal',
      hinweis: 'Für Ereignisse im Ausland, die in Deutschland nachbeurkundet wurden, ist das Standesamt I in Berlin zuständig.',
    },
    voraussetzungen: [
      'Antragsberechtigt sind die Person selbst, Ehegatten, Vorfahren und Abkömmlinge in gerader Linie sowie Personen mit rechtlichem Interesse.',
      'Geschwister nur mit berechtigtem Interesse; entfernte Verwandte müssen es glaubhaft machen.',
      'Nach Ablauf der Fortführungsfristen - 110 Jahre bei Geburten, 80 bei Ehen, 30 bei Sterbefällen - gehen die Register ins Archiv über, dann gelten die Archivgesetze.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Angaben zum Ereignis: Name, Datum, Ort, Standesamt', pflicht: true },
      { was: 'Nachweis des rechtlichen Interesses', pflicht: false, hinweis: 'Etwa Erbschein, gerichtliche Aufforderung, Vollmacht.' },
    ],
    gebuehren: [
      { position: 'Urkunde oder beglaubigter Registerausdruck', betrag: 'etwa 12 bis 15 Euro', art: 'kommunal' },
      { position: 'Weitere Ausfertigung im selben Vorgang', betrag: 'etwa 5 bis 8 Euro', art: 'kommunal' },
      { position: 'Internationale Urkunde nach dem CIEC-Übereinkommen', betrag: 'etwa 12 bis 18 Euro', art: 'kommunal', hinweis: 'Mehrsprachig, für viele europäische Staaten ohne Übersetzung verwendbar.' },
      { position: 'Apostille', betrag: 'etwa 15 bis 30 Euro', art: 'landesrecht', hinweis: 'Wird nicht vom Standesamt, sondern von der übergeordneten Behörde erteilt - je nach Land Regierungspräsidium, Landratsamt oder Innenministerium.' },
      { position: 'Urkunden für Renten-, Eltern- oder Kindergeldzwecke', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Gebührenfrei nach § 68 PStG.' },
    ],
    fristen: ['Keine. Empfänger verlangen häufig aktuelle Ausdrucke, meist nicht älter als sechs Monate.'],
    bearbeitungsdauer: 'Vor Ort sofort, per Post oder online meist drei bis zehn Werktage.',
    ablauf: [
      { nr: 1, titel: 'Richtiges Standesamt finden', detail: 'Immer das Standesamt des Ereignisortes. Bei Gemeindefusionen hat oft eine Nachfolgegemeinde die Register übernommen.', akteur: 'Bürger' },
      { nr: 2, titel: 'Urkundenart wählen', detail: 'Urkunde für den normalen Nachweis, beglaubigter Registerausdruck mit allen Randvermerken - etwa für Eheschließungen oder Einbürgerungen. Internationale Fassung für das Ausland.', akteur: 'Bürger' },
      { nr: 3, titel: 'Bestellen', detail: 'Online, schriftlich oder persönlich. Geben Sie den Verwendungszweck an, um Gebührenbefreiungen zu nutzen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Gegebenenfalls Apostille beantragen', detail: 'Für die Verwendung im Ausland; bei Staaten außerhalb des Haager Übereinkommens ist eine Legalisation durch die Auslandsvertretung nötig.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 55 Personenstandsgesetz - Personenstandsurkunden',
      '§ 62, 63 Personenstandsgesetz - Antragsberechtigung',
      '§ 68 Personenstandsgesetz - Gebührenfreiheit',
      'Haager Übereinkommen zur Befreiung ausländischer öffentlicher Urkunden von der Legalisation',
    ],
    online: { moeglich: true, hinweis: 'Nahezu flächendeckend online bestellbar, häufig mit Kartenzahlung und Postversand.' },
    haeufigeFehler: [
      'Beim Wohnort statt beim Ereignisort bestellen.',
      'Urkunde statt beglaubigtem Registerausdruck bestellen, obwohl das Standesamt für die Eheschließung den Ausdruck verlangt.',
      'Apostille vergessen.',
      'Gebührenbefreiung für Renten- und Elterngeldzwecke nicht nutzen.',
    ],
    faq: [
      { frage: 'Was ist der Unterschied zwischen Urkunde und Registerausdruck?', antwort: 'Die Urkunde enthält die Kerndaten. Der beglaubigte Registerausdruck gibt den vollständigen Eintrag samt Randvermerken wieder - etwa Namensänderungen, Vaterschaftsanerkennungen oder Auflösungsvermerke.' },
      { frage: 'Ich brauche eine Urkunde von 1930 - geht das noch?', antwort: 'Geburtenregister werden 110 Jahre beim Standesamt fortgeführt, Eheregister 80 Jahre, Sterberegister 30. Danach liegen sie im Stadt- oder Landesarchiv, wo Sie ebenfalls Kopien erhalten.' },
      { frage: 'Ich lebe im Ausland - wie komme ich an eine Urkunde?', antwort: 'Online oder schriftlich beim zuständigen Standesamt mit Ausweiskopie; Versand ins Ausland ist üblich.' },
    ],
    verwandt: ['geburtsurkunde', 'eheschliessung', 'sterbefall'],
    eskalation: 'Bei historischen Registern, unklarer Zuständigkeit nach Gebietsreformen oder Auslandsurkunden an das Standesamt beziehungsweise Standesamt I Berlin weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Bundesrechtliche Grundlage, kommunale Gebührensätze.' },
    stand: '2026-08',
  },
  {
    id: 'kirchenaustritt',
    cluster: 'ehe-tod',
    name: 'Kirchenaustritt erklären',
    sprechName: 'Kirchenaustritt erklären',
    synonyme: ['kirchenaustritt', 'aus der kirche austreten', 'kirche austreten', 'austreten', 'austritt', 'kirche', 'kirchensteuer sparen', 'austritt religionsgemeinschaft', 'kirche verlassen'],
    leikaBezug: 'Kirchenaustritt - Erklärung (LeiKa 99000000)',
    kurzbeschreibung: 'Der Austritt aus einer Religionsgemeinschaft des öffentlichen Rechts wird persönlich vor dem Standesamt oder Amtsgericht erklärt - je nach Bundesland. Er beendet die Kirchensteuerpflicht mit Wirkung ab dem Folgemonat.',
    zustaendigkeit: {
      stelle: 'Je nach Bundesland Standesamt oder Amtsgericht des Wohnorts',
      ebene: 'land',
      hinweis: 'In Bayern, Baden-Württemberg, Nordrhein-Westfalen und weiteren Ländern das Standesamt; in Hessen, Bremen und einigen anderen das Amtsgericht. Erfragen Sie das für Ihren Wohnort.',
    },
    voraussetzungen: [
      'Vollendetes 14. Lebensjahr - ab dann ist man religionsmündig und erklärt selbst.',
      'Zwischen 12 und 14 Jahren kann das Kind nicht gegen seinen Willen zu einem anderen Bekenntnis angehalten werden; die Erklärung gibt der Sorgeberechtigte ab.',
      'Persönliches Erscheinen oder öffentlich beglaubigte schriftliche Erklärung.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Bei Verheirateten teilweise die Eheurkunde', pflicht: false },
      { was: 'Taufschein oder Kirchenmitgliedsnachweis', pflicht: false, hinweis: 'Meist nicht nötig; hilfreich, wenn die Gemeinde unklar ist.' },
    ],
    gebuehren: [
      { position: 'Austrittserklärung', betrag: 'etwa 10 bis 60 Euro', art: 'landesrecht', hinweis: 'In Bayern, Brandenburg und Bremen gebührenfrei, in anderen Ländern zwischen 10 und 60 Euro. Die Höhe legt das Landesrecht fest.' },
      { position: 'Austrittsbescheinigung', betrag: 'meist in der Gebühr enthalten', art: 'landesrecht' },
    ],
    fristen: [
      'Wirkung für die Kirchensteuer: je nach Landesrecht mit Ablauf des Monats der Erklärung oder des Folgemonats.',
      'Keine Rückwirkung - die Kirchensteuer des laufenden Monats bleibt in der Regel geschuldet.',
    ],
    bearbeitungsdauer: 'Die Erklärung wird sofort entgegengenommen. Die Bescheinigung erhalten Sie meist direkt, sonst binnen weniger Tage.',
    ablauf: [
      { nr: 1, titel: 'Zuständige Stelle klären', detail: 'Standesamt oder Amtsgericht - das entscheidet Ihr Bundesland.', akteur: 'Bürger' },
      { nr: 2, titel: 'Termin vereinbaren', detail: 'Vielerorts ohne Termin möglich, in Großstädten mit Voranmeldung.', akteur: 'Bürger' },
      { nr: 3, titel: 'Erklärung abgeben', detail: 'Persönlich und höchstpersönlich - eine Vertretung ist ausgeschlossen. Die Erklärung darf keine Bedingungen enthalten.', akteur: 'Bürger' },
      { nr: 4, titel: 'Bescheinigung aufbewahren', detail: 'Sie brauchen sie gegenüber Arbeitgeber und Finanzamt; die Meldebehörde und das Finanzamt werden zusätzlich automatisch informiert.', akteur: 'Bürger' },
      { nr: 5, titel: 'Folgen bedenken', detail: 'Kein kirchliches Begräbnis, keine Patenschaft, kein Zugang zu Sakramenten, mögliche arbeitsrechtliche Folgen bei kirchlichen Arbeitgebern.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Kirchenaustrittsgesetze der Länder',
      'Artikel 4 und 140 Grundgesetz in Verbindung mit Artikel 136 ff. Weimarer Reichsverfassung',
      'Kirchensteuergesetze der Länder',
      'Gesetz über die religiöse Kindererziehung',
    ],
    online: { moeglich: false, hinweis: 'Die Erklärung ist höchstpersönlich abzugeben oder öffentlich zu beglaubigen; rein digitale Wege bestehen bislang nicht.' },
    haeufigeFehler: [
      'Beim falschen Amt erscheinen - die Zuständigkeit unterscheidet sich je Land.',
      'Erwarten, dass die Kirchensteuer rückwirkend entfällt.',
      'Vergessen, den Arbeitgeber zu informieren, obwohl die elektronischen Lohnsteuerabzugsmerkmale automatisch aktualisiert werden - Nachfrage lohnt trotzdem.',
      'Übersehen, dass bei kirchlichen Arbeitgebern der Austritt arbeitsrechtliche Konsequenzen haben kann.',
    ],
    faq: [
      { frage: 'Ab wann spare ich Kirchensteuer?', antwort: 'Je nach Landesrecht ab dem Monat der Erklärung oder ab dem Folgemonat. Rückwirkend geht es nicht.' },
      { frage: 'Kann ich wieder eintreten?', antwort: 'Ja, der Wiedereintritt erfolgt bei der Religionsgemeinschaft selbst, nicht bei der Behörde.' },
      { frage: 'Was kostet der Austritt?', antwort: 'Je nach Bundesland zwischen 0 und etwa 60 Euro. Bayern, Brandenburg und Bremen erheben keine Gebühr.' },
    ],
    verwandt: ['eheschliessung', 'steuer-identifikationsnummer'],
    eskalation: 'Bei Fragen zur Kirchensteuerpflicht rückwirkender Zeiträume an das Finanzamt, bei Wiedereintritt an die Religionsgemeinschaft verweisen.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Zuständige Stelle, Gebühr und Wirkungszeitpunkt sind Landesrecht und unterscheiden sich deutlich.' },
    stand: '2026-08',
  },
];
