/** Stufe 2: Leistungen des Clusters "Familie, Kinder und Erziehung". */
export const LEISTUNGEN = [
  {
    id: 'geburtsurkunde',
    cluster: 'familie-kinder',
    name: 'Geburt anzeigen und Geburtsurkunde beantragen',
    sprechName: 'Geburtsurkunde beantragen',
    synonyme: ['geburtsurkunde', 'geburt anmelden', 'geburt anzeigen', 'kind geboren', 'baby urkunde', 'abstammungsurkunde', 'geburtenregister', 'internationale geburtsurkunde'],
    leikaBezug: 'Geburtsurkunde - Ausstellung (LeiKa 99012001)',
    kurzbeschreibung: 'Jede Geburt wird beim Standesamt des Geburtsortes beurkundet. Aus dem Geburtenregister werden Geburtsurkunden ausgestellt, die für Kindergeld, Elterngeld, Krankenversicherung und Kita gebraucht werden.',
    zustaendigkeit: {
      stelle: 'Standesamt des Geburtsortes - nicht des Wohnortes',
      ebene: 'kommunal',
      hinweis: 'Späterer Nachdruck von Urkunden ist ebenfalls nur beim Standesamt des Geburtsortes möglich. Bei Geburten im Ausland ist das Standesamt I in Berlin zuständig.',
    },
    voraussetzungen: [
      'Die Geburt hat in Deutschland stattgefunden.',
      'Für Urkundenbestellung: Sie sind die betroffene Person, ein Elternteil, Ehegatte, Kind oder haben ein rechtliches Interesse.',
    ],
    unterlagen: [
      { was: 'Geburtsanzeige der Klinik oder der Hebamme', pflicht: true, hinweis: 'Bei Klinikgeburten übernimmt das Krankenhaus die Anzeige, bei Hausgeburten die Hebamme oder ein Elternteil.' },
      { was: 'Personalausweise beider Eltern', pflicht: true },
      { was: 'Bei verheirateten Eltern: Eheurkunde oder beglaubigter Ausdruck aus dem Eheregister', pflicht: false },
      { was: 'Bei unverheirateten Eltern: Geburtsurkunden beider Eltern, Vaterschaftsanerkennung und gegebenenfalls Sorgeerklärung', pflicht: false },
      { was: 'Erklärung über den Familiennamen des Kindes', pflicht: true, hinweis: 'Bei unterschiedlichen Familiennamen der Eltern bestimmen die Sorgeberechtigten den Namen des Kindes.' },
    ],
    gebuehren: [
      { position: 'Beurkundung der Geburt', betrag: '0,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Erste Geburtsurkunde', betrag: 'etwa 12 bis 15 Euro', art: 'kommunal' },
      { position: 'Jede weitere Ausfertigung im selben Vorgang', betrag: 'etwa 5 bis 8 Euro', art: 'kommunal' },
      { position: 'Urkunden für Eltern- und Kindergeld', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Für Zwecke der Eltern-, Kinder- und Mutterschaftsleistungen werden Urkunden gebührenfrei ausgestellt (§ 68 PStG). Fragen Sie ausdrücklich danach.' },
      { position: 'Internationale Geburtsurkunde', betrag: 'etwa 12 bis 18 Euro', art: 'kommunal' },
    ],
    fristen: [
      'Anzeige der Geburt: binnen einer Woche (§ 18 PStG).',
      'Kindergeldantrag: möglichst sofort, rückwirkend nur sechs Monate.',
      'Elterngeldantrag: rückwirkend nur drei Monate.',
      'Vaterschaftsanerkennung: schon vor der Geburt möglich und oft sinnvoll.',
    ],
    bearbeitungsdauer: 'Bei Klinikgeburten stellt das Standesamt die Urkunden meist innerhalb von ein bis drei Wochen aus. Späterer Nachdruck dauert wenige Tage.',
    ablauf: [
      { nr: 1, titel: 'Namen des Kindes festlegen', detail: 'Vornamen frei wählbar, Familienname nach den Regeln des BGB. Bei unverheirateten Eltern mit gemeinsamem Sorgerecht bestimmen beide gemeinsam.', akteur: 'Bürger' },
      { nr: 2, titel: 'Unterlagen der Klinik übergeben', detail: 'Die Klinik leitet die Geburtsanzeige mit Ihren Unterlagen an das Standesamt weiter. Bringen Sie Ausweise und Urkunden schon zur Entbindung mit.', akteur: 'Bürger' },
      { nr: 3, titel: 'Beurkundung im Geburtenregister', detail: 'Das Standesamt trägt Name, Geburtsdatum, Geburtsort und Eltern ein.', akteur: 'Behörde' },
      { nr: 4, titel: 'Urkunden bestellen', detail: 'Bestellen Sie mehrere: für Kindergeld, Elterngeld, Krankenkasse, Kita und Ihre Unterlagen. Für Eltern- und Kindergeld sind sie gebührenfrei.', akteur: 'Bürger' },
      { nr: 5, titel: 'Folgeanträge stellen', detail: 'Kindergeld bei der Familienkasse, Elterngeld bei der Elterngeldstelle, Aufnahme in die Krankenversicherung, gegebenenfalls Anmeldung im Kita-Vormerksystem.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 18 ff. Personenstandsgesetz - Beurkundung der Geburt',
      '§ 55 Personenstandsgesetz - Personenstandsurkunden',
      '§ 68 Personenstandsgesetz - Gebührenfreiheit für bestimmte Zwecke',
      '§ 1616 ff. Bürgerliches Gesetzbuch - Name des Kindes',
    ],
    online: {
      moeglich: true,
      hinweis: 'Urkundenbestellung ist bei den meisten Standesämtern online möglich. Einige Länder bieten mit dem Verfahren "Geburt - Kombileistung" die gebündelte Beantragung von Geburtsurkunde, Kindergeld und Elterngeld an.',
    },
    haeufigeFehler: [
      'Zu wenige Urkunden bestellen und später mehrfach nachbestellen.',
      'Die Gebührenfreiheit für Eltern- und Kindergeldzwecke nicht nutzen.',
      'Bei unverheirateten Eltern die Vaterschaftsanerkennung erst nach der Geburt angehen.',
      'Beim Standesamt des Wohnorts statt des Geburtsorts anfragen.',
    ],
    faq: [
      { frage: 'Wie viele Urkunden brauche ich?', antwort: 'Rechnen Sie mit vier bis sechs: Kindergeld, Elterngeld, Krankenkasse, Kita, eigene Unterlagen, gegebenenfalls Arbeitgeber.' },
      { frage: 'Wie heißt mein Kind, wenn wir unterschiedliche Namen führen?', antwort: 'Bei gemeinsamer Sorge bestimmen Sie gemeinsam einen der beiden Familiennamen. Einigen Sie sich nicht binnen eines Monats, überträgt das Familiengericht einem Elternteil das Bestimmungsrecht.' },
      { frage: 'Unser Kind wurde im Ausland geboren.', antwort: 'Die ausländische Urkunde gilt meist, oft mit Apostille und Übersetzung. Eine Nachbeurkundung im deutschen Geburtenregister ist beim Standesamt I in Berlin möglich und für spätere deutsche Urkunden praktisch.' },
    ],
    verwandt: ['kindergeld', 'elterngeld', 'vaterschaftsanerkennung', 'kita-platz'],
    eskalation: 'Bei Auslandsgeburten, Zweifeln an der Abstammung, Leihmutterschaft oder Namensfragen mit Auslandsbezug an das Standesamt weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Verfahren bundeseinheitlich, Urkundengebühren kommunal leicht unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'kindergeld',
    cluster: 'familie-kinder',
    name: 'Kindergeld beantragen',
    sprechName: 'Kindergeld beantragen',
    synonyme: ['kindergeld', 'familienkasse', 'kindergeldantrag', 'geld für kinder', 'kindergeld beantragen', 'kinderzuschlag', 'kindergeld student'],
    leikaBezug: 'Kindergeld - Beantragung (LeiKa 99075001)',
    kurzbeschreibung: 'Kindergeld ist eine steuerliche Leistung für alle Kinder bis 18 Jahre, bei Ausbildung, Studium oder Behinderung darüber hinaus. Es wird bei der Familienkasse der Bundesagentur für Arbeit beantragt.',
    zustaendigkeit: {
      stelle: 'Familienkasse der Bundesagentur für Arbeit; für Angehörige des öffentlichen Dienstes teilweise der Dienstherr',
      ebene: 'bund',
      hinweis: 'Nicht die Kommune - Bürgerämter können nur weiterverweisen.',
    },
    voraussetzungen: [
      'Wohnsitz oder gewöhnlicher Aufenthalt in Deutschland oder unbeschränkte Steuerpflicht.',
      'Das Kind lebt in Ihrem Haushalt oder Sie zahlen überwiegend Unterhalt.',
      'Bis 18 Jahre voraussetzungslos; von 18 bis 25 nur bei Schule, Ausbildung, Studium, Freiwilligendienst oder Übergangszeiten von bis zu vier Monaten.',
      'Ohne Altersgrenze bei Behinderung, wenn diese vor dem 25. Geburtstag eingetreten ist und das Kind sich nicht selbst unterhalten kann.',
      'Für Nicht-EU-Staatsangehörige: Aufenthaltstitel, der zur Erwerbstätigkeit berechtigt.',
    ],
    unterlagen: [
      { was: 'Antrag auf Kindergeld mit Anlage Kind', pflicht: true },
      { was: 'Steuerliche Identifikationsnummer des Kindes und des Antragstellers', pflicht: true, hinweis: 'Die Steuer-ID des Kindes kommt automatisch nach der Geburt per Post vom Bundeszentralamt für Steuern.' },
      { was: 'Geburtsurkunde des Kindes', pflicht: true },
      { was: 'Bei volljährigen Kindern: Schul-, Ausbildungs- oder Immatrikulationsbescheinigung', pflicht: false },
      { was: 'Bei Nicht-EU-Bürgern: Aufenthaltstitel', pflicht: false },
    ],
    gebuehren: [
      { position: 'Antrag', betrag: '0,00 Euro', art: 'keine' },
      { position: 'Kindergeld je Kind und Monat', betrag: '255 Euro (2025), 259 Euro (ab 2026)', art: 'bundeseinheitlich', hinweis: 'Der Betrag wird regelmäßig angepasst. Prüfen Sie den aktuellen Wert bei der Familienkasse - hier handelt es sich um den Stand dieser Wissensbasis.' },
    ],
    fristen: [
      'Rückwirkende Zahlung nur für die letzten sechs Monate vor Antragseingang (§ 66 Abs. 3 EStG).',
      'Änderungen - Ausbildungsende, Auszug, Auslandsaufenthalt - sind unverzüglich zu melden.',
      'Bei volljährigen Kindern jährliche Nachweise über die Ausbildung.',
    ],
    bearbeitungsdauer: 'In der Regel vier bis sechs Wochen, bei Auslandsbezug oder unvollständigen Unterlagen länger. Die Zahlung erfolgt monatlich, der Auszahlungstag richtet sich nach der Endziffer der Kindergeldnummer.',
    ablauf: [
      { nr: 1, titel: 'Steuer-ID des Kindes abwarten oder abfragen', detail: 'Sie kommt einige Wochen nach der Geburt automatisch. Fehlt sie, können Sie sie beim Bundeszentralamt für Steuern erneut anfordern.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag online stellen', detail: 'Über den Onlinedienst der Familienkasse, wahlweise mit Online-Ausweisfunktion für die vollständig digitale Einreichung.', akteur: 'Bürger' },
      { nr: 3, titel: 'Anlage Kind ausfüllen', detail: 'Pro Kind eine Anlage; bei volljährigen Kindern zusätzlich Angaben zur Ausbildung.', akteur: 'Bürger' },
      { nr: 4, titel: 'Prüfung durch die Familienkasse', detail: 'Es wird geprüft, wer vorrangig berechtigt ist - bei getrennt lebenden Eltern derjenige, in dessen Haushalt das Kind lebt.', akteur: 'Behörde' },
      { nr: 5, titel: 'Bescheid und Zahlung', detail: 'Sie erhalten einen Bescheid mit Kindergeldnummer. Bewahren Sie diese auf - jede spätere Mitteilung läuft darüber.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 31, 32 Einkommensteuergesetz - Kinderfreibetrag und Kindergeld',
      '§ 62 bis 78 Einkommensteuergesetz - Kindergeldrecht',
      'Bundeskindergeldgesetz (BKGG) für Sonderfälle',
      'Verordnung (EG) Nr. 883/2004 bei grenzüberschreitenden Fällen',
    ],
    online: {
      moeglich: true,
      hinweis: 'Vollständig online über den Familienkassen-Onlinedienst. Mit der Online-Ausweisfunktion ist auch die Identifizierung digital möglich; sonst ist der Ausdruck mit Unterschrift nachzureichen.',
      voraussetzungen: ['Steuer-ID von Kind und Antragsteller', 'optional Online-Ausweisfunktion'],
    },
    haeufigeFehler: [
      'Zu lange warten - mehr als sechs Monate rückwirkend gibt es nicht.',
      'Bei volljährigen Kindern die Ausbildungsbescheinigung nicht nachreichen und eine Einstellung der Zahlung riskieren.',
      'Nach Trennung nicht klären, wer den Anspruch geltend macht - Doppelzahlungen werden zurückgefordert.',
      'Kindergeld und Kinderzuschlag verwechseln: Der Kinderzuschlag ist eine zusätzliche Leistung für Geringverdiener und wird gesondert beantragt.',
    ],
    faq: [
      { frage: 'Wie lange gibt es Kindergeld?', antwort: 'Bis 18 Jahre in jedem Fall. Bis 25, wenn das Kind in Schule, Ausbildung oder Studium ist, einen Freiwilligendienst leistet oder eine Übergangszeit von höchstens vier Monaten überbrückt. Ohne Altersgrenze bei einer vor dem 25. Geburtstag eingetretenen Behinderung.' },
      { frage: 'Zählt eigenes Einkommen des Kindes?', antwort: 'Seit 2012 grundsätzlich nicht mehr. Nur nach abgeschlossener Erstausbildung schadet eine Erwerbstätigkeit von mehr als 20 Wochenstunden.' },
      { frage: 'Was ist der Kinderzuschlag?', antwort: 'Eine Leistung für Eltern mit kleinem Einkommen, bis zu 297 Euro je Kind und Monat (Stand dieser Wissensbasis). Er wird ebenfalls bei der Familienkasse beantragt und ist an Einkommensgrenzen geknüpft.' },
    ],
    verwandt: ['elterngeld', 'geburtsurkunde', 'unterhaltsvorschuss', 'buergergeld'],
    eskalation: 'Bei grenzüberschreitenden Fällen, Rückforderungen, Trennungskonflikten oder Ablehnungen an die Familienkasse weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht. Die Beträge werden regelmäßig angepasst - immer als Stand kennzeichnen und auf die Familienkasse verweisen.' },
    stand: '2026-08',
  },
  {
    id: 'elterngeld',
    cluster: 'familie-kinder',
    name: 'Elterngeld beantragen',
    sprechName: 'Elterngeld beantragen',
    synonyme: ['elterngeld', 'basiselterngeld', 'elterngeldplus', 'partnerschaftsbonus', 'elternzeit geld', 'elterngeldstelle', 'elterngeld antrag'],
    leikaBezug: 'Elterngeld - Beantragung (LeiKa 99075002)',
    kurzbeschreibung: 'Elterngeld ersetzt einen Teil des wegfallenden Einkommens nach der Geburt. Es gibt Basiselterngeld, ElterngeldPlus und den Partnerschaftsbonus - kombinierbar und beantragt bei der Elterngeldstelle des Landes oder Kreises.',
    zustaendigkeit: {
      stelle: 'Elterngeldstelle - je nach Land beim Kreis, der Stadt, dem Landesamt für Soziales oder dem Versorgungsamt',
      ebene: 'land',
      hinweis: 'Die Zuständigkeit ist landesrechtlich sehr unterschiedlich organisiert. Fragen Sie nach der Stelle für Ihren Wohnort.',
    },
    voraussetzungen: [
      'Wohnsitz in Deutschland, Betreuung und Erziehung des Kindes im eigenen Haushalt.',
      'Keine oder höchstens 32 Wochenstunden Erwerbstätigkeit im Bezugszeitraum.',
      'Einkommensgrenze: Für Geburten ab 1. April 2025 entfällt der Anspruch ab 175.000 Euro zu versteuerndem Einkommen - für Paare und Alleinerziehende gleichermaßen.',
      'Bei Nicht-EU-Bürgern: Aufenthaltstitel, der zur Erwerbstätigkeit berechtigt.',
    ],
    unterlagen: [
      { was: 'Antragsformular des Landes, für jedes Elternteil eigens', pflicht: true },
      { was: 'Geburtsurkunde mit Verwendungszweck Elterngeld', pflicht: true, hinweis: 'Ausdrücklich diesen Zweck angeben - dann ist die Urkunde gebührenfrei.' },
      { was: 'Einkommensnachweise der zwölf Monate vor dem Geburtsmonat', pflicht: true, hinweis: 'Bei Angestellten Gehaltsabrechnungen, bei Selbstständigen der Steuerbescheid des letzten abgeschlossenen Veranlagungszeitraums.' },
      { was: 'Bescheinigung des Arbeitgebers über die Elternzeit', pflicht: true },
      { was: 'Bescheinigung der Krankenkasse über Mutterschaftsgeld', pflicht: false },
      { was: 'Nachweis über den Zuschuss des Arbeitgebers zum Mutterschaftsgeld', pflicht: false },
      { was: 'Personalausweise beider Eltern', pflicht: true },
    ],
    gebuehren: [
      { position: 'Antrag', betrag: '0,00 Euro', art: 'keine' },
      { position: 'Basiselterngeld', betrag: '300 bis 1.800 Euro monatlich', art: 'bundeseinheitlich', hinweis: 'In der Regel 65 bis 67 Prozent des wegfallenden Nettoeinkommens; bei niedrigem Einkommen steigt die Ersatzrate auf bis zu 100 Prozent.' },
      { position: 'ElterngeldPlus', betrag: '150 bis 900 Euro monatlich', art: 'bundeseinheitlich', hinweis: 'Halber Betrag, dafür doppelt so lange - besonders sinnvoll bei Teilzeitarbeit.' },
      { position: 'Geschwisterbonus und Mehrlingszuschlag', betrag: '10 Prozent, mindestens 75 Euro, beziehungsweise 300 Euro je weiterem Kind', art: 'bundeseinheitlich' },
    ],
    fristen: [
      'Rückwirkende Zahlung nur für drei Monate vor Antragseingang.',
      'Basiselterngeld: 12 Monatsbeträge, 14 bei Aufteilung auf beide Elternteile oder für Alleinerziehende.',
      'Bezugszeitraum: bis zum 14. Lebensmonat des Kindes für Basiselterngeld; für Geburten ab April 2024 dürfen Eltern nur noch einen Monat gleichzeitig Basiselterngeld beziehen, und zwar innerhalb der ersten zwölf Lebensmonate.',
      'Elternzeit muss dem Arbeitgeber spätestens sieben Wochen vor Beginn schriftlich angezeigt werden - für Zeiten nach dem dritten Geburtstag 13 Wochen vorher.',
    ],
    bearbeitungsdauer: 'Vier bis zehn Wochen. Da Elterngeld erst nach der Geburt beantragt werden kann und die Unterlagen umfangreich sind, überbrücken viele Familien mit Mutterschaftsgeld.',
    ablauf: [
      { nr: 1, titel: 'Variante planen', detail: 'Rechnen Sie Basiselterngeld, ElterngeldPlus und Partnerschaftsbonus durch. Der Elterngeldrechner des Bundesfamilienministeriums hilft. Die Aufteilung ist später nur begrenzt änderbar.', akteur: 'Bürger' },
      { nr: 2, titel: 'Elternzeit beim Arbeitgeber anmelden', detail: 'Schriftlich, mit Bindung an die gewählten Zeiträume für die ersten zwei Jahre.', akteur: 'Bürger' },
      { nr: 3, titel: 'Unterlagen sammeln', detail: 'Zwölf Gehaltsabrechnungen vor dem Geburtsmonat, Geburtsurkunde, Arbeitgeberbescheinigung, Mutterschaftsgeldbescheinigung.', akteur: 'Bürger' },
      { nr: 4, titel: 'Antrag stellen', detail: 'Über ElterngeldDigital oder das Landesportal, sonst schriftlich. Beide Elternteile unterschreiben den Antrag des jeweils anderen mit.', akteur: 'Bürger' },
      { nr: 5, titel: 'Prüfung und Bescheid', detail: 'Die Stelle ermittelt das Bemessungsentgelt, rechnet Mutterschaftsgeld an und setzt die Monatsbeträge fest.', akteur: 'Behörde' },
      { nr: 6, titel: 'Änderungen melden', detail: 'Nehmen Sie eine Teilzeittätigkeit auf oder ändert sich das Einkommen, ist das sofort anzuzeigen - sonst drohen Rückforderungen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 1 ff. Bundeselterngeld- und Elternzeitgesetz - Anspruch und Höhe',
      '§ 4 BEEG - Bezugszeitraum und Aufteilung',
      '§ 4b, 4c BEEG - ElterngeldPlus und Partnerschaftsbonus',
      '§ 15, 16 BEEG - Elternzeit und Anmeldefristen',
    ],
    online: {
      moeglich: true,
      hinweis: 'ElterngeldDigital des Bundes wird von vielen Ländern genutzt; einige haben eigene Portale. Häufig ist der Antrag digital ausfüllbar, muss aber unterschrieben eingereicht werden - mit eID auch das digital.',
    },
    haeufigeFehler: [
      'Erst Monate nach der Geburt beantragen und die Dreimonatsgrenze überschreiten.',
      'Die Geburtsurkunde ohne den Verwendungszweck Elterngeld bestellen und dafür zahlen.',
      'Bei Selbstständigen die Gewinnermittlung des maßgeblichen Zeitraums nicht vorbereiten.',
      'Übersehen, dass Mutterschaftsgeld und Arbeitgeberzuschuss auf das Elterngeld angerechnet werden.',
      'Die parallele Bezugsbeschränkung für Geburten ab April 2024 nicht kennen.',
    ],
    faq: [
      { frage: 'Wie viel bekomme ich?', antwort: 'Basiselterngeld ersetzt in der Regel 65 bis 67 Prozent des wegfallenden Nettoeinkommens, mindestens 300 und höchstens 1.800 Euro im Monat. Bei Einkommen unter 1.000 Euro steigt die Ersatzrate bis auf 100 Prozent.' },
      { frage: 'Kann ich während des Elterngeldbezugs arbeiten?', antwort: 'Ja, bis zu 32 Wochenstunden. Das Einkommen wird angerechnet; ElterngeldPlus ist für diesen Fall die günstigere Variante.' },
      { frage: 'Was ist der Partnerschaftsbonus?', antwort: 'Zusätzliche ElterngeldPlus-Monate, wenn beide Eltern gleichzeitig zwischen 24 und 32 Wochenstunden arbeiten - zwei bis vier Monate je Elternteil.' },
      { frage: 'Gilt die Einkommensgrenze für uns?', antwort: 'Für Geburten ab dem 1. April 2025 entfällt der Anspruch, wenn das zu versteuernde Einkommen 175.000 Euro übersteigt - bei Paaren gemeinsam, bei Alleinerziehenden allein.' },
    ],
    verwandt: ['kindergeld', 'geburtsurkunde', 'kita-platz', 'mutterschutz'],
    eskalation: 'Bei Selbstständigen, Mischeinkünften, Auslandsbezug, Mehrlingsgeburten oder Rückforderungen an die Elterngeldstelle weiterleiten.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Der Anspruch ist Bundesrecht, die Zuständigkeit und die Portale sind Landesrecht. Beträge und Grenzen ändern sich - immer als Stand kennzeichnen.' },
    stand: '2026-08',
  },
  {
    id: 'kita-platz',
    cluster: 'familie-kinder',
    name: 'Kita-Platz oder Kindertagespflege beantragen',
    sprechName: 'Kita-Platz beantragen',
    synonyme: ['kita', 'kindergarten', 'krippe', 'betreuungsplatz', 'kitaplatz', 'tagesmutter', 'kindertagespflege', 'kita anmelden', 'kitagutschein', 'hort'],
    leikaBezug: 'Kindertagesbetreuung - Betreuungsplatz (LeiKa 99075011)',
    kurzbeschreibung: 'Kinder haben ab dem vollendeten ersten Lebensjahr einen Rechtsanspruch auf frühkindliche Förderung in einer Tageseinrichtung oder Kindertagespflege. Die Vergabe organisieren Kommune und Träger, meist über ein zentrales Vormerksystem.',
    zustaendigkeit: {
      stelle: 'Jugendamt beziehungsweise Amt für Kindertagesbetreuung der Kommune, daneben die freien Träger der Einrichtungen',
      ebene: 'kommunal',
      hinweis: 'In Städten mit Gutscheinsystem - etwa Hamburg oder Berlin - stellt die Behörde einen Gutschein aus, mit dem Sie sich selbst eine Einrichtung suchen.',
    },
    voraussetzungen: [
      'Rechtsanspruch ab dem vollendeten ersten Lebensjahr bis zum Schuleintritt (§ 24 SGB VIII).',
      'Für Kinder unter einem Jahr besteht ein Anspruch nur bei besonderem Bedarf, etwa Erwerbstätigkeit, Ausbildung oder Eingliederungsmaßnahme der Eltern.',
      'Wohnsitz in der Gemeinde; auswärtige Kinder werden nachrangig berücksichtigt.',
      'Umfang der Betreuung richtet sich nach dem individuellen Bedarf - Nachweise über Arbeitszeiten sind häufig nötig.',
    ],
    unterlagen: [
      { was: 'Anmeldung im kommunalen Vormerksystem', pflicht: true },
      { was: 'Geburtsurkunde des Kindes', pflicht: true },
      { was: 'Meldebescheinigung oder Personalausweis der Eltern', pflicht: true },
      { was: 'Arbeitgeberbescheinigungen oder Nachweise über Ausbildung und Studium', pflicht: false, hinweis: 'Für den Umfang der Betreuungszeit und bei Vergabekriterien relevant.' },
      { was: 'Einkommensnachweise', pflicht: false, hinweis: 'Für die einkommensabhängige Beitragsberechnung.' },
      { was: 'Nachweis der Masernimpfung', pflicht: true, hinweis: 'Seit dem Masernschutzgesetz Aufnahmevoraussetzung in jeder Einrichtung.' },
    ],
    gebuehren: [
      { position: 'Elternbeitrag', betrag: '0 bis über 500 Euro monatlich', art: 'kommunal', hinweis: 'Extrem unterschiedlich: Einige Länder haben beitragsfreie Kita-Jahre, andere staffeln nach Einkommen, Betreuungsumfang und Geschwisterzahl.' },
      { position: 'Verpflegungsgeld', betrag: 'etwa 40 bis 120 Euro monatlich', art: 'kommunal' },
      { position: 'Beitragsübernahme bei geringem Einkommen', betrag: '0,00 Euro', art: 'einkommensabhaengig', hinweis: 'Nach § 90 SGB VIII kann der Beitrag ganz oder teilweise erlassen werden; das Mittagessen wird über Bildung und Teilhabe übernommen.' },
    ],
    fristen: [
      'Anmeldung in vielen Kommunen sechs bis zwölf Monate vor dem gewünschten Beginn, in Großstädten früher.',
      'Der Bedarf soll dem Jugendamt spätestens drei Monate vor dem gewünschten Betreuungsbeginn angezeigt werden - das ist Voraussetzung, um den Rechtsanspruch später durchzusetzen.',
      'Kündigungsfristen der Einrichtungen meist ein bis drei Monate.',
    ],
    bearbeitungsdauer: 'Die Platzvergabe erfolgt meist in festen Vergaberunden im Frühjahr für das Kita-Jahr ab August. Die Zusage kommt oft erst wenige Monate vor Beginn.',
    ablauf: [
      { nr: 1, titel: 'Bedarf frühzeitig anmelden', detail: 'Melden Sie den Betreuungsbedarf schriftlich beim Jugendamt an, mindestens drei Monate vorher. Diese Bedarfsanzeige ist rechtlich entscheidend.', akteur: 'Bürger' },
      { nr: 2, titel: 'Einrichtungen auswählen', detail: 'Im Vormerksystem mehrere Wunscheinrichtungen angeben und dort persönlich vorstellen - viele Träger vergeben nach eigenen Kriterien.', akteur: 'Bürger' },
      { nr: 3, titel: 'Platzangebot annehmen', detail: 'Nach der Zusage schließen Sie einen Betreuungsvertrag mit dem Träger; in Gutscheinstädten lösen Sie den Gutschein bei der Einrichtung ein.', akteur: 'Bürger' },
      { nr: 4, titel: 'Beitrag festsetzen lassen', detail: 'Einkommensnachweise einreichen; bei geringem Einkommen Erlass nach § 90 SGB VIII beantragen.', akteur: 'Bürger' },
      { nr: 5, titel: 'Eingewöhnung', detail: 'Meist zwei bis sechs Wochen nach dem Berliner oder Münchner Modell; planen Sie das bei der Rückkehr in den Beruf ein.', akteur: 'Bürger' },
      { nr: 6, titel: 'Wenn kein Platz angeboten wird', detail: 'Der Rechtsanspruch ist einklagbar. Rügen Sie schriftlich, setzen Sie eine Frist und lassen Sie sich die Ablehnung bestätigen. Möglich sind Eilantrag beim Verwaltungsgericht und Schadensersatz für Verdienstausfall - das hat der Bundesgerichtshof anerkannt.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 24 Achtes Buch Sozialgesetzbuch - Anspruch auf Förderung in Tageseinrichtungen',
      '§ 22 bis 23 SGB VIII - Grundsätze und Kindertagespflege',
      '§ 90 SGB VIII - Kostenbeiträge und Erlass',
      'Kindertagesstättengesetze der Länder',
      '§ 20 Abs. 8 Infektionsschutzgesetz - Masernnachweis',
    ],
    online: {
      moeglich: true,
      hinweis: 'Fast überall online über kommunale Vormerksysteme wie Kita-Navigator, Little Bird oder eigene Portale. Der Betreuungsvertrag wird meist noch analog geschlossen.',
    },
    haeufigeFehler: [
      'Nur bei den Einrichtungen anfragen und die formale Bedarfsanzeige beim Jugendamt vergessen - dann ist der Rechtsanspruch schwer durchsetzbar.',
      'Zu spät anmelden.',
      'Nur eine Wunscheinrichtung angeben.',
      'Die Beitragsermäßigung nicht beantragen.',
      'Den Masernnachweis erst beim Betreuungsstart besorgen.',
    ],
    faq: [
      { frage: 'Ab wann habe ich Anspruch?', antwort: 'Ab dem ersten Geburtstag des Kindes bis zum Schuleintritt. Für jüngere Kinder nur bei besonderem Bedarf.' },
      { frage: 'Die Stadt bietet mir keinen Platz an - was kann ich tun?', antwort: 'Der Anspruch ist einklagbar. Legen Sie die Bedarfsanzeige vor, fordern Sie schriftlich einen Platz, und beantragen Sie notfalls eine einstweilige Anordnung beim Verwaltungsgericht. Verdienstausfall wegen eines fehlenden Platzes kann als Amtshaftungsanspruch geltend gemacht werden.' },
      { frage: 'Muss die Kita in meiner Nähe sein?', antwort: 'Der Platz muss zumutbar erreichbar sein. Als Faustregel gelten in Städten etwa 30 Minuten Fahrzeit; ein Platz am anderen Ende der Stadt kann unzumutbar sein.' },
      { frage: 'Was kostet die Kita?', antwort: 'Das unterscheidet sich stark: In einigen Ländern sind ein oder mehrere Kita-Jahre beitragsfrei, in anderen zahlen Sie einkommensabhängig bis über 500 Euro. Das Mittagessen wird fast überall extra berechnet.' },
    ],
    verwandt: ['elterngeld', 'bildung-und-teilhabe', 'geburtsurkunde', 'schulanmeldung'],
    eskalation: 'Bei Ablehnung trotz Rechtsanspruch, bei Kindern mit Behinderung und Eingliederungshilfebedarf oder bei Härtefällen an das Jugendamt weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Der Rechtsanspruch ist Bundesrecht, Vergabe und Beiträge sind kommunal höchst unterschiedlich. Beträge nur als Spanne nennen.' },
    stand: '2026-08',
  },
  {
    id: 'vaterschaftsanerkennung',
    cluster: 'familie-kinder',
    name: 'Vaterschaft anerkennen und Sorgeerklärung abgeben',
    sprechName: 'Vaterschaftsanerkennung und Sorgeerklärung',
    synonyme: ['vaterschaft', 'vaterschaftsanerkennung', 'vater anerkennen', 'sorgeerklärung', 'gemeinsames sorgerecht', 'sorgerecht unverheiratet', 'beurkundung jugendamt'],
    leikaBezug: 'Vaterschaftsanerkennung - Beurkundung (LeiKa 99075008)',
    kurzbeschreibung: 'Sind die Eltern nicht miteinander verheiratet, entsteht die rechtliche Vaterschaft erst durch Anerkennung mit Zustimmung der Mutter. Das gemeinsame Sorgerecht entsteht zusätzlich erst durch Sorgeerklärungen beider Eltern.',
    zustaendigkeit: {
      stelle: 'Jugendamt, Standesamt, Amtsgericht oder Notar - alle können beurkunden',
      ebene: 'kommunal',
      hinweis: 'Beim Jugendamt ist die Beurkundung kostenfrei, beim Notar nicht. Örtlich sind Sie nicht gebunden - jedes Jugendamt kann beurkunden.',
    },
    voraussetzungen: [
      'Für die Anerkennung: Zustimmung der Mutter; ist das Kind volljährig, auch dessen Zustimmung.',
      'Es darf kein anderer Mann rechtlicher Vater sein - war die Mutter bei der Geburt verheiratet, gilt zunächst der Ehemann als Vater.',
      'Für die Sorgeerklärung: übereinstimmende Erklärungen beider Elternteile, öffentlich beurkundet.',
      'Anerkennung und Zustimmung können vor oder nach der Geburt erklärt werden.',
    ],
    unterlagen: [
      { was: 'Personalausweise oder Reisepässe beider Eltern', pflicht: true },
      { was: 'Mutterpass oder Geburtsurkunde des Kindes', pflicht: true, hinweis: 'Vor der Geburt der Mutterpass mit errechnetem Termin, danach die Geburtsurkunde.' },
      { was: 'Geburtsurkunden der Eltern', pflicht: false, hinweis: 'Wird von vielen Jugendämtern verlangt.' },
      { was: 'Bei Auslandsbezug: Nachweise über den Personenstand, gegebenenfalls Übersetzungen', pflicht: false },
      { was: 'Dolmetscher', pflicht: false, hinweis: 'Wenn eine beteiligte Person die Beurkundungssprache nicht ausreichend beherrscht - dann ist er zwingend.' },
    ],
    gebuehren: [
      { position: 'Beurkundung beim Jugendamt', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Vaterschaftsanerkennung, Sorgeerklärung, Unterhaltsverpflichtung - alles kostenfrei.' },
      { position: 'Beurkundung beim Notar', betrag: 'etwa 30 bis 90 Euro', art: 'bundeseinheitlich' },
      { position: 'Beurkundung beim Standesamt', betrag: 'etwa 10 bis 30 Euro', art: 'kommunal' },
    ],
    fristen: [
      'Keine Frist. Vor der Geburt möglich und empfehlenswert, damit der Vater von Anfang an eingetragen ist.',
      'Anfechtung der Vaterschaft: zwei Jahre ab Kenntnis der Umstände, die gegen die Vaterschaft sprechen.',
    ],
    bearbeitungsdauer: 'Die Beurkundung dauert etwa 20 bis 40 Minuten und ist sofort wirksam. Die Urkunden erhalten Sie direkt.',
    ablauf: [
      { nr: 1, titel: 'Termin beim Jugendamt vereinbaren', detail: 'Beide Eltern sollten gemeinsam kommen. Getrennte Erklärungen sind möglich, machen aber mehrere Termine nötig.', akteur: 'Bürger' },
      { nr: 2, titel: 'Vaterschaft anerkennen', detail: 'Der Vater erklärt die Anerkennung, die Mutter stimmt zu. Beides wird öffentlich beurkundet.', akteur: 'Bürger' },
      { nr: 3, titel: 'Sorgeerklärungen abgeben', detail: 'Separater Schritt: Nur mit Sorgeerklärungen beider Eltern entsteht das gemeinsame Sorgerecht. Ohne sie hat die Mutter allein die elterliche Sorge.', akteur: 'Bürger' },
      { nr: 4, titel: 'Optional: Unterhalt beurkunden', detail: 'Das Jugendamt beurkundet auch Unterhaltsverpflichtungen - ein vollstreckbarer Titel, der spätere Streitigkeiten erspart.', akteur: 'Bürger' },
      { nr: 5, titel: 'Urkunden weiterleiten', detail: 'Das Standesamt trägt die Vaterschaft im Geburtenregister ein. Bewahren Sie Kopien für Elterngeld, Krankenkasse und Kindergeld auf.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 1592 ff. Bürgerliches Gesetzbuch - Vaterschaft',
      '§ 1595, 1597 BGB - Zustimmung und Form der Anerkennung',
      '§ 1626a BGB - Elterliche Sorge nicht miteinander verheirateter Eltern',
      '§ 59 Achtes Buch Sozialgesetzbuch - Beurkundung durch das Jugendamt',
    ],
    online: { moeglich: false, hinweis: 'Die Beurkundung erfordert persönliche Anwesenheit; Terminvereinbarung ist online möglich.' },
    haeufigeFehler: [
      'Annehmen, mit der Vaterschaftsanerkennung sei auch das Sorgerecht geregelt - das sind zwei getrennte Erklärungen.',
      'Beim Notar beurkunden lassen und dafür zahlen, obwohl das Jugendamt es kostenfrei tut.',
      'Bei bestehender Ehe der Mutter mit einem anderen Mann direkt anerkennen wollen - dann ist zuerst die bestehende Vaterschaft anzufechten.',
      'Die Anerkennung erst Monate nach der Geburt angehen und dadurch Elterngeld und Krankenversicherung verzögern.',
    ],
    faq: [
      { frage: 'Bekomme ich mit der Anerkennung automatisch das Sorgerecht?', antwort: 'Nein. Ohne Sorgeerklärung liegt die elterliche Sorge allein bei der Mutter. Verweigert sie die Erklärung, kann der Vater beim Familiengericht die gemeinsame Sorge beantragen.' },
      { frage: 'Was kostet das beim Jugendamt?', antwort: 'Nichts. Beurkundungen von Vaterschaft, Sorgeerklärung und Unterhalt sind dort gebührenfrei.' },
      { frage: 'Können wir das schon vor der Geburt machen?', antwort: 'Ja, und das ist meist sinnvoll. Bringen Sie den Mutterpass mit.' },
      { frage: 'Die Mutter war bei der Geburt verheiratet, aber vom Ehemann getrennt.', antwort: 'Dann gilt zunächst der Ehemann als Vater. Der biologische Vater kann anerkennen, wenn der Ehemann und die Mutter zustimmen und ein Scheidungsverfahren anhängig ist, sonst ist die Vaterschaft gerichtlich anzufechten.' },
    ],
    verwandt: ['geburtsurkunde', 'unterhaltsvorschuss', 'kindergeld'],
    eskalation: 'Bei Auslandsbezug, bestehender Ehe der Mutter, Anfechtungsfragen oder Sorgerechtsstreit an das Jugendamt oder Familiengericht weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht; kostenfrei beim Jugendamt in ganz Deutschland.' },
    stand: '2026-08',
  },
  {
    id: 'unterhaltsvorschuss',
    cluster: 'familie-kinder',
    name: 'Unterhaltsvorschuss beantragen',
    sprechName: 'Unterhaltsvorschuss beantragen',
    synonyme: ['unterhaltsvorschuss', 'unterhalt vorschuss', 'kein unterhalt', 'alleinerziehend unterhalt', 'uvg', 'unterhaltsvorschusskasse'],
    leikaBezug: 'Unterhaltsvorschuss - Beantragung (LeiKa 99075006)',
    kurzbeschreibung: 'Alleinerziehende erhalten Unterhaltsvorschuss, wenn der andere Elternteil keinen oder zu wenig Unterhalt zahlt. Die Leistung springt für den ausfallenden Barunterhalt ein; der Staat holt sich das Geld beim Unterhaltspflichtigen zurück.',
    zustaendigkeit: {
      stelle: 'Unterhaltsvorschusskasse beim Jugendamt der Kommune',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Das Kind lebt bei einem alleinerziehenden Elternteil und ist unter 18 Jahre alt.',
      'Der andere Elternteil zahlt keinen, unregelmäßigen oder zu geringen Unterhalt.',
      'Das Kind lebt in Deutschland; der alleinerziehende Elternteil ist nicht verheiratet oder lebt dauernd getrennt.',
      'Für Kinder ab 12 Jahren zusätzlich: Der alleinerziehende Elternteil bezieht kein Bürgergeld oder hat ein Bruttoeinkommen von mindestens 600 Euro monatlich, oder das Kind wird durch die Leistung nicht hilfebedürftig.',
      'Mitwirkungspflicht: Angaben zum anderen Elternteil sind zu machen, soweit möglich.',
    ],
    unterlagen: [
      { was: 'Antragsformular der Unterhaltsvorschusskasse', pflicht: true },
      { was: 'Geburtsurkunde des Kindes', pflicht: true },
      { was: 'Personalausweis des antragstellenden Elternteils', pflicht: true },
      { was: 'Meldebescheinigung des Kindes', pflicht: true },
      { was: 'Angaben zum anderen Elternteil: Name, Anschrift, Arbeitgeber', pflicht: true, hinweis: 'Fehlen sie vollständig ohne nachvollziehbaren Grund, kann die Leistung versagt werden.' },
      { was: 'Nachweise über gezahlten Unterhalt oder dessen Ausbleiben', pflicht: false },
      { was: 'Bei Kindern ab 12: Einkommensnachweise oder Bürgergeldbescheid', pflicht: false },
    ],
    gebuehren: [
      { position: 'Antrag', betrag: '0,00 Euro', art: 'keine' },
      { position: 'Unterhaltsvorschuss Kinder 0 bis 5 Jahre', betrag: 'Mindestunterhalt der ersten Altersstufe abzüglich des vollen Kindergeldes', art: 'bundeseinheitlich', hinweis: 'Die Beträge werden jährlich zum 1. Januar mit der Mindestunterhaltsverordnung angepasst; erfragen Sie den aktuellen Wert.' },
      { position: 'Unterhaltsvorschuss Kinder 6 bis 11 Jahre', betrag: 'Mindestunterhalt der zweiten Altersstufe abzüglich Kindergeld', art: 'bundeseinheitlich' },
      { position: 'Unterhaltsvorschuss Kinder 12 bis 17 Jahre', betrag: 'Mindestunterhalt der dritten Altersstufe abzüglich Kindergeld', art: 'bundeseinheitlich' },
    ],
    fristen: [
      'Rückwirkende Zahlung höchstens für den Monat vor der Antragstellung, und nur wenn der Unterhalt schon damals ausblieb.',
      'Änderungen - Unterhaltszahlungen, Zusammenziehen mit einem Partner, Umzug - sind unverzüglich anzuzeigen.',
    ],
    bearbeitungsdauer: 'Vier bis zwölf Wochen. Die Leistung wird ab dem Antragsmonat gezahlt, Nachzahlungen sind üblich.',
    ablauf: [
      { nr: 1, titel: 'Antrag stellen, auch bei unklarer Lage', detail: 'Stellen Sie den Antrag sofort - Rückwirkung gibt es fast keine. Unterlagen können nachgereicht werden.', akteur: 'Bürger' },
      { nr: 2, titel: 'Angaben zum anderen Elternteil machen', detail: 'Je genauer, desto schneller. Ist der Aufenthalt unbekannt, schildern Sie Ihre Bemühungen - eine bloße Weigerung, Angaben zu machen, führt zur Ablehnung.', akteur: 'Bürger' },
      { nr: 3, titel: 'Prüfung durch die Unterhaltsvorschusskasse', detail: 'Sie prüft Anspruch, Alter und bei Kindern ab 12 die zusätzlichen Voraussetzungen.', akteur: 'Behörde' },
      { nr: 4, titel: 'Bewilligung und Zahlung', detail: 'Monatliche Zahlung im Voraus.', akteur: 'Behörde' },
      { nr: 5, titel: 'Rückgriff beim Unterhaltspflichtigen', detail: 'Der Anspruch geht auf das Land über. Die Kasse fordert das Geld beim anderen Elternteil ein - das entlastet Sie von der eigenen Durchsetzung.', akteur: 'Behörde' },
      { nr: 6, titel: 'Beistandschaft erwägen', detail: 'Parallel können Sie beim Jugendamt eine kostenfreie Beistandschaft beantragen, die Vaterschaft feststellt und Unterhaltsansprüche durchsetzt.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 1 Unterhaltsvorschussgesetz - Anspruchsberechtigte',
      '§ 1 Abs. 1a UhVorschG - Zusätzliche Voraussetzungen ab 12 Jahren',
      '§ 2 UhVorschG - Höhe der Leistung',
      '§ 7 UhVorschG - Übergang des Unterhaltsanspruchs',
      'Mindestunterhaltsverordnung',
    ],
    online: { moeglich: true, hinweis: 'In vielen Kommunen als Online-Antrag mit Upload der Nachweise verfügbar.' },
    haeufigeFehler: [
      'Zu spät beantragen - es gibt praktisch keine Rückwirkung.',
      'Angaben zum anderen Elternteil verweigern.',
      'Nicht melden, wenn doch Unterhalt gezahlt wird - das führt zu Rückforderungen.',
      'Unterhaltsvorschuss und Unterhaltstitel verwechseln: Der Vorschuss ersetzt keinen Titel, die Beistandschaft hilft dabei.',
    ],
    faq: [
      { frage: 'Wie hoch ist der Vorschuss?', antwort: 'Er entspricht dem Mindestunterhalt der jeweiligen Altersstufe abzüglich des vollen Kindergeldes. Die Beträge steigen jährlich - erfragen Sie den aktuellen Wert bei der Unterhaltsvorschusskasse.' },
      { frage: 'Muss ich den Vorschuss zurückzahlen?', antwort: 'Nein, solange Ihre Angaben stimmen. Der Staat holt das Geld beim unterhaltspflichtigen Elternteil.' },
      { frage: 'Der andere Elternteil zahlt etwas, aber zu wenig.', antwort: 'Dann gibt es die Differenz bis zur Höhe des Vorschusses.' },
      { frage: 'Ich bin wieder in einer Partnerschaft.', antwort: 'Entscheidend ist, ob Sie mit dem anderen Elternteil zusammenleben oder erneut heiraten. Eine neue Partnerschaft ohne Heirat steht dem Anspruch grundsätzlich nicht entgegen, ist aber anzugeben.' },
    ],
    verwandt: ['kindergeld', 'vaterschaftsanerkennung', 'buergergeld'],
    eskalation: 'Bei unbekanntem Aufenthalt des anderen Elternteils, Auslandsbezug oder Rückforderungen an das Jugendamt weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht; die Beträge ändern sich jährlich zum 1. Januar.' },
    stand: '2026-08',
  },
  {
    id: 'bildung-und-teilhabe',
    cluster: 'familie-kinder',
    name: 'Leistungen für Bildung und Teilhabe beantragen',
    sprechName: 'Bildung und Teilhabe',
    synonyme: ['bildung und teilhabe', 'but', 'bildungspaket', 'schulbedarf', 'klassenfahrt zuschuss', 'mittagessen zuschuss', 'nachhilfe zuschuss', 'vereinsbeitrag zuschuss', 'teilhabepaket'],
    leikaBezug: 'Bildung und Teilhabe - Leistungen (LeiKa 99075014)',
    kurzbeschreibung: 'Kinder aus Familien mit geringem Einkommen erhalten Zuschüsse für Schulbedarf, Klassenfahrten, Mittagessen, Schülerbeförderung, Lernförderung und Mitgliedsbeiträge in Vereinen.',
    zustaendigkeit: {
      stelle: 'Jobcenter bei Bürgergeldbezug, sonst Sozialamt oder eigenes Bildungs- und Teilhabe-Team der Kommune',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Bezug von Bürgergeld, Sozialhilfe, Wohngeld, Kinderzuschlag oder Leistungen nach dem Asylbewerberleistungsgesetz.',
      'Das Kind besucht eine Schule oder Kita beziehungsweise ist unter 25 und noch nicht erwerbstätig.',
      'Für Lernförderung: die Versetzung oder das Lernziel ist gefährdet - Bestätigung der Schule nötig.',
    ],
    unterlagen: [
      { was: 'Antragsformular, meist je Leistungsart', pflicht: true },
      { was: 'Aktueller Leistungsbescheid über Bürgergeld, Wohngeld oder Kinderzuschlag', pflicht: true },
      { was: 'Schul- oder Kitabescheinigung', pflicht: true },
      { was: 'Bei Klassenfahrten: Bestätigung der Schule mit Kosten und Zeitraum', pflicht: false },
      { was: 'Bei Lernförderung: Stellungnahme der Schule', pflicht: false },
      { was: 'Bei Vereinsbeiträgen: Nachweis des Vereins', pflicht: false },
    ],
    gebuehren: [
      { position: 'Schulbedarf', betrag: 'Pauschale je Schuljahr, aufgeteilt auf zwei Termine', art: 'bundeseinheitlich', hinweis: 'Der Betrag wird jährlich angepasst; er wird bei Bürgergeldbezug meist automatisch ausgezahlt.' },
      { position: 'Mittagsverpflegung', betrag: 'Übernahme der Mehrkosten', art: 'bundeseinheitlich', hinweis: 'Seit 2019 ohne Eigenanteil.' },
      { position: 'Schülerbeförderung', betrag: 'Übernahme der tatsächlichen Kosten', art: 'bundeseinheitlich' },
      { position: 'Teilhabe an Kultur, Sport und Freizeit', betrag: '15 Euro monatlich', art: 'bundeseinheitlich' },
      { position: 'Klassenfahrten und Ausflüge', betrag: 'tatsächliche Kosten', art: 'bundeseinheitlich' },
      { position: 'Lernförderung', betrag: 'angemessene Kosten', art: 'bundeseinheitlich' },
    ],
    fristen: [
      'Anträge sollen vor der Kostenentstehung gestellt werden - nachträgliche Übernahme ist häufig ausgeschlossen.',
      'Bewilligung meist für den Bewilligungszeitraum der Hauptleistung.',
    ],
    bearbeitungsdauer: 'Zwei bis sechs Wochen. Bei Bürgergeldbezug werden Schulbedarf und Mittagessen häufig automatisch mitbewilligt.',
    ablauf: [
      { nr: 1, titel: 'Leistungsart bestimmen', detail: 'Schulbedarf, Mittagessen, Beförderung, Ausflüge und Klassenfahrten, Lernförderung, Teilhabe an Kultur und Sport.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag vor der Ausgabe stellen', detail: 'Wichtig: erst beantragen, dann buchen oder zahlen.', akteur: 'Bürger' },
      { nr: 3, titel: 'Nachweise beibringen', detail: 'Schulbestätigungen, Vereinsnachweise, Kostenaufstellungen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Bewilligung', detail: 'Die Zahlung geht häufig direkt an Schule, Verein oder Anbieter, nicht an die Familie.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 28 Zweites Buch Sozialgesetzbuch - Bedarfe für Bildung und Teilhabe',
      '§ 34 Zwölftes Buch Sozialgesetzbuch',
      '§ 6b Bundeskindergeldgesetz für Wohngeld- und Kinderzuschlagsempfänger',
      '§ 3 Asylbewerberleistungsgesetz',
    ],
    online: { moeglich: true, hinweis: 'In vielen Kommunen über das Jobcenter- oder Sozialamtsportal; teils mit digitaler Bildungskarte.' },
    haeufigeFehler: [
      'Erst nach der Klassenfahrt beantragen.',
      'Nicht wissen, dass auch Wohngeld- und Kinderzuschlagsempfänger anspruchsberechtigt sind.',
      'Die Lernförderung ohne Schulstellungnahme beantragen.',
      'Den Teilhabebetrag von 15 Euro monatlich ungenutzt lassen.',
    ],
    faq: [
      { frage: 'Wir bekommen Wohngeld - haben wir Anspruch?', antwort: 'Ja. Bildung und Teilhabe steht auch Familien mit Wohngeld oder Kinderzuschlag zu, beantragt wird es dann bei der Kommune.' },
      { frage: 'Wird das Geld an mich ausgezahlt?', antwort: 'Meist nicht. Die Kommune zahlt direkt an Schule, Verein oder Caterer. Nur der Schulbedarf wird in der Regel ausgezahlt.' },
      { frage: 'Bekommen wir Nachhilfe bezahlt?', antwort: 'Ja, als Lernförderung, wenn die Schule bestätigt, dass das Lernziel gefährdet ist. Eine Versetzungsgefährdung ist seit 2019 nicht mehr zwingend.' },
    ],
    verwandt: ['buergergeld', 'wohngeld', 'kita-platz', 'schulanmeldung'],
    eskalation: 'Bei abgelehnter Lernförderung oder strittigem Bedarf an das zuständige Jobcenter oder Sozialamt weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrechtlicher Anspruch, kommunale Umsetzung sehr unterschiedlich - manche Städte nutzen Gutscheine oder Bildungskarten.' },
    stand: '2026-08',
  },
  {
    id: 'mutterschutz',
    cluster: 'familie-kinder',
    name: 'Mutterschutz und Mutterschaftsgeld',
    sprechName: 'Mutterschutz und Mutterschaftsgeld',
    synonyme: ['mutterschutz', 'mutterschaftsgeld', 'schwanger arbeit', 'beschäftigungsverbot', 'schwangerschaft melden', 'mutterschutzfrist', 'arbeitgeberzuschuss mutterschaft'],
    leikaBezug: 'Mutterschaftsgeld und Mutterschutz (LeiKa 99075010)',
    kurzbeschreibung: 'Der Mutterschutz schützt schwangere und stillende Beschäftigte. Sechs Wochen vor und acht Wochen nach der Geburt gilt Beschäftigungsverbot; in dieser Zeit zahlen Krankenkasse und Arbeitgeber Mutterschaftsgeld und Zuschuss.',
    zustaendigkeit: {
      stelle: 'Krankenkasse für das Mutterschaftsgeld, Arbeitgeber für den Zuschuss, Gewerbeaufsicht beziehungsweise Amt für Arbeitsschutz für Aufsicht und Beschäftigungsverbote',
      ebene: 'sonstige',
      hinweis: 'Nicht gesetzlich versicherte Frauen erhalten Mutterschaftsgeld vom Bundesamt für Soziale Sicherung, begrenzt auf einmalig 210 Euro.',
    },
    voraussetzungen: [
      'Bestehendes Beschäftigungsverhältnis - auch Minijob, Ausbildung und in Teilen Schülerinnen und Studentinnen.',
      'Mitgliedschaft in einer gesetzlichen Krankenkasse mit Anspruch auf Krankengeld für das volle Mutterschaftsgeld.',
      'Vorlage der ärztlichen Bescheinigung über den mutmaßlichen Entbindungstermin, ausgestellt frühestens sieben Wochen vor dem Termin.',
    ],
    unterlagen: [
      { was: 'Ärztliche Bescheinigung über den voraussichtlichen Entbindungstermin', pflicht: true },
      { was: 'Antrag auf Mutterschaftsgeld bei der Krankenkasse', pflicht: true },
      { was: 'Mitteilung der Schwangerschaft an den Arbeitgeber', pflicht: false, hinweis: 'Rechtlich freiwillig, praktisch Voraussetzung für den Schutz - erst mit Kenntnis greifen die Schutzvorschriften.' },
      { was: 'Geburtsurkunde nach der Entbindung', pflicht: true, hinweis: 'Für die zweite Hälfte der Zahlung.' },
    ],
    gebuehren: [
      { position: 'Mutterschaftsgeld der gesetzlichen Krankenkasse', betrag: 'bis 13 Euro kalendertäglich', art: 'bundeseinheitlich' },
      { position: 'Arbeitgeberzuschuss', betrag: 'Differenz zum bisherigen Nettoentgelt', art: 'bundeseinheitlich', hinweis: 'So bleibt das Nettoeinkommen in der Schutzfrist praktisch erhalten.' },
      { position: 'Mutterschaftsgeld für privat oder nicht Versicherte', betrag: 'einmalig bis 210 Euro', art: 'bundeseinheitlich', hinweis: 'Beim Bundesamt für Soziale Sicherung zu beantragen.' },
    ],
    fristen: [
      'Schutzfrist: 6 Wochen vor der Entbindung, 8 Wochen danach, bei Früh- und Mehrlingsgeburten sowie bei Behinderung des Kindes 12 Wochen danach.',
      'Bescheinigung über den Entbindungstermin: frühestens sieben Wochen vor dem Termin ausstellbar.',
      'Antrag auf Mutterschaftsgeld: möglichst sieben Wochen vor der Entbindung bei der Krankenkasse.',
      'Kündigungsschutz: ab Beginn der Schwangerschaft bis vier Monate nach der Entbindung, bei Fehlgeburt nach der zwölften Woche ebenfalls vier Monate.',
    ],
    bearbeitungsdauer: 'Die Krankenkasse zahlt in der Regel binnen ein bis zwei Wochen nach Antragseingang.',
    ablauf: [
      { nr: 1, titel: 'Schwangerschaft mitteilen', detail: 'Sobald Sie den Schutz nutzen wollen: dem Arbeitgeber mitteilen, mit voraussichtlichem Entbindungstermin. Erst dann greifen Beschäftigungsverbote und Kündigungsschutz.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bescheinigung beim Arzt holen', detail: 'Sieben Wochen vor dem Termin. Die Kosten trägt die Krankenkasse.', akteur: 'Bürger' },
      { nr: 3, titel: 'Mutterschaftsgeld beantragen', detail: 'Bei der Krankenkasse, mit der Bescheinigung. Der Arbeitgeber erhält eine Kopie für den Zuschuss.', akteur: 'Bürger' },
      { nr: 4, titel: 'Schutzfristen einhalten', detail: 'Sechs Wochen vor der Geburt dürfen Sie nur auf ausdrücklichen eigenen Wunsch arbeiten, nach der Geburt gilt ein absolutes Beschäftigungsverbot.', akteur: 'Bürger' },
      { nr: 5, titel: 'Nach der Geburt', detail: 'Geburtsurkunde an die Krankenkasse; anschließend Elterngeld und Elternzeit anschließen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 3 Mutterschutzgesetz - Schutzfristen',
      '§ 17 Mutterschutzgesetz - Kündigungsverbot',
      '§ 19 ff. Mutterschutzgesetz - Mutterschaftsgeld und Zuschuss',
      '§ 24i Fünftes Buch Sozialgesetzbuch - Mutterschaftsgeld',
    ],
    online: { moeglich: true, hinweis: 'Antrag bei den meisten Krankenkassen online oder per App möglich.' },
    haeufigeFehler: [
      'Die Bescheinigung zu früh ausstellen lassen - sie gilt erst ab sieben Wochen vor dem Termin.',
      'Annehmen, Mutterschaftsgeld und Elterngeld ließen sich addieren - Mutterschaftsleistungen werden auf das Elterngeld angerechnet.',
      'Den Kündigungsschutz nicht kennen und eine Kündigung hinnehmen.',
      'Als Selbstständige keinen Krankentagegeldtarif haben und ohne Absicherung dastehen.',
    ],
    faq: [
      { frage: 'Muss ich meinem Arbeitgeber die Schwangerschaft melden?', antwort: 'Rechtlich müssen Sie nicht. Praktisch greifen Schutzvorschriften und Kündigungsschutz aber erst, wenn er Bescheid weiß - deshalb ist die Mitteilung dringend zu empfehlen.' },
      { frage: 'Wie viel Geld bekomme ich?', antwort: 'Praktisch Ihr bisheriges Nettoentgelt: bis zu 13 Euro kalendertäglich von der Krankenkasse, den Rest als Arbeitgeberzuschuss.' },
      { frage: 'Was ist ein Beschäftigungsverbot?', antwort: 'Ein individuelles ärztliches Verbot bei Gefährdung, unabhängig von den Schutzfristen. Dann zahlt der Arbeitgeber den Mutterschutzlohn in voller Höhe weiter.' },
    ],
    verwandt: ['elterngeld', 'geburtsurkunde', 'kindergeld'],
    eskalation: 'Bei Kündigung während der Schwangerschaft, bei Streit über Beschäftigungsverbote oder bei Selbstständigen an das Amt für Arbeitsschutz beziehungsweise die Krankenkasse weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht; die Aufsicht liegt bei Landesbehörden mit unterschiedlichen Namen.' },
    stand: '2026-08',
  },
];
