/** Stufe 2: Leistungen des Clusters "Kraftfahrzeug und Verkehr". */
export const LEISTUNGEN = [
  {
    id: 'kfz-zulassung',
    cluster: 'kfz-verkehr',
    name: 'Fahrzeug zulassen',
    sprechName: 'Fahrzeug zulassen',
    synonyme: ['auto anmelden', 'fahrzeug zulassen', 'zulassung', 'neuwagen anmelden', 'gebrauchtwagen anmelden', 'kennzeichen beantragen', 'erstzulassung', 'wiederzulassung', 'motorrad anmelden', 'auto zulassen'],
    leikaBezug: 'Fahrzeugzulassung - Erstzulassung und Wiederzulassung (LeiKa 99045002)',
    kurzbeschreibung: 'Ein Fahrzeug darf auf öffentlichen Straßen nur mit gültiger Zulassung und amtlichem Kennzeichen betrieben werden. Die Zulassung erfolgt bei der Zulassungsbehörde des Halterwohnsitzes oder online über das i-Kfz-Portal.',
    zustaendigkeit: {
      stelle: 'Kfz-Zulassungsbehörde des Landkreises oder der kreisfreien Stadt am Wohnsitz des Halters',
      ebene: 'kommunal',
      hinweis: 'Maßgeblich ist der Wohnsitz beziehungsweise Sitz des Halters, nicht der Standort des Fahrzeugs oder des Händlers.',
    },
    voraussetzungen: [
      'Nachgewiesene Verfügungsberechtigung über das Fahrzeug - in der Regel durch die Zulassungsbescheinigung Teil II.',
      'Gültige Hauptuntersuchung; bei Neufahrzeugen genügt die Übereinstimmungsbescheinigung.',
      'Bestehender Versicherungsschutz, nachgewiesen durch die elektronische Versicherungsbestätigung, kurz eVB-Nummer.',
      'Erteilung eines SEPA-Lastschriftmandats für die Kraftfahrzeugsteuer - ohne Mandat wird nicht zugelassen.',
      'Keine offenen Kfz-Steuerrückstände des Halters.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass mit Meldebescheinigung', pflicht: true },
      { was: 'Zulassungsbescheinigung Teil II, früher Fahrzeugbrief', pflicht: true },
      { was: 'Zulassungsbescheinigung Teil I, früher Fahrzeugschein', pflicht: false, hinweis: 'Bei Gebrauchtfahrzeugen vorhanden, bei Neufahrzeugen entfällt sie.' },
      { was: 'eVB-Nummer der Kfz-Versicherung', pflicht: true, hinweis: 'Siebenstellig, meist telefonisch oder online in Minuten erhältlich, in der Regel drei bis sechs Monate gültig.' },
      { was: 'Nachweis der letzten Hauptuntersuchung', pflicht: true, hinweis: 'Bei Neufahrzeugen die EG-Übereinstimmungsbescheinigung, kurz CoC-Papier.' },
      { was: 'SEPA-Lastschriftmandat für die Kfz-Steuer', pflicht: true },
      { was: 'Kennzeichenschilder oder Reservierungsnummer für ein Wunschkennzeichen', pflicht: false },
      { was: 'Bei Firmen: Handelsregisterauszug und Gewerbeanmeldung', pflicht: false },
      { was: 'Vollmacht, Ausweiskopie des Halters und gegebenenfalls SEPA-Mandat bei Vertretung', pflicht: false },
    ],
    gebuehren: [
      { position: 'Erstzulassung mit neuem Kennzeichen', betrag: 'etwa 30 bis 40 Euro', art: 'bundeseinheitlich', hinweis: 'Gebührenrahmen der Gebührenordnung für Maßnahmen im Straßenverkehr; die Behörde bestimmt die genaue Höhe.' },
      { position: 'Wiederzulassung', betrag: 'etwa 25 bis 40 Euro', art: 'bundeseinheitlich' },
      { position: 'Kennzeichenschilder', betrag: 'etwa 20 bis 35 Euro je Paar', art: 'sonstige', hinweis: 'Privatanbieter am Amt, nicht die Behörde.' },
      { position: 'Wunschkennzeichen-Reservierung', betrag: 'etwa 10 bis 13 Euro', art: 'bundeseinheitlich' },
      { position: 'Feinstaubplakette', betrag: 'etwa 5 bis 20 Euro', art: 'sonstige' },
      { position: 'Kfz-Steuer', betrag: 'jährlich, abhängig von Hubraum, CO2-Ausstoß und Antriebsart', art: 'bundeseinheitlich', hinweis: 'Erhoben vom Zoll, nicht von der Zulassungsstelle. Reine Elektrofahrzeuge sind bei Erstzulassung bis Ende 2025 zehn Jahre lang befreit, längstens bis 2030.' },
    ],
    fristen: [
      'Vor der ersten Fahrt - ohne Zulassung darf das Fahrzeug nicht bewegt werden.',
      'Nach dem Kauf eines Gebrauchtwagens: unverzüglich umschreiben, damit die Halterhaftung übergeht.',
      'Hauptuntersuchung: bei Erstzulassung nach 36 Monaten, danach alle 24 Monate.',
    ],
    bearbeitungsdauer: 'Vor Ort in der Regel 20 bis 60 Minuten, Kennzeichen sofort. Bei der Online-Zulassung über i-Kfz wird der Bescheid meist binnen weniger Stunden bis Werktage bereitgestellt; die Papiere kommen per Post, die vorläufige Zulassungsbescheinigung ist sofort als PDF verfügbar.',
    ablauf: [
      { nr: 1, titel: 'Versicherung abschließen und eVB-Nummer holen', detail: 'Erst der Versicherungsvertrag, dann die Zulassung. Die eVB-Nummer erhalten Sie in wenigen Minuten telefonisch, per App oder online.', akteur: 'Bürger' },
      { nr: 2, titel: 'Wunschkennzeichen reservieren', detail: 'Optional über das Portal Ihrer Zulassungsstelle. Die Reservierung gilt meist 90 Tage.', akteur: 'Bürger' },
      { nr: 3, titel: 'Unterlagen zusammenstellen', detail: 'Zulassungsbescheinigung Teil II, HU-Nachweis, Ausweis, SEPA-Mandat. Bei Fahrzeugkauf zusätzlich Kaufvertrag.', akteur: 'Bürger' },
      { nr: 4, titel: 'Zulassung beantragen', detail: 'Entweder im Termin bei der Zulassungsstelle oder online über i-Kfz. Online geht nur, wenn die Papiere die verdeckten Sicherheitscodes tragen - das ist bei Fahrzeugen ab etwa 2015 der Fall.', akteur: 'Bürger' },
      { nr: 5, titel: 'Kennzeichen prägen und stempeln lassen', detail: 'Die Schilder werden bei einem Prägedienst hergestellt und in der Zulassungsstelle mit der Zulassungsplakette und dem Siegel versehen. Bei i-Kfz erhalten Sie Plaketten mit verdecktem Sicherheitscode per Post.', akteur: 'Bürger' },
      { nr: 6, titel: 'Papiere erhalten', detail: 'Zulassungsbescheinigung Teil I bleibt im Fahrzeug, Teil II gehört in den Aktenordner - nie ins Auto legen.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 3 ff. Fahrzeug-Zulassungsverordnung - Zulassungspflicht und Verfahren',
      '§ 15 ff. Fahrzeug-Zulassungsverordnung - Internetbasierte Fahrzeugzulassung',
      'Straßenverkehrs-Zulassungs-Ordnung (StVZO)',
      'Kraftfahrzeugsteuergesetz (KraftStG)',
      'Gebührenordnung für Maßnahmen im Straßenverkehr (GebOSt)',
    ],
    online: {
      moeglich: true,
      hinweis: 'Über i-Kfz in der vierten Ausbaustufe sind Erstzulassung, Wiederzulassung, Umschreibung, Halterwechsel, Adressänderung und Außerbetriebsetzung online möglich - für Privatpersonen, Firmen und Händler. Voraussetzung sind die verdeckten Sicherheitscodes auf Zulassungsbescheinigung und Plaketten.',
      voraussetzungen: ['Online-Ausweisfunktion oder ELSTER-Zertifikat', 'BundID- oder Nutzerkonto', 'Sicherheitscodes auf den Fahrzeugpapieren', 'Zahlungsmittel für die Online-Gebühr'],
    },
    haeufigeFehler: [
      'Ohne eVB-Nummer zur Zulassungsstelle fahren.',
      'Die Zulassungsbescheinigung Teil II im Handschuhfach aufbewahren - bei Diebstahl ein erhebliches Risiko.',
      'Das SEPA-Mandat nicht ausgefüllt mitbringen, wenn der Kontoinhaber nicht der Halter ist - dann ist dessen Unterschrift nötig.',
      'Bei i-Kfz die Sicherheitscodes vorher freirubbeln - sie werden erst im Verfahren aufgedeckt und sind danach verbraucht.',
      'Annehmen, die Zulassung sei mit dem Kauf erledigt.',
    ],
    faq: [
      { frage: 'Kann ich ein Fahrzeug auf jemand anderen zulassen?', antwort: 'Ja, mit Vollmacht, Ausweiskopie des Halters und dessen SEPA-Mandat. Halter ist, wer das Fahrzeug für eigene Rechnung nutzt und darüber verfügt.' },
      { frage: 'Kann ich ein Kennzeichen aus einem anderen Kreis behalten?', antwort: 'Ja. Seit der Kennzeichenliberalisierung dürfen Sie bei Umzug innerhalb Deutschlands das bisherige Kennzeichen behalten, solange das Fahrzeug nicht den Halter wechselt.' },
      { frage: 'Was ist ein Kurzzeitkennzeichen?', antwort: 'Ein für längstens fünf Tage gültiges Kennzeichen für Probe- und Überführungsfahrten, gebunden an ein bestimmtes Fahrzeug mit gültiger Hauptuntersuchung. Kosten etwa 13 Euro Gebühr plus Schilder und eigene Versicherung.' },
      { frage: 'Was kostet die Zulassung insgesamt?', antwort: 'Rechnen Sie mit 60 bis 100 Euro: Verwaltungsgebühr, Schilder, gegebenenfalls Wunschkennzeichen und Plakette. Die Kfz-Steuer kommt jährlich separat vom Zoll.' },
    ],
    verwandt: ['kfz-ummeldung', 'kfz-abmeldung', 'wunschkennzeichen', 'wohnsitz-anmeldung'],
    eskalation: 'Bei fehlenden Fahrzeugpapieren, importierten Fahrzeugen mit Einzelabnahme, Oldtimern mit H-Kennzeichen oder Steuerrückständen an die Zulassungsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Verfahren bundeseinheitlich, Gebührenhöhe innerhalb der GebOSt-Rahmen leicht unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'kfz-ummeldung',
    cluster: 'kfz-verkehr',
    name: 'Fahrzeug ummelden oder umschreiben',
    sprechName: 'Fahrzeug ummelden',
    synonyme: ['auto ummelden', 'fahrzeug ummelden', 'umschreiben', 'halterwechsel', 'auto gekauft', 'auto verkauft', 'adresse ändern fahrzeug', 'kennzeichen mitnehmen', 'umzug auto'],
    leikaBezug: 'Fahrzeugzulassung - Umschreibung (LeiKa 99045002)',
    kurzbeschreibung: 'Eine Umschreibung ist nötig bei Halterwechsel und bei Umzug in einen anderen Zulassungsbezirk. Bei einem Umzug innerhalb Deutschlands darf das bisherige Kennzeichen behalten werden; die Adresse muss dennoch geändert werden.',
    zustaendigkeit: {
      stelle: 'Zulassungsbehörde am neuen Wohnsitz des Halters',
      ebene: 'kommunal',
      hinweis: 'Ist der Zulassungsbezirk gleich geblieben, genügt die Adressänderung in der Zulassungsbescheinigung Teil I.',
    },
    voraussetzungen: [
      'Wohnsitzanmeldung am neuen Wohnort ist bereits erfolgt.',
      'Bei Halterwechsel: Verfügungsberechtigung, gültige Hauptuntersuchung und eigene eVB-Nummer des Käufers.',
      'Keine offenen Kfz-Steuerrückstände.',
    ],
    unterlagen: [
      { was: 'Personalausweis mit aktueller Adresse oder Meldebescheinigung', pflicht: true },
      { was: 'Zulassungsbescheinigung Teil I und Teil II', pflicht: true },
      { was: 'Bei Halterwechsel: eVB-Nummer des neuen Halters und SEPA-Mandat', pflicht: false },
      { was: 'Nachweis der gültigen Hauptuntersuchung', pflicht: false, hinweis: 'Bei Halterwechsel erforderlich; bei reiner Adressänderung nicht.' },
      { was: 'Kennzeichenschilder', pflicht: false, hinweis: 'Nur wenn ein neues Kennzeichen zugeteilt wird.' },
    ],
    gebuehren: [
      { position: 'Umschreibung mit Halterwechsel', betrag: 'etwa 30 bis 40 Euro', art: 'bundeseinheitlich' },
      { position: 'Adressänderung im selben Zulassungsbezirk', betrag: 'etwa 11 bis 17 Euro', art: 'bundeseinheitlich' },
      { position: 'Neue Kennzeichenschilder', betrag: 'etwa 20 bis 35 Euro', art: 'sonstige' },
    ],
    fristen: [
      'Unverzüglich nach Halterwechsel oder Umzug - die Fahrzeug-Zulassungsverordnung verlangt die sofortige Anzeige.',
      'Der Verkäufer sollte die Veräußerung unverzüglich der Zulassungsbehörde anzeigen, um die Halterhaftung zu beenden.',
    ],
    bearbeitungsdauer: 'Vor Ort 20 bis 45 Minuten, online meist binnen weniger Werktage.',
    ablauf: [
      { nr: 1, titel: 'Reihenfolge beachten', detail: 'Erst den Wohnsitz anmelden, dann das Fahrzeug ummelden - die Zulassungsstelle prüft die aktuelle Meldeadresse.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bei Fahrzeugkauf: Kaufvertrag und Papiere prüfen', detail: 'Vergleichen Sie Fahrzeug-Identifizierungsnummer, Halterangaben und HU-Termin. Lassen Sie sich beide Teile der Zulassungsbescheinigung übergeben.', akteur: 'Bürger' },
      { nr: 3, titel: 'Umschreibung beantragen', detail: 'Persönlich oder über i-Kfz. Wählen Sie, ob Sie das Kennzeichen behalten oder ein neues wollen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Verkäufer: Veräußerungsanzeige stellen', detail: 'Der Verkäufer meldet den Verkauf mit Namen und Anschrift des Käufers an die Zulassungsbehörde. Ohne diese Anzeige haftet er weiter für Steuer und Verstöße.', akteur: 'Dritte' },
      { nr: 5, titel: 'Papiere und Plaketten aktualisieren', detail: 'Neue Zulassungsbescheinigung Teil I, gegebenenfalls neue Schilder und Plaketten.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 13 Fahrzeug-Zulassungsverordnung - Mitteilungspflichten bei Änderungen',
      '§ 15 ff. Fahrzeug-Zulassungsverordnung - Internetbasierte Verfahren',
      '§ 6 Kraftfahrzeugsteuergesetz - Steuerpflicht des Halters',
    ],
    online: {
      moeglich: true,
      hinweis: 'Umschreibung und Adressänderung sind über i-Kfz online möglich, wenn die Sicherheitscodes vorhanden sind. Bei Halterwechsel müssen beide Seiten mitwirken.',
      voraussetzungen: ['Online-Ausweisfunktion', 'Sicherheitscodes auf Zulassungsbescheinigung Teil I und II'],
    },
    haeufigeFehler: [
      'Als Verkäufer die Veräußerungsanzeige unterlassen und weiter Kfz-Steuer und Bußgelder tragen.',
      'Als Käufer wochenlang mit dem alten Halter im Register fahren.',
      'Beim Umzug nur den Wohnsitz ummelden und das Fahrzeug vergessen - das führt zu Problemen bei Bußgeldzustellungen und HU-Erinnerungen.',
      'Vergessen, die Versicherung über die Adressänderung zu informieren, was die Regionalklasse und den Beitrag beeinflusst.',
    ],
    faq: [
      { frage: 'Muss ich beim Umzug ein neues Kennzeichen nehmen?', antwort: 'Nein. Seit 2015 dürfen Sie Ihr Kennzeichen bundesweit behalten. Nur die Adresse in den Papieren ändert sich.' },
      { frage: 'Ich habe mein Auto verkauft. Was muss ich tun?', antwort: 'Übergeben Sie beide Teile der Zulassungsbescheinigung und zeigen Sie den Verkauf sofort der Zulassungsbehörde an - mit Kopie des Kaufvertrags, Name, Anschrift und Geburtsdatum des Käufers.' },
      { frage: 'Was passiert, wenn der Käufer nicht umschreibt?', antwort: 'Sie bleiben als Halter im Register geführt und haften für Kfz-Steuer, Bußgelder und Versicherungspflicht, bis die Veräußerungsanzeige greift. Deshalb ist sie so wichtig.' },
    ],
    verwandt: ['kfz-zulassung', 'kfz-abmeldung', 'wohnsitz-anmeldung'],
    eskalation: 'Bei Streit über den Halterwechsel, verlorenen Fahrzeugpapieren oder Zwangsstilllegung an die Zulassungsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht mit engen Gebührenrahmen.' },
    stand: '2026-08',
  },
  {
    id: 'kfz-abmeldung',
    cluster: 'kfz-verkehr',
    name: 'Fahrzeug außer Betrieb setzen',
    sprechName: 'Fahrzeug abmelden',
    synonyme: ['auto abmelden', 'fahrzeug abmelden', 'stilllegen', 'stilllegung', 'außer betrieb setzen', 'abmeldung fahrzeug', 'verschrotten', 'verwertungsnachweis', 'saisonpause'],
    leikaBezug: 'Fahrzeugzulassung - Außerbetriebsetzung (LeiKa 99045002)',
    kurzbeschreibung: 'Die Außerbetriebsetzung beendet Zulassung, Kfz-Steuer und Versicherungspflicht. Sie ist nötig bei Verkauf ins Ausland, Verschrottung, längerer Nichtnutzung oder vor einem Halterwechsel ohne Umschreibung.',
    zustaendigkeit: {
      stelle: 'Jede Kfz-Zulassungsbehörde in Deutschland',
      ebene: 'kommunal',
      hinweis: 'Die Außerbetriebsetzung ist die einzige Zulassungshandlung, die bundesweit bei jeder Zulassungsstelle möglich ist.',
    },
    voraussetzungen: [
      'Sie sind Halter oder verfügungsberechtigt beziehungsweise bevollmächtigt.',
      'Die Kennzeichenschilder liegen vor - sie werden entstempelt.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Zulassungsbescheinigung Teil I', pflicht: true },
      { was: 'Beide Kennzeichenschilder', pflicht: true, hinweis: 'Werden entstempelt und können bis zu zwölf Monate für dasselbe Fahrzeug reserviert bleiben.' },
      { was: 'Zulassungsbescheinigung Teil II', pflicht: false, hinweis: 'Bei Verschrottung erforderlich; sie wird eingezogen.' },
      { was: 'Verwertungsnachweis eines anerkannten Demontagebetriebs', pflicht: false, hinweis: 'Nur bei endgültiger Verschrottung.' },
    ],
    gebuehren: [
      { position: 'Außerbetriebsetzung', betrag: 'etwa 7 bis 20 Euro', art: 'bundeseinheitlich' },
      { position: 'Kennzeichenreservierung bei Außerbetriebsetzung', betrag: 'etwa 3 bis 13 Euro', art: 'bundeseinheitlich', hinweis: 'Das Kennzeichen bleibt sonst zwölf Monate ohnehin für dasselbe Fahrzeug vorgemerkt.' },
      { position: 'Online über i-Kfz', betrag: 'etwa 3 bis 6 Euro', art: 'bundeseinheitlich', hinweis: 'Deutlich günstiger als der Behördengang.' },
    ],
    fristen: [
      'Keine Frist - die Steuerpflicht endet mit dem Tag der Außerbetriebsetzung.',
      'Nach der Außerbetriebsetzung besteht ein siebenjähriger Zeitraum, in dem das Fahrzeug ohne erneute Vollabnahme wiederzugelassen werden kann, sofern die Hauptuntersuchung gültig ist.',
    ],
    bearbeitungsdauer: 'Vor Ort 10 bis 20 Minuten, online oft binnen weniger Stunden mit sofortiger Bestätigung.',
    ablauf: [
      { nr: 1, titel: 'Sicherheitscodes prüfen', detail: 'Für die Online-Abmeldung brauchen Sie die verdeckten Codes auf den Kennzeichenplaketten und auf der Zulassungsbescheinigung Teil I.', akteur: 'Bürger' },
      { nr: 2, titel: 'Abmeldung durchführen', detail: 'Online über i-Kfz oder persönlich mit Schildern und Papieren.', akteur: 'Bürger' },
      { nr: 3, titel: 'Entstempelung', detail: 'Die Plaketten auf den Schildern werden entwertet. Bei Online-Abmeldung entfällt das, die Codes werden entwertet.', akteur: 'Behörde' },
      { nr: 4, titel: 'Versicherung und Steuer beenden', detail: 'Die Behörde meldet die Außerbetriebsetzung an Versicherung und Zoll. Prüfen Sie dennoch Ihre Beitragsabrechnung. Statt Kündigung können Sie die Versicherung ruhen lassen - bei Fahrzeugen, die bis zu 18 Monate stillgelegt bleiben, gilt eine beitragsfreie Ruheversicherung.', akteur: 'Behörde' },
      { nr: 5, titel: 'Fahrzeug abstellen', detail: 'Ein außer Betrieb gesetztes Fahrzeug darf nicht auf öffentlichem Straßenland stehen - es gilt als Abfall und kann kostenpflichtig abgeschleppt werden. Nutzen Sie Privatgrund oder Garage.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 14 Fahrzeug-Zulassungsverordnung - Außerbetriebsetzung',
      '§ 5 Kraftfahrzeugsteuergesetz - Ende der Steuerpflicht',
      'Altfahrzeug-Verordnung (AltfahrzeugV) bei Verschrottung',
    ],
    online: {
      moeglich: true,
      hinweis: 'Die Außerbetriebsetzung war der erste i-Kfz-Dienst und ist heute in allen Zulassungsbezirken online möglich. Sie ist online deutlich billiger als vor Ort.',
      voraussetzungen: ['Online-Ausweisfunktion oder ELSTER-Zertifikat', 'Sicherheitscodes auf Plaketten und Zulassungsbescheinigung Teil I'],
    },
    haeufigeFehler: [
      'Das abgemeldete Fahrzeug auf der Straße stehen lassen.',
      'Die Versicherung sofort kündigen statt in die beitragsfreie Ruheversicherung zu wechseln.',
      'Bei Verschrottung den Verwertungsnachweis nicht besorgen - ohne ihn bleibt die Halterverantwortung bestehen.',
      'Annehmen, die Abmeldung ersetze die Veräußerungsanzeige beim Verkauf - beim Verkauf im Inland ist die Umschreibung durch den Käufer der richtige Weg.',
    ],
    faq: [
      { frage: 'Kann ich mein Kennzeichen behalten?', antwort: 'Ja. Nach der Außerbetriebsetzung bleibt es zwölf Monate für dasselbe Fahrzeug reserviert; gegen kleine Gebühr auch für eine spätere Wiederzulassung eines anderen Fahrzeugs desselben Halters.' },
      { frage: 'Was passiert mit der Kfz-Steuer?', antwort: 'Sie endet taggenau. Zu viel gezahlte Steuer erstattet der Zoll automatisch.' },
      { frage: 'Ich verkaufe ins Ausland - abmelden oder umschreiben?', antwort: 'Abmelden. Verlangen Sie eine Ausfuhrkennzeichnung oder händigen Sie dem Käufer die abgemeldeten Papiere aus. Für die Überführung braucht er ein Ausfuhrkennzeichen.' },
    ],
    verwandt: ['kfz-zulassung', 'kfz-ummeldung'],
    eskalation: 'Bei Zwangsstilllegung wegen fehlender Versicherung, bei Fahrzeugen im Ausland oder bei verlorenen Papieren an die Zulassungsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundeseinheitliches Verfahren; Gebühren im Rahmen der GebOSt.' },
    stand: '2026-08',
  },
  {
    id: 'wunschkennzeichen',
    cluster: 'kfz-verkehr',
    name: 'Wunschkennzeichen reservieren',
    sprechName: 'Wunschkennzeichen reservieren',
    synonyme: ['wunschkennzeichen', 'kennzeichen aussuchen', 'nummernschild wunsch', 'kennzeichen reservieren', 'eigenes kennzeichen'],
    leikaBezug: 'Fahrzeugzulassung - Wunschkennzeichen (LeiKa 99045002)',
    kurzbeschreibung: 'Sie können sich die Buchstaben- und Zahlenkombination Ihres Kennzeichens selbst aussuchen, sofern sie frei und zulässig ist. Die Reservierung erfolgt online und gilt in der Regel 90 Tage.',
    zustaendigkeit: {
      stelle: 'Kfz-Zulassungsbehörde des künftigen Halterwohnsitzes',
      ebene: 'kommunal',
      hinweis: 'Das Unterscheidungszeichen - die Buchstaben vor dem Bindestrich - ist an den Zulassungsbezirk gebunden; viele Kreise bieten mehrere Altkennzeichen an.',
    },
    voraussetzungen: [
      'Die Kombination ist im Zulassungsbezirk noch frei.',
      'Sie verstößt nicht gegen Ausschlussregeln: Kombinationen wie HJ, KZ, NS, SA, SS und in vielen Ländern auch SD und HH sind gesperrt.',
      'Die Zeichenzahl ist begrenzt: maximal acht Zeichen inklusive Unterscheidungszeichen, bei Motorrädern und kleinen Schildern weniger.',
    ],
    unterlagen: [
      { was: 'Reservierungsnummer oder Ausdruck der Reservierung', pflicht: true },
      { was: 'Alle Unterlagen der Zulassung', pflicht: true },
    ],
    gebuehren: [
      { position: 'Reservierung des Wunschkennzeichens', betrag: 'etwa 10,20 bis 13,00 Euro', art: 'bundeseinheitlich', hinweis: 'Wird zusätzlich zur Zulassungsgebühr erhoben.' },
      { position: 'Schilder mit Wunschkombination', betrag: 'etwa 20 bis 35 Euro', art: 'sonstige' },
    ],
    fristen: ['Die Reservierung gilt meist 90 Tage, in einigen Bezirken bis zu sechs Monate. Danach verfällt sie ersatzlos.'],
    bearbeitungsdauer: 'Reservierung online in Minuten mit sofortiger Bestätigung.',
    ablauf: [
      { nr: 1, titel: 'Verfügbarkeit prüfen', detail: 'Im Wunschkennzeichen-Portal Ihres Zulassungsbezirks die gewünschte Kombination eingeben. Freie Kombinationen werden sofort angezeigt.', akteur: 'Bürger' },
      { nr: 2, titel: 'Reservieren und zahlen', detail: 'Onlinezahlung per Karte oder Lastschrift; Sie erhalten eine Reservierungsnummer.', akteur: 'Bürger' },
      { nr: 3, titel: 'Schilder prägen lassen', detail: 'Bei einem Prägedienst - meist direkt am Amt oder online mit Versand.', akteur: 'Bürger' },
      { nr: 4, titel: 'Bei der Zulassung vorlegen', detail: 'Reservierungsnummer angeben; die Kombination wird dem Fahrzeug zugeteilt.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 8 Fahrzeug-Zulassungsverordnung - Zuteilung von Kennzeichen',
      'Anlage 2 zur Fahrzeug-Zulassungsverordnung - Unterscheidungszeichen',
      'Gebührenordnung für Maßnahmen im Straßenverkehr, Gebührennummer 221',
    ],
    online: {
      moeglich: true,
      hinweis: 'Nahezu flächendeckend online; die Reservierung ist Teil des i-Kfz-Verfahrens und kann direkt mit der Online-Zulassung verbunden werden.',
    },
    haeufigeFehler: [
      'Reservieren, aber die 90 Tage verstreichen lassen.',
      'Schilder prägen lassen, bevor die Reservierung bestätigt ist.',
      'Übersehen, dass bei Motorrädern und Elektro-Kleinfahrzeugen weniger Zeichen passen.',
    ],
    faq: [
      { frage: 'Kann ich mein altes Kennzeichen aus einer anderen Stadt wieder haben?', antwort: 'Nur wenn Sie im entsprechenden Zulassungsbezirk gemeldet sind oder das Fahrzeug dort seinen Standort hat. Behalten dürfen Sie ein bestehendes Kennzeichen bundesweit, neu zuteilen lassen aber nur im eigenen Bezirk.' },
      { frage: 'Welche Kombinationen sind verboten?', antwort: 'Historisch belastete Buchstabenfolgen wie HJ, KZ, NS, SA, SS - je nach Land auch weitere. Die Portale blockieren sie automatisch.' },
      { frage: 'Was ist ein E-Kennzeichen?', antwort: 'Elektrofahrzeuge erhalten auf Wunsch ein Kennzeichen mit angehängtem E, das kommunale Vorteile wie kostenloses Parken oder Busspurnutzung ermöglichen kann.' },
    ],
    verwandt: ['kfz-zulassung', 'kfz-ummeldung'],
    eskalation: 'Bei gesperrten Kombinationen oder Sonderkennzeichen wie Saison-, Oldtimer- oder Ausfuhrkennzeichen an die Zulassungsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrechtlicher Rahmen, gesperrte Kombinationen teils landesrechtlich ergänzt.' },
    stand: '2026-08',
  },
  {
    id: 'fuehrerschein-ersterteilung',
    cluster: 'kfz-verkehr',
    name: 'Fahrerlaubnis erstmals beantragen',
    sprechName: 'Führerschein beantragen',
    synonyme: ['führerschein machen', 'fahrerlaubnis beantragen', 'führerschein beantragen', 'erste fahrerlaubnis', 'führerschein klasse b', 'begleitetes fahren', 'bf17', 'fahrschule anmelden', 'roller führerschein'],
    leikaBezug: 'Fahrerlaubnis - Ersterteilung (LeiKa 99042001)',
    kurzbeschreibung: 'Die Fahrerlaubnis wird bei der Fahrerlaubnisbehörde beantragt, meist über die Fahrschule. Erforderlich sind Sehtest, Erste-Hilfe-Kurs, theoretische und praktische Ausbildung sowie beide Prüfungen bei einer amtlich anerkannten Prüforganisation.',
    zustaendigkeit: {
      stelle: 'Fahrerlaubnisbehörde - Straßenverkehrsamt des Kreises oder der kreisfreien Stadt am Hauptwohnsitz',
      ebene: 'kommunal',
      hinweis: 'Die Prüfungen nehmen TÜV oder DEKRA ab, nicht die Behörde. Die Fahrschule reicht den Antrag meist ein.',
    },
    voraussetzungen: [
      'Mindestalter: Klasse B 18 Jahre, begleitetes Fahren ab 17, Klasse AM und A1 ab 16, Klasse A2 ab 18, Klasse A ab 24 oder mit Stufenzugang ab 20.',
      'Ordentlicher Wohnsitz in Deutschland seit mindestens 185 Tagen im Jahr.',
      'Sehtest bei Optiker oder Augenarzt, nicht älter als zwei Jahre.',
      'Teilnahme an einem Erste-Hilfe-Kurs mit neun Unterrichtseinheiten.',
      'Keine Bedenken gegen die Eignung - Abfrage im Fahreignungsregister und Verkehrszentralregister.',
    ],
    unterlagen: [
      { was: 'Antragsformular der Fahrerlaubnisbehörde', pflicht: true, hinweis: 'Wird meist von der Fahrschule bereitgestellt und eingereicht.' },
      { was: 'Biometrisches Lichtbild', pflicht: true },
      { was: 'Sehtestbescheinigung', pflicht: true },
      { was: 'Bescheinigung über den Erste-Hilfe-Kurs', pflicht: true },
      { was: 'Personalausweis oder Reisepass mit Meldebescheinigung', pflicht: true },
      { was: 'Bei Klassen C und D: ärztliches Gutachten und augenärztliche Untersuchung', pflicht: false },
      { was: 'Bei begleitetem Fahren: Angaben zu den Begleitpersonen', pflicht: false, hinweis: 'Mindestens 30 Jahre alt, seit fünf Jahren Klasse B, höchstens ein Punkt im Fahreignungsregister.' },
    ],
    gebuehren: [
      { position: 'Antrag auf Ersterteilung bei der Behörde', betrag: 'etwa 40 bis 70 Euro', art: 'bundeseinheitlich' },
      { position: 'Theoretische Prüfung bei der Prüforganisation', betrag: 'etwa 25 bis 30 Euro', art: 'sonstige' },
      { position: 'Praktische Prüfung Klasse B', betrag: 'etwa 130 bis 150 Euro', art: 'sonstige' },
      { position: 'Sehtest', betrag: 'etwa 7 Euro', art: 'sonstige' },
      { position: 'Erste-Hilfe-Kurs', betrag: 'etwa 30 bis 60 Euro', art: 'sonstige' },
      { position: 'Fahrschule insgesamt', betrag: 'je nach Region und Fahrstunden etwa 2.500 bis 4.500 Euro', art: 'sonstige', hinweis: 'Freie Preisbildung der Fahrschulen; die Behördengebühr ist nur ein kleiner Teil.' },
    ],
    fristen: [
      'Der Antrag darf frühestens sechs Monate vor Erreichen des Mindestalters gestellt werden.',
      'Die theoretische Prüfung ist frühestens drei Monate vor dem Mindestalter möglich, die praktische einen Monat vorher.',
      'Nach bestandener Theorieprüfung haben Sie zwölf Monate Zeit für die Praxisprüfung.',
      'Die Prüfaufträge sind ab Erteilung der Behörde in der Regel zwölf Monate gültig.',
    ],
    bearbeitungsdauer: 'Prüfung des Antrags durch die Behörde etwa vier bis sechs Wochen, in Ballungsräumen länger. Die gesamte Ausbildung dauert erfahrungsgemäß drei bis sechs Monate.',
    ablauf: [
      { nr: 1, titel: 'Fahrschule wählen und anmelden', detail: 'Die Fahrschule berät zur Klasse und stellt die Ausbildungsbescheinigung. Achten Sie auf Preisliste und Prüfungsquote.', akteur: 'Bürger' },
      { nr: 2, titel: 'Sehtest und Erste Hilfe absolvieren', detail: 'Beides ist unabhängig von der Fahrschule möglich und sollte früh erledigt werden.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag einreichen', detail: 'Meist über die Fahrschule an die Fahrerlaubnisbehörde. Die Behörde prüft Eignung und Register.', akteur: 'Bürger' },
      { nr: 4, titel: 'Theorieunterricht und Prüfung', detail: 'Pflichtstunden je nach Klasse - bei Klasse B zwölf Doppelstunden Grundstoff und zwei klassenspezifische. Prüfung am Computer bei TÜV oder DEKRA.', akteur: 'Bürger' },
      { nr: 5, titel: 'Praktische Ausbildung', detail: 'Sonderfahrten sind vorgeschrieben: bei Klasse B fünf Überland-, vier Autobahn- und drei Nachtfahrten.', akteur: 'Bürger' },
      { nr: 6, titel: 'Praktische Prüfung', detail: 'Etwa 55 Minuten Fahrzeit bei Klasse B mit Prüfer der Prüforganisation und Fahrlehrer im Fahrzeug.', akteur: 'Bürger' },
      { nr: 7, titel: 'Führerschein abholen', detail: 'Nach bestandener Prüfung händigt in vielen Ländern der Prüfer den Kartenführerschein direkt aus, sonst die Behörde. Es beginnt die zweijährige Probezeit.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 2 Straßenverkehrsgesetz - Fahrerlaubnis',
      '§ 6 ff. Fahrerlaubnis-Verordnung - Klasseneinteilung und Mindestalter',
      '§ 48a Fahrerlaubnis-Verordnung - Begleitetes Fahren ab 17',
      'Fahrschüler-Ausbildungsordnung (FahrschAusbO)',
      'Prüfungsrichtlinie und Gebührenordnung für Maßnahmen im Straßenverkehr',
    ],
    online: {
      moeglich: true,
      hinweis: 'Einige Länder bieten den digitalen Führerscheinantrag; in der Praxis läuft der Antrag meist über die Fahrschule. Der Führerschein selbst wird persönlich ausgehändigt.',
    },
    haeufigeFehler: [
      'Erst nach Ausbildungsbeginn den Antrag stellen und dann auf die Prüfungsfreigabe warten müssen.',
      'Sehtest oder Erste-Hilfe-Bescheinigung veralten lassen.',
      'Die Zwölfmonatsfrist zwischen Theorie- und Praxisprüfung verstreichen lassen.',
      'Beim begleiteten Fahren die Begleitperson nicht eintragen lassen - dann gilt die Fahrt als Fahren ohne Fahrerlaubnis.',
    ],
    faq: [
      { frage: 'Wie lange gilt die Probezeit?', antwort: 'Zwei Jahre ab Erteilung. Bei einem schwerwiegenden Verstoß verlängert sie sich auf vier Jahre und ein Aufbauseminar wird angeordnet.' },
      { frage: 'Kann ich Klasse B auf Automatik machen?', antwort: 'Ja. Seit April 2021 gibt es die Schlüsselzahl 197: Wer auf Automatik ausbildet, aber mindestens zehn Fahrstunden und eine Prüfungsfahrt mit Schaltgetriebe nachweist, erhält eine uneingeschränkte Klasse B.' },
      { frage: 'Was kostet der Führerschein insgesamt?', antwort: 'Realistisch 2.500 bis 4.500 Euro je nach Region und Zahl der Fahrstunden. Die Behördengebühren machen davon nur etwa 200 bis 300 Euro aus.' },
    ],
    verwandt: ['fuehrerschein-umtausch', 'fuehrerschein-verlust', 'internationaler-fuehrerschein'],
    eskalation: 'Bei Eignungszweifeln, medizinisch-psychologischer Untersuchung, ausländischen Vorbesitzen oder Entziehung der Fahrerlaubnis an die Fahrerlaubnisbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht; Fahrschulpreise sind frei und regional sehr unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'fuehrerschein-umtausch',
    cluster: 'kfz-verkehr',
    name: 'Führerschein umtauschen',
    sprechName: 'Führerschein umtauschen',
    synonyme: ['führerschein umtauschen', 'alter führerschein', 'papierführerschein', 'graue lappen', 'rosa führerschein', 'kartenführerschein', 'umtauschpflicht', 'führerschein tauschen'],
    leikaBezug: 'Fahrerlaubnis - Umtausch (LeiKa 99042005)',
    kurzbeschreibung: 'Alle vor dem 19. Januar 2013 ausgestellten Führerscheine müssen gestaffelt in fälschungssichere EU-Kartenführerscheine umgetauscht werden. Die Staffel richtet sich bei Papierführerscheinen nach dem Geburtsjahr, bei Kartenführerscheinen nach dem Ausstellungsjahr.',
    zustaendigkeit: {
      stelle: 'Fahrerlaubnisbehörde am Hauptwohnsitz',
      ebene: 'kommunal',
      hinweis: 'Wurde der Führerschein in einer anderen Stadt ausgestellt, muss dort die Karteikarte angefordert werden - das verlängert die Bearbeitung.',
    },
    voraussetzungen: [
      'Sie besitzen einen gültigen deutschen Führerschein, der vor dem 19. Januar 2013 ausgestellt wurde.',
      'Es handelt sich um einen reinen Dokumententausch - keine neue Prüfung, kein Sehtest, keine ärztliche Untersuchung, außer bei Klassen C und D.',
    ],
    unterlagen: [
      { was: 'Bisheriger Führerschein', pflicht: true },
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Biometrisches Lichtbild', pflicht: true },
      { was: 'Karteikartenabschrift der ausstellenden Behörde', pflicht: false, hinweis: 'Nur nötig, wenn der Führerschein nicht von Ihrer heutigen Behörde ausgestellt wurde; oft fordert die Behörde sie selbst an.' },
      { was: 'Bei Klassen C, C1, D, D1: ärztliche und augenärztliche Untersuchung', pflicht: false, hinweis: 'Diese Klassen sind befristet und werden nur mit Nachweisen verlängert.' },
    ],
    gebuehren: [
      { position: 'Umtausch Führerschein', betrag: '25,30 Euro', art: 'bundeseinheitlich', hinweis: 'Zuzüglich etwaiger Gebühr für die Karteikartenabschrift von etwa 5 bis 15 Euro.' },
      { position: 'Verlängerung Klassen C und D', betrag: 'etwa 30 bis 45 Euro', art: 'bundeseinheitlich', hinweis: 'Zuzüglich Kosten für die ärztlichen Untersuchungen von etwa 100 bis 200 Euro.' },
    ],
    fristen: [
      'Papierführerscheine nach Geburtsjahr: Jahrgänge 1953 bis 1958 bis 19. Januar 2022, 1959 bis 1964 bis 19. Januar 2023, 1965 bis 1970 bis 19. Januar 2024, ab 1971 bis 19. Januar 2025. Jahrgänge vor 1953 haben bis 19. Januar 2033 Zeit.',
      'Kartenführerscheine nach Ausstellungsjahr: 1999 bis 2001 bis 19. Januar 2026, 2002 bis 2004 bis 19. Januar 2027, danach jährlich gestaffelt bis 19. Januar 2033.',
      'Der neue Kartenführerschein ist 15 Jahre gültig und wird danach ohne Prüfung erneuert.',
    ],
    bearbeitungsdauer: 'Drei bis sechs Wochen. Muss eine Karteikarte aus einer anderen Stadt angefordert werden, dauert es länger.',
    ablauf: [
      { nr: 1, titel: 'Umtauschfrist prüfen', detail: 'Papierführerschein: Geburtsjahr entscheidet. Kartenführerschein: Ausstellungsdatum in Feld 4a entscheidet.', akteur: 'Bürger' },
      { nr: 2, titel: 'Unterlagen zusammenstellen', detail: 'Alter Führerschein, Ausweis, Lichtbild. Wenn die Fahrerlaubnis von einer anderen Behörde stammt, dort die Karteikartenabschrift anfordern.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag stellen', detail: 'Persönlich oder in einigen Kommunen schriftlich beziehungsweise online. Der alte Führerschein bleibt bis zur Abholung meist bei Ihnen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Abholen', detail: 'Persönlich; der alte Führerschein wird eingezogen und entwertet. Auf Wunsch geben viele Behörden ihn gelocht als Andenken zurück.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 24a Fahrerlaubnis-Verordnung - Umtausch von Führerscheinen',
      'Anlage 8e zur Fahrerlaubnis-Verordnung - Umtauschfristen',
      'EU-Führerscheinrichtlinie 2006/126/EG',
    ],
    online: {
      moeglich: true,
      hinweis: 'Zunehmend als Online-Dienst mit digitalem Lichtbild und eID; in vielen Kreisen weiterhin schriftlich per Post möglich, ohne Termin.',
    },
    haeufigeFehler: [
      'Die Frist verstreichen lassen - danach droht ein Verwarnungsgeld von 10 Euro, im Ausland kann das Dokument als ungültig angesehen werden.',
      'Annehmen, mit dem Umtausch verfalle die Fahrerlaubnis - nein, nur das Dokument wird ersetzt.',
      'Bei Klassen C und D die Untersuchungstermine zu spät machen.',
      'Übersehen, dass alte Klasse-3-Rechte beim Umtausch teilweise in eingeschränkte neue Klassen überführt werden.',
    ],
    faq: [
      { frage: 'Verliere ich Rechte beim Umtausch?', antwort: 'Bestandsrechte bleiben grundsätzlich erhalten und werden über Schlüsselzahlen abgebildet. Die alte Klasse 3 wird etwa zu B, BE, C1, C1E und mit Schlüsselzahl 79 zu weiteren Berechtigungen.' },
      { frage: 'Was passiert, wenn ich die Frist versäume?', antwort: 'Es droht ein Verwarnungsgeld von 10 Euro. Die Fahrerlaubnis selbst bleibt bestehen, aber das Dokument ist nicht mehr gültig - im EU-Ausland kann das erhebliche Probleme geben.' },
      { frage: 'Brauche ich eine neue Prüfung?', antwort: 'Nein, es ist ein reiner Dokumententausch.' },
    ],
    verwandt: ['fuehrerschein-ersterteilung', 'fuehrerschein-verlust', 'internationaler-fuehrerschein'],
    eskalation: 'Bei im Ausland erworbenen Fahrerlaubnissen, bei verschollenen Karteikarten oder bei Bestandsschutzfragen an die Fahrerlaubnisbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundeseinheitliche Fristen und Gebühr von 25,30 Euro.' },
    stand: '2026-08',
  },
  {
    id: 'fuehrerschein-verlust',
    cluster: 'kfz-verkehr',
    name: 'Ersatzführerschein bei Verlust oder Diebstahl',
    sprechName: 'Führerschein verloren',
    synonyme: ['führerschein verloren', 'führerschein weg', 'führerschein gestohlen', 'ersatzführerschein', 'neuer führerschein', 'führerschein beschädigt'],
    leikaBezug: 'Fahrerlaubnis - Ersatzausfertigung (LeiKa 99042005)',
    kurzbeschreibung: 'Geht der Führerschein verloren oder wird er gestohlen, stellt die Fahrerlaubnisbehörde eine Ersatzausfertigung aus. Die Fahrerlaubnis selbst bleibt bestehen - nur das Dokument wird ersetzt.',
    zustaendigkeit: {
      stelle: 'Fahrerlaubnisbehörde am Hauptwohnsitz',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Sie besitzen eine gültige Fahrerlaubnis, die nicht entzogen wurde.',
      'Eidesstattliche Versicherung über den Verlust oder polizeiliche Diebstahlsanzeige.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Biometrisches Lichtbild', pflicht: true },
      { was: 'Eidesstattliche Versicherung über den Verlust', pflicht: true, hinweis: 'Wird vor Ort abgegeben; falsche Angaben sind strafbar.' },
      { was: 'Polizeiliche Anzeige bei Diebstahl', pflicht: false },
      { was: 'Karteikartenabschrift der ausstellenden Behörde', pflicht: false },
    ],
    gebuehren: [
      { position: 'Ersatzführerschein', betrag: 'etwa 35,20 bis 40 Euro', art: 'bundeseinheitlich' },
      { position: 'Karteikartenabschrift', betrag: 'etwa 5 bis 15 Euro', art: 'kommunal' },
      { position: 'Vorläufiger Nachweis der Fahrerlaubnis', betrag: 'etwa 10 bis 15 Euro', art: 'kommunal', hinweis: 'Nicht überall angeboten; gilt nur im Inland.' },
    ],
    fristen: ['Keine gesetzliche Frist. Ohne Führerschein dürfen Sie zwar fahren, müssen ihn aber auf Verlangen vorzeigen - sonst droht ein Verwarnungsgeld von 10 Euro.'],
    bearbeitungsdauer: 'Drei bis fünf Wochen. Manche Behörden stellen eine vorläufige Bescheinigung aus, die nur in Deutschland gilt.',
    ablauf: [
      { nr: 1, titel: 'Bei Diebstahl Anzeige erstatten', detail: 'Polizeiliche Anzeige beugt Missbrauch vor.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag bei der Behörde stellen', detail: 'Mit Ausweis, Lichtbild und eidesstattlicher Versicherung.', akteur: 'Bürger' },
      { nr: 3, titel: 'Registerabfrage und Herstellung', detail: 'Die Behörde prüft die Fahrerlaubnis und lässt die Karte produzieren.', akteur: 'Behörde' },
      { nr: 4, titel: 'Abholen', detail: 'Persönlich. Taucht der alte Führerschein wieder auf, ist er abzugeben - er wird ungültig.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 25 Abs. 4 Fahrerlaubnis-Verordnung - Ersatzführerschein',
      '§ 4 Abs. 2 Fahrerlaubnis-Verordnung - Mitführungs- und Aushändigungspflicht',
    ],
    online: {
      moeglich: true,
      hinweis: 'In einigen Kreisen als Online-Dienst; die eidesstattliche Versicherung wird dann elektronisch abgegeben.',
    },
    haeufigeFehler: [
      'Ohne Führerschein weiterfahren und annehmen, das sei Fahren ohne Fahrerlaubnis - es ist nur ein Verwarnungsgeld, solange die Fahrerlaubnis besteht.',
      'Den wiedergefundenen alten Führerschein behalten.',
      'Bei bevorstehenden Auslandsreisen keinen vorläufigen Nachweis erfragen.',
    ],
    faq: [
      { frage: 'Darf ich ohne Führerschein fahren?', antwort: 'Ja, die Fahrerlaubnis besteht fort. Sie können den Führerschein aber nicht vorzeigen - das kostet 10 Euro Verwarnungsgeld. Im Ausland kann es deutlich unangenehmer werden.' },
      { frage: 'Was ist bei einem beschädigten Führerschein?', antwort: 'Gleiches Verfahren, aber statt der eidesstattlichen Versicherung geben Sie das beschädigte Dokument ab.' },
    ],
    verwandt: ['fuehrerschein-umtausch', 'fuehrerschein-ersterteilung'],
    eskalation: 'Bei entzogener Fahrerlaubnis, ausländischen Führerscheinen oder Zweifeln am Bestand der Fahrerlaubnis an die Behörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrechtliche Gebührenordnung mit engem Rahmen.' },
    stand: '2026-08',
  },
  {
    id: 'internationaler-fuehrerschein',
    cluster: 'kfz-verkehr',
    name: 'Internationalen Führerschein beantragen',
    sprechName: 'Internationaler Führerschein',
    synonyme: ['internationaler führerschein', 'international driving permit', 'führerschein ausland', 'mietwagen ausland', 'übersetzung führerschein'],
    leikaBezug: 'Internationaler Führerschein - Ausstellung (LeiKa 99042005)',
    kurzbeschreibung: 'Der internationale Führerschein ist eine mehrsprachige Übersetzung Ihres Kartenführerscheins und wird für Fahrten außerhalb der EU verlangt. Er gilt nur zusammen mit dem nationalen Führerschein.',
    zustaendigkeit: {
      stelle: 'Fahrerlaubnisbehörde am Hauptwohnsitz',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Sie besitzen einen gültigen EU-Kartenführerschein - alte Papierführerscheine müssen zuvor umgetauscht werden.',
      'Der internationale Führerschein wird nur zusätzlich, nie allein ausgestellt.',
    ],
    unterlagen: [
      { was: 'Gültiger Kartenführerschein', pflicht: true },
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Biometrisches Lichtbild', pflicht: true },
    ],
    gebuehren: [
      { position: 'Internationaler Führerschein', betrag: '16,00 bis 20,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Zusätzlich nötiger Umtausch des Papierführerscheins', betrag: '25,30 Euro', art: 'bundeseinheitlich' },
    ],
    fristen: [
      'Gültigkeit nach dem Wiener Übereinkommen von 1968: drei Jahre, längstens bis zum Ablauf des nationalen Führerscheins.',
      'Für Staaten des Genfer Abkommens von 1949 - etwa die USA in einigen Bundesstaaten - gilt eine Version mit einem Jahr Gültigkeit.',
    ],
    bearbeitungsdauer: 'Häufig sofort im Termin, sonst wenige Tage.',
    ablauf: [
      { nr: 1, titel: 'Prüfen, ob das Zielland ihn verlangt', detail: 'Innerhalb der EU und des EWR nicht nötig. In vielen Ländern Asiens, Afrikas und Amerikas dagegen Pflicht - die Reisehinweise des Auswärtigen Amts nennen die Details.', akteur: 'Bürger' },
      { nr: 2, titel: 'Kartenführerschein sicherstellen', detail: 'Papierführerscheine berechtigen nicht zur Ausstellung; zuerst umtauschen.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag stellen', detail: 'Meist ohne Termin am Schalter, in einigen Kreisen auch schriftlich.', akteur: 'Bürger' },
      { nr: 4, titel: 'Auf Reisen beide Dokumente mitführen', detail: 'Der internationale Führerschein ist ohne den nationalen ungültig.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 25b Fahrerlaubnis-Verordnung - Internationaler Führerschein',
      'Wiener Übereinkommen über den Straßenverkehr von 1968',
      'Genfer Abkommen über den Straßenverkehr von 1949',
    ],
    online: { moeglich: false, hinweis: 'In der Regel persönliche Vorsprache, da der Kartenführerschein vorgelegt werden muss. Einige Kreise bieten die schriftliche Beantragung an.' },
    haeufigeFehler: [
      'Zu spät beantragen, wenn noch der Papierführerschein umgetauscht werden muss.',
      'Nur den internationalen Führerschein mitnehmen.',
      'Annehmen, er ersetze ein Visum oder eine Mietwagenversicherung.',
    ],
    faq: [
      { frage: 'Brauche ich ihn für die USA?', antwort: 'Formal verlangen ihn nur einzelne Bundesstaaten, viele Mietwagenfirmen bestehen aber darauf. Er ist günstig - im Zweifel mitnehmen.' },
      { frage: 'Wie lange gilt er?', antwort: 'Drei Jahre nach dem Wiener Abkommen, längstens bis zum Ablauf Ihres Kartenführerscheins.' },
    ],
    verwandt: ['fuehrerschein-umtausch', 'fuehrerschein-ersterteilung'],
    eskalation: 'Bei Fragen zu Anerkennung im Zielland an die Auslandsvertretung oder Automobilclubs verweisen.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrechtlich geregelt, Gebühren nur leicht abweichend.' },
    stand: '2026-08',
  },
  {
    id: 'bewohnerparkausweis',
    cluster: 'kfz-verkehr',
    name: 'Bewohnerparkausweis beantragen',
    sprechName: 'Bewohnerparkausweis',
    synonyme: ['anwohnerparken', 'bewohnerparkausweis', 'anwohnerparkausweis', 'parkausweis', 'parkvignette', 'parken vor der haustür', 'parkberechtigung'],
    leikaBezug: 'Bewohnerparkausweis - Ausstellung (LeiKa 99045015)',
    kurzbeschreibung: 'In ausgewiesenen Bewohnerparkgebieten dürfen Anwohner mit Parkausweis ohne Parkschein und ohne Zeitbeschränkung parken. Der Ausweis wird von der Straßenverkehrsbehörde oder dem Ordnungsamt ausgestellt.',
    zustaendigkeit: {
      stelle: 'Straßenverkehrsbehörde oder Ordnungsamt der Stadt',
      ebene: 'kommunal',
      hinweis: 'Nur Städte mit ausgewiesenen Bewohnerparkzonen bieten die Leistung an.',
    },
    voraussetzungen: [
      'Hauptwohnsitz im ausgewiesenen Bewohnerparkgebiet - in einigen Städten reicht der Nebenwohnsitz nicht.',
      'Sie sind Halter des Fahrzeugs oder nutzen es dauerhaft, etwa als Dienst-, Leasing- oder Carsharing-Fahrzeug mit Nachweis.',
      'Kein eigener Stellplatz oder keine Garage auf dem Grundstück - das prüfen viele Städte.',
    ],
    unterlagen: [
      { was: 'Personalausweis mit Adresse im Gebiet oder Meldebescheinigung', pflicht: true },
      { was: 'Zulassungsbescheinigung Teil I', pflicht: true },
      { was: 'Bei Firmen-, Leasing- oder Dienstwagen: Überlassungsnachweis des Halters', pflicht: false },
    ],
    gebuehren: [
      { position: 'Bewohnerparkausweis pro Jahr', betrag: 'etwa 20 bis 360 Euro', art: 'kommunal', hinweis: 'Seit dem Wegfall der bundesrechtlichen Obergrenze von 30,70 Euro im Jahr 2020 setzen die Länder und Kommunen die Gebühr selbst fest. Die Spanne ist entsprechend groß; einige Städte staffeln nach Fahrzeuglänge.' },
    ],
    fristen: [
      'Gültigkeit meist ein bis zwei Jahre; rechtzeitig verlängern.',
      'Bei Umzug oder Fahrzeugwechsel ist der Ausweis unverzüglich zurückzugeben oder ändern zu lassen.',
    ],
    bearbeitungsdauer: 'Online oft sofort mit digitalem Ausweis, sonst wenige Tage bis zwei Wochen.',
    ablauf: [
      { nr: 1, titel: 'Parkzone prüfen', detail: 'Auf dem Stadtplan der Kommune sehen Sie, ob und in welcher Zone Ihre Adresse liegt.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag stellen', detail: 'Online, schriftlich oder am Schalter, mit Fahrzeug- und Meldedaten.', akteur: 'Bürger' },
      { nr: 3, titel: 'Prüfung', detail: 'Die Behörde gleicht Melderegister und Fahrzeugdaten ab und prüft, ob ein privater Stellplatz vorhanden ist.', akteur: 'Behörde' },
      { nr: 4, titel: 'Ausweis erhalten und auslegen', detail: 'Klassisch als Vignette hinter der Windschutzscheibe, zunehmend rein digital über die Kennzeichenerfassung.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 45 Abs. 1b Straßenverkehrsordnung - Bewohnerparkvorrechte',
      '§ 6a Straßenverkehrsgesetz - Gebühren für Bewohnerparkausweise',
      'Landesrechtliche Gebührenverordnungen und kommunale Satzungen',
    ],
    online: {
      moeglich: true,
      hinweis: 'In den meisten größeren Städten vollständig online, häufig mit sofort gültiger digitaler Berechtigung.',
    },
    haeufigeFehler: [
      'Mit Nebenwohnsitz beantragen, wo nur der Hauptwohnsitz zählt.',
      'Vergessen, den Ausweis bei Fahrzeugwechsel umschreiben zu lassen - er gilt kennzeichenbezogen.',
      'Annehmen, der Ausweis garantiere einen Stellplatz - er berechtigt nur zum Parken ohne Gebühr und Zeitbegrenzung, wenn Platz frei ist.',
      'Die Verlängerung verpassen und Verwarnungsgelder riskieren.',
    ],
    faq: [
      { frage: 'Warum kostet das in manchen Städten so viel mehr?', antwort: 'Seit 2020 dürfen Länder und Kommunen die Gebühr selbst festlegen. Gerichte haben einzelne sehr hohe Satzungen gekippt, andere bestätigt - die Preise reichen daher von rund 20 bis über 300 Euro im Jahr.' },
      { frage: 'Gilt der Ausweis in der ganzen Stadt?', antwort: 'Nein, nur in der eingetragenen Zone, teilweise mit angrenzenden Bereichen.' },
      { frage: 'Ich habe einen Dienstwagen - geht das?', antwort: 'Ja, mit einer Bescheinigung des Halters, dass Ihnen das Fahrzeug dauerhaft überlassen ist.' },
    ],
    verwandt: ['kfz-zulassung', 'wohnsitz-anmeldung', 'sondernutzungserlaubnis'],
    eskalation: 'Bei Ablehnung wegen vorhandenem Stellplatz oder bei Gebührenstreit an die Straßenverkehrsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Gebühren und Voraussetzungen unterscheiden sich stark je Stadt. Nennen Sie Beträge ausdrücklich als Spanne.' },
    stand: '2026-08',
  },
  {
    id: 'schwerbehindertenparkausweis',
    cluster: 'kfz-verkehr',
    name: 'Parkausweis für Menschen mit Behinderung beantragen',
    sprechName: 'Behindertenparkausweis',
    synonyme: ['behindertenparkausweis', 'blauer parkausweis', 'orangener parkausweis', 'parkerleichterung', 'merkzeichen ag', 'merkzeichen bl', 'behindertenparkplatz', 'ag merkzeichen'],
    leikaBezug: 'Parkerleichterungen für schwerbehinderte Menschen (LeiKa 99045015)',
    kurzbeschreibung: 'Menschen mit bestimmten Merkzeichen im Schwerbehindertenausweis erhalten den blauen EU-Parkausweis oder den orangenen bundesdeutschen Parkausweis mit besonderen Parkrechten.',
    zustaendigkeit: {
      stelle: 'Straßenverkehrsbehörde oder Ordnungsamt der Stadt oder des Kreises',
      ebene: 'kommunal',
      hinweis: 'Der Schwerbehindertenausweis mit den Merkzeichen kommt hingegen vom Versorgungsamt.',
    },
    voraussetzungen: [
      'Blauer EU-Parkausweis: Merkzeichen aG - außergewöhnlich gehbehindert - oder Bl - blind - oder beidseitige Amelie oder Phokomelie.',
      'Orangener Parkausweis: bestimmte Konstellationen etwa mit Merkzeichen G und B und einem Grad der Behinderung von mindestens 80 wegen Störungen der Gehfähigkeit, oder Menschen mit Morbus Crohn, Colitis ulcerosa oder künstlichem Darmausgang unter näheren Voraussetzungen.',
      'Vorlage des Schwerbehindertenausweises oder des Feststellungsbescheids.',
    ],
    unterlagen: [
      { was: 'Schwerbehindertenausweis mit Merkzeichen', pflicht: true },
      { was: 'Personalausweis', pflicht: true },
      { was: 'Lichtbild', pflicht: true, hinweis: 'Der Parkausweis ist personengebunden und trägt ein Foto.' },
      { was: 'Feststellungsbescheid des Versorgungsamts', pflicht: false },
    ],
    gebuehren: [
      { position: 'Blauer und orangener Parkausweis', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Die Ausstellung ist gebührenfrei.' },
    ],
    fristen: ['Gültigkeit meist fünf Jahre oder bis zum Ablauf des Schwerbehindertenausweises; Verlängerung rechtzeitig beantragen.'],
    bearbeitungsdauer: 'Häufig sofort im Termin, sonst ein bis drei Wochen.',
    ablauf: [
      { nr: 1, titel: 'Merkzeichen prüfen', detail: 'Blauer Ausweis nur bei aG, Bl oder vergleichbaren Fällen. Fehlt das Merkzeichen, ist zuerst ein Neufeststellungsantrag beim Versorgungsamt nötig.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag stellen', detail: 'Bei der Straßenverkehrsbehörde mit Ausweis, Foto und Schwerbehindertenausweis.', akteur: 'Bürger' },
      { nr: 3, titel: 'Ausweis erhalten', detail: 'Er ist personen-, nicht fahrzeuggebunden und gilt in jedem Fahrzeug, in dem die berechtigte Person mitfährt.', akteur: 'Behörde' },
      { nr: 4, titel: 'Richtig nutzen', detail: 'Sichtbar hinter der Windschutzscheibe auslegen. Der blaue Ausweis gilt EU-weit, der orangene nur in Deutschland und nicht auf Behindertenparkplätzen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 46 Abs. 1 Nr. 11 Straßenverkehrsordnung - Ausnahmegenehmigungen',
      'Allgemeine Verwaltungsvorschrift zur Straßenverkehrsordnung zu § 46',
      'Empfehlung 98/376/EG des Rates über den Parkausweis für Behinderte',
      'Neuntes Buch Sozialgesetzbuch (SGB IX) - Merkzeichen',
    ],
    online: { moeglich: true, hinweis: 'In vielen Kommunen als Online-Antrag mit Upload der Nachweise; die Abholung ist meist persönlich.' },
    haeufigeFehler: [
      'Den orangenen Ausweis auf Behindertenparkplätzen nutzen - das ist nicht erlaubt.',
      'Den Ausweis anderen überlassen, wenn die berechtigte Person nicht mitfährt - das ist Missbrauch und führt zur Einziehung.',
      'Verlängerung vergessen.',
    ],
    faq: [
      { frage: 'Was darf ich mit dem blauen Ausweis?', antwort: 'Auf gekennzeichneten Behindertenparkplätzen parken, im eingeschränkten Halteverbot bis zu drei Stunden, an Parkuhren ohne Gebühr und über die Höchstparkdauer hinaus, in Fußgängerzonen während der Ladezeiten und in Bewohnerparkgebieten.' },
      { frage: 'Ich habe nur Merkzeichen G - reicht das?', antwort: 'Für den blauen Ausweis nicht. Für den orangenen kann es in Kombination mit weiteren Voraussetzungen reichen; die Behörde prüft im Einzelfall.' },
      { frage: 'Gilt der Ausweis im Ausland?', antwort: 'Der blaue EU-Parkausweis gilt in allen EU-Staaten, die Regeln vor Ort können aber abweichen.' },
    ],
    verwandt: ['schwerbehindertenausweis', 'bewohnerparkausweis'],
    eskalation: 'Bei fehlenden Merkzeichen an das Versorgungsamt, bei Ablehnung an die Straßenverkehrsbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrechtlich vorgegebene Voraussetzungen; die orangene Variante wird in den Ländern teils erweitert.' },
    stand: '2026-08',
  },
];
