/** Stufe 2: Leistungen des Clusters "Melde- und Ausweisangelegenheiten". */
export const LEISTUNGEN = [
  {
    id: 'wohnsitz-anmeldung',
    cluster: 'melde-ausweis',
    name: 'Wohnsitz anmelden oder ummelden',
    sprechName: 'Wohnsitz anmelden oder ummelden',
    synonyme: ['anmelden', 'ummelden', 'ummeldung', 'anmeldung wohnsitz', 'umgezogen', 'gezogen', 'hergezogen', 'zugezogen', 'neue wohnung anmelden', 'adresse ändern', 'adressänderung', 'wohnsitz ändern', 'einwohnermeldeamt anmelden', 'nach umzug anmelden', 'zweitwohnsitz anmelden'],
    leikaBezug: 'Meldebescheinigung/Anmeldung einer Wohnung (LeiKa 99083016)',
    kurzbeschreibung: 'Wer eine Wohnung bezieht, muss sich innerhalb von zwei Wochen bei der Meldebehörde der neuen Gemeinde anmelden. Das gilt für den Zuzug von außerhalb ebenso wie für den Umzug innerhalb der Gemeinde und für Neben- oder Zweitwohnungen.',
    zustaendigkeit: {
      stelle: 'Bürgeramt, Bürgerbüro oder Einwohnermeldeamt der neuen Wohnsitzgemeinde',
      ebene: 'kommunal',
      hinweis: 'Zuständig ist ausschließlich die Gemeinde, in die Sie einziehen. Eine Abmeldung am alten Ort ist innerhalb Deutschlands nicht nötig - die alte Gemeinde wird automatisch informiert.',
    },
    voraussetzungen: [
      'Sie haben eine Wohnung im Sinne des § 20 BMG bezogen, also einen umschlossenen Raum, der zum Wohnen oder Schlafen genutzt wird.',
      'Der Einzug hat bereits stattgefunden - eine Anmeldung im Voraus ist nicht zulässig.',
      'Sie erscheinen persönlich oder lassen sich mit schriftlicher Vollmacht vertreten.',
      'Bei mehreren Wohnungen bestimmen Sie eine als Hauptwohnung; maßgeblich ist die vorwiegend benutzte Wohnung, bei Verheirateten die vorwiegend genutzte Familienwohnung.',
    ],
    unterlagen: [
      { was: 'Gültiger Personalausweis, Reisepass oder Passersatzpapier aller anzumeldenden Personen', pflicht: true, hinweis: 'Bei Kindern genügt die Geburtsurkunde, wenn kein Ausweisdokument vorhanden ist.' },
      { was: 'Wohnungsgeberbestätigung nach § 19 BMG', pflicht: true, hinweis: 'Vom Vermieter oder der Hausverwaltung, spätestens zwei Wochen nach Einzug auszustellen. Der Mietvertrag allein reicht nicht.' },
      { was: 'Ausgefülltes Anmeldeformular der Gemeinde', pflicht: true, hinweis: 'Meist vor Ort erhältlich oder online vorab ausfüllbar.' },
      { was: 'Heiratsurkunde oder Geburtsurkunden', pflicht: false, hinweis: 'Nur beim erstmaligen Zuzug nach Deutschland oder bei erstmaliger Erfassung von Familienstand und Kindern.' },
      { was: 'Schriftliche Vollmacht und Ausweiskopie der vertretenen Person', pflicht: false, hinweis: 'Nur bei Vertretung. Der Ausweis der vertretenen Person muss im Original vorgelegt werden, damit die Adresse überklebt werden kann.' },
    ],
    gebuehren: [
      { position: 'An- und Ummeldung', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Die Meldung selbst ist gebührenfrei.' },
      { position: 'Zusätzliche Meldebescheinigung', betrag: 'etwa 5 bis 15 Euro', art: 'kommunal', hinweis: 'Nur wenn Sie eine gesonderte Bescheinigung wünschen. Eine einfache Anmeldebestätigung erhalten Sie kostenfrei.' },
      { position: 'Verspätungsbußgeld', betrag: 'bis 1.000 Euro', art: 'bundeseinheitlich', hinweis: 'Ordnungswidrigkeit nach § 54 BMG. In der Praxis werden bei kurzer Überschreitung meist 5 bis 40 Euro erhoben oder es bleibt bei einer Ermahnung.' },
    ],
    fristen: [
      'Anmeldung: innerhalb von zwei Wochen nach dem Einzug (§ 17 Abs. 1 BMG).',
      'Wohnungsgeberbestätigung: der Wohnungsgeber muss sie innerhalb von zwei Wochen nach Einzug ausstellen.',
      'Statuswechsel zwischen Haupt- und Nebenwohnung: ebenfalls innerhalb von zwei Wochen anzuzeigen.',
    ],
    bearbeitungsdauer: 'Die Anmeldung erfolgt während des Termins sofort. Die Adressänderung im Ausweis wird direkt aufgebracht, die Anmeldebestätigung erhalten Sie mit.',
    ablauf: [
      { nr: 1, titel: 'Wohnungsgeberbestätigung anfordern', detail: 'Bitten Sie Vermieter oder Hausverwaltung um die Bestätigung nach § 19 BMG. Sie enthält Name und Anschrift des Wohnungsgebers, Einzugsdatum, Anschrift der Wohnung und die Namen aller einziehenden Personen. Wer selbst Eigentümer ist, bestätigt sich den Einzug selbst.', akteur: 'Bürger' },
      { nr: 2, titel: 'Termin vereinbaren', detail: 'In den meisten Städten ist ein Online-Termin nötig. Buchen Sie früh - in Ballungsräumen liegen Wartezeiten bei mehreren Wochen. Viele Kommunen halten Notfall- und Spontankontingente frei, die morgens freigeschaltet werden.', akteur: 'Bürger' },
      { nr: 3, titel: 'Formular ausfüllen', detail: 'Das Meldeformular erfasst alle Personen des Haushalts, Familienstand, Religionszugehörigkeit für die Kirchensteuer und die bisherige Anschrift.', akteur: 'Bürger' },
      { nr: 4, titel: 'Persönlich vorsprechen', detail: 'Alle volljährigen Personen melden sich grundsätzlich selbst an; eine volljährige Person kann die übrigen mit Vollmacht vertreten. Kinder werden von einem Sorgeberechtigten angemeldet.', akteur: 'Bürger' },
      { nr: 5, titel: 'Datenabgleich und Eintragung', detail: 'Die Meldebehörde gleicht Ihre Angaben mit dem Melderegister ab, übermittelt die Daten an die bisherige Gemeinde und aktualisiert das Register.', akteur: 'Behörde' },
      { nr: 6, titel: 'Adressaufkleber und Bestätigung', detail: 'Auf Personalausweis und Reisepass wird die neue Anschrift aufgebracht, im Chip des Ausweises wird die Adresse elektronisch aktualisiert. Sie erhalten eine Anmeldebestätigung.', akteur: 'Behörde' },
      { nr: 7, titel: 'Folgemeldungen erledigen', detail: 'Denken Sie an Kfz-Ummeldung, Rundfunkbeitrag, Finanzamt, Bank, Versicherungen, Arbeitgeber und gegebenenfalls die Ausländerbehörde. Die Meldebehörde informiert nur andere Behörden im Rahmen der Datenübermittlungsverordnungen, nicht private Stellen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 17 Bundesmeldegesetz - Anmeldung, Abmeldung',
      '§ 19 Bundesmeldegesetz - Mitwirkung des Wohnungsgebers',
      '§ 21, 22 Bundesmeldegesetz - Haupt- und Nebenwohnung',
      '§ 54 Bundesmeldegesetz - Bußgeldvorschriften',
    ],
    online: {
      moeglich: true,
      hinweis: 'Die elektronische Wohnsitzanmeldung ist seit 2023 bundesweit ausgerollt, aber noch nicht in allen Kommunen aktiv. Sie funktioniert nur beim Umzug innerhalb Deutschlands und nur, wenn der Wohnungsgeber die Bestätigung digital hinterlegt hat. Die Adresse im Ausweischip wird dabei selbst per Smartphone überschrieben, der Adressaufkleber kommt per Post.',
      voraussetzungen: ['Online-Ausweisfunktion mit PIN', 'BundID-Konto', 'NFC-fähiges Smartphone mit AusweisApp', 'Digitale Wohnungsgeberbestätigung'],
    },
    haeufigeFehler: [
      'Mietvertrag statt Wohnungsgeberbestätigung mitbringen - der Mietvertrag wird nicht akzeptiert.',
      'Zu spät anmelden und die Zwei-Wochen-Frist verstreichen lassen.',
      'Vergessen, Kinder mit anzumelden - sie brauchen eigene Einträge.',
      'Bei Vertretung den Ausweis der vertretenen Person nicht mitbringen, sodass die Adresse nicht geändert werden kann.',
      'Annehmen, der Nebenwohnsitz sei kostenlos - viele Städte erheben Zweitwohnungsteuer.',
    ],
    faq: [
      { frage: 'Muss ich mich am alten Wohnort abmelden?', antwort: 'Innerhalb Deutschlands nein. Die neue Meldebehörde informiert die alte automatisch. Abgemeldet wird nur bei Wegzug ins Ausland oder wenn eine Nebenwohnung aufgegeben wird.' },
      { frage: 'Ich ziehe nur in eine andere Wohnung derselben Stadt - muss ich trotzdem etwas tun?', antwort: 'Ja, das ist eine Ummeldung und ebenfalls binnen zwei Wochen erforderlich.' },
      { frage: 'Ich wohne vorübergehend bei Freunden. Muss ich mich anmelden?', antwort: 'Bei einem Aufenthalt bis zu sechs Monaten in einer bereits gemeldeten Wohnung entfällt die Meldepflicht nach § 27 BMG, wenn Sie im Inland gemeldet bleiben. Danach besteht Meldepflicht.' },
      { frage: 'Was ist, wenn mein Vermieter die Bestätigung nicht ausstellt?', antwort: 'Er ist dazu gesetzlich verpflichtet und begeht sonst eine Ordnungswidrigkeit. Melden Sie das der Meldebehörde - sie kann den Wohnungsgeber auffordern und ein Bußgeld verhängen.' },
      { frage: 'Zählt ein Wohnwagen oder Boot als Wohnung?', antwort: 'Nach § 20 BMG nur, wenn er nicht oder nur gelegentlich fortbewegt wird. Dauerhaft genutzte Mobilheime auf festem Stellplatz sind meldepflichtige Wohnungen.' },
    ],
    verwandt: ['wohnsitz-abmeldung', 'meldebescheinigung', 'wohnungsgeberbestaetigung', 'kfz-ummeldung', 'zweitwohnungsteuer'],
    eskalation: 'Bei ungeklärter Wohnsitzlage im Ausland, bei Scheinanmeldungen, bei Obdachlosigkeit ohne feste Anschrift oder bei Konflikten mit dem Wohnungsgeber an einen Sachbearbeiter des Bürgeramts weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Fristen und Pflichten regelt bundeseinheitlich das Bundesmeldegesetz. Nur Gebühren für zusätzliche Bescheinigungen und die Terminorganisation sind kommunal unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'wohnsitz-abmeldung',
    cluster: 'melde-ausweis',
    name: 'Wohnsitz abmelden',
    sprechName: 'Wohnsitz abmelden',
    synonyme: ['abmelden', 'abmeldung', 'ins ausland ziehen', 'auswandern', 'auswanderung', 'nebenwohnung abmelden', 'zweitwohnsitz abmelden', 'deutschland verlassen', 'wegzug'],
    leikaBezug: 'Abmeldung einer Wohnung (LeiKa 99083020)',
    kurzbeschreibung: 'Eine Abmeldung ist nur in zwei Fällen nötig: beim Wegzug ins Ausland ohne Wohnung in Deutschland und bei Aufgabe einer Neben- oder Zweitwohnung. Bei einem Umzug innerhalb Deutschlands genügt die Anmeldung am neuen Ort.',
    zustaendigkeit: {
      stelle: 'Bürgeramt der Gemeinde, in der die aufzugebende Wohnung liegt',
      ebene: 'kommunal',
      hinweis: 'Bei Nebenwohnungen ist die Gemeinde der Nebenwohnung zuständig, nicht die des Hauptwohnsitzes.',
    },
    voraussetzungen: [
      'Sie geben eine Wohnung auf und beziehen keine neue Wohnung in Deutschland - oder Sie geben eine Nebenwohnung auf.',
      'Der Auszug steht unmittelbar bevor oder ist erfolgt.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Abmeldeformular', pflicht: true, hinweis: 'Bei den meisten Gemeinden auch als Download und per Post oder Fax einreichbar.' },
      { was: 'Vollmacht bei Vertretung', pflicht: false },
    ],
    gebuehren: [
      { position: 'Abmeldung', betrag: '0,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Abmeldebestätigung', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Wird auf Verlangen gebührenfrei ausgestellt und ist für viele Auslandsbehörden und für die Beendigung des Rundfunkbeitrags wichtig.' },
    ],
    fristen: [
      'Frühestens eine Woche vor dem Auszug möglich.',
      'Spätestens zwei Wochen nach dem Auszug erforderlich (§ 17 Abs. 2 BMG).',
    ],
    bearbeitungsdauer: 'Sofort bei Vorsprache; bei schriftlicher Abmeldung wenige Tage bis zum Erhalt der Bestätigung.',
    ablauf: [
      { nr: 1, titel: 'Abmeldegrund prüfen', detail: 'Klären Sie zuerst, ob überhaupt abgemeldet werden muss. Ziehen Sie innerhalb Deutschlands um, melden Sie sich nur am neuen Ort an.', akteur: 'Bürger' },
      { nr: 2, titel: 'Formular ausfüllen', detail: 'Angaben zur bisherigen Wohnung, zum Auszugsdatum und zur künftigen Auslandsanschrift, soweit bekannt.', akteur: 'Bürger' },
      { nr: 3, titel: 'Abmeldung einreichen', detail: 'Persönlich, schriftlich per Post oder in vielen Kommunen online. Für die schriftliche Abmeldung ist eine Ausweiskopie beizufügen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Abmeldebestätigung erhalten', detail: 'Bewahren Sie sie auf. Sie wird für Rundfunkbeitrag, Versicherungen und viele ausländische Behörden verlangt.', akteur: 'Behörde' },
      { nr: 5, titel: 'Folgeschritte beim Wegzug ins Ausland', detail: 'Rundfunkbeitrag kündigen, Steuerpflicht mit dem Finanzamt klären, Krankenversicherung informieren, gegebenenfalls Nachsendeauftrag einrichten und Konsulat des Ziellandes kontaktieren.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 17 Abs. 2 Bundesmeldegesetz - Abmeldepflicht',
      '§ 18 Bundesmeldegesetz - Meldebestätigung',
      '§ 21 Bundesmeldegesetz - Mehrere Wohnungen',
    ],
    online: {
      moeglich: true,
      hinweis: 'Die Abmeldung ins Ausland und die Abmeldung einer Nebenwohnung sind in vielen Kommunen online oder schriftlich möglich, da keine Ausweisänderung nötig ist.',
      voraussetzungen: ['Ausweiskopie oder eID je nach Kommune'],
    },
    haeufigeFehler: [
      'Sich beim Umzug innerhalb Deutschlands unnötig abmelden - das kann zu Lücken im Melderegister führen.',
      'Die Abmeldebestätigung nicht anfordern und später für Rundfunkbeitrag oder Auslandsbehörde nachweisen müssen.',
      'Vergessen, dass bei Aufgabe der Hauptwohnung mit verbleibender Nebenwohnung diese automatisch zur Hauptwohnung wird und umzumelden ist.',
    ],
    faq: [
      { frage: 'Ich ziehe für ein Jahr ins Ausland und behalte meine Wohnung. Muss ich mich abmelden?', antwort: 'Nein. Solange Sie eine Wohnung in Deutschland behalten und beibehalten wollen, bleibt die Meldung bestehen.' },
      { frage: 'Was passiert mit dem Rundfunkbeitrag?', antwort: 'Er endet nicht automatisch. Kündigen Sie beim Beitragsservice unter Vorlage der Abmeldebestätigung.' },
      { frage: 'Kann ich mich rückwirkend abmelden?', antwort: 'Ja, bis zu zwei Wochen nach dem Auszug ist das der Normalfall. Deutlich spätere Abmeldungen werden akzeptiert, können aber als Ordnungswidrigkeit gewertet werden.' },
    ],
    verwandt: ['wohnsitz-anmeldung', 'meldebescheinigung', 'zweitwohnungsteuer'],
    eskalation: 'Bei ungeklärtem Verbleib, bei Abmeldung von Amts wegen oder bei laufenden Sozialleistungen an das Bürgeramt weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundeseinheitlich geregelt im Bundesmeldegesetz.' },
    stand: '2026-08',
  },
  {
    id: 'personalausweis',
    cluster: 'melde-ausweis',
    name: 'Personalausweis beantragen',
    sprechName: 'Personalausweis beantragen',
    synonyme: ['perso', 'personalausweis', 'ausweis beantragen', 'neuer ausweis', 'ausweis abgelaufen', 'ausweis verlängern', 'ausweis erneuern', 'identitätskarte', 'ausweis für kind'],
    leikaBezug: 'Personalausweis - Ausstellung (LeiKa 99011001)',
    kurzbeschreibung: 'Alle Deutschen ab 16 Jahren müssen einen gültigen Personalausweis oder Reisepass besitzen. Der Ausweis wird persönlich bei der Personalausweisbehörde beantragt und in der Bundesdruckerei hergestellt. Er enthält die Online-Ausweisfunktion.',
    zustaendigkeit: {
      stelle: 'Bürgeramt oder Personalausweisbehörde am Hauptwohnsitz',
      ebene: 'kommunal',
      hinweis: 'Aus wichtigem Grund - etwa Studium oder Arbeit an einem anderen Ort - kann auch eine andere Behörde tätig werden; dafür fällt eine Unzuständigkeitsgebühr von 13 Euro an.',
    },
    voraussetzungen: [
      'Deutsche Staatsangehörigkeit.',
      'Persönliches Erscheinen zur Abgabe von Lichtbild, Unterschrift und zwei Fingerabdrücken - die Fingerabdrücke sind seit dem 2. August 2021 verpflichtend.',
      'Bei Personen unter 16 Jahren: Einwilligung aller Sorgeberechtigten.',
      'Ausweispflicht besteht ab dem 16. Geburtstag; jüngere Kinder können freiwillig einen Ausweis erhalten.',
    ],
    unterlagen: [
      { was: 'Bisheriger Personalausweis oder Reisepass', pflicht: true, hinweis: 'Bei Erstbeantragung stattdessen eine beglaubigte Geburtsurkunde oder Abstammungsurkunde.' },
      { was: 'Aktuelles biometrisches Lichtbild', pflicht: true, hinweis: 'Seit 1. Mai 2025 nur noch in digitaler Form: entweder im Fotostudio erstellt und über einen sicheren Übertragungsweg gesendet oder direkt am Selbstbedienungsterminal der Behörde aufgenommen. Papierfotos werden nicht mehr angenommen.' },
      { was: 'Bei Namensänderung: Heirats-, Scheidungs- oder Namensänderungsurkunde', pflicht: false },
      { was: 'Bei Verlust: Verlustanzeige oder polizeiliche Bescheinigung', pflicht: false },
      { was: 'Bei Minderjährigen: Einwilligung und Ausweise beider Sorgeberechtigten sowie Geburtsurkunde', pflicht: false },
    ],
    gebuehren: [
      { position: 'Personalausweis ab 24 Jahren, Gültigkeit 10 Jahre', betrag: '37,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Personalausweis unter 24 Jahren, Gültigkeit 6 Jahre', betrag: '22,80 Euro', art: 'bundeseinheitlich' },
      { position: 'Express-Herstellung', betrag: '32,00 Euro zusätzlich', art: 'bundeseinheitlich', hinweis: 'Produktion in der Regel binnen drei bis vier Werktagen. Abholung dennoch nur bei der Behörde, sofern kein Direktversand gewählt wird.' },
      { position: 'Direktversand nach Hause', betrag: '15,00 Euro zusätzlich', art: 'bundeseinheitlich', hinweis: 'Nicht in allen Kommunen angeboten.' },
      { position: 'Vorläufiger Personalausweis', betrag: '10,00 Euro', art: 'bundeseinheitlich', hinweis: 'Sofort gültig, maximal drei Monate, ohne Online-Ausweisfunktion, für Reisen nur eingeschränkt anerkannt.' },
      { position: 'Beantragung bei unzuständiger Behörde', betrag: '13,00 Euro zusätzlich', art: 'bundeseinheitlich' },
      { position: 'Ausstellung an Personen unter 24 mit Wohnsitz im Ausland oder Sonderfälle', betrag: 'abweichend', art: 'bundeseinheitlich', hinweis: 'Bei Auslandsvertretungen gelten höhere Sätze nach der Auslandskostenverordnung.' },
    ],
    fristen: [
      'Es gibt keine gesetzliche Frist zur Beantragung, aber eine Ausweispflicht ab 16 Jahren: Sie müssen jederzeit ein gültiges Dokument besitzen.',
      'Beantragen Sie rechtzeitig etwa sechs bis acht Wochen vor Ablauf, in Ferienzeiten früher.',
      'Verlust ist unverzüglich anzuzeigen.',
      'Der fertige Ausweis muss binnen drei Monaten abgeholt werden, sonst wird er vernichtet.',
    ],
    bearbeitungsdauer: 'Regelfall drei bis sechs Wochen bis zur Abholbereitschaft. Express-Ausweise sind meist nach drei bis vier Werktagen bei der Behörde. Der vorläufige Ausweis wird sofort ausgestellt.',
    ablauf: [
      { nr: 1, titel: 'Digitales Lichtbild besorgen', detail: 'Lassen Sie im Fotostudio ein biometrisches Bild anfertigen und digital an die Behörde übermitteln, oder nutzen Sie das Fototerminal im Bürgeramt. Achten Sie auf neutrale Miene, frontale Kopfhaltung, gleichmäßige Ausleuchtung und keine Brillenreflexe.', akteur: 'Bürger' },
      { nr: 2, titel: 'Termin buchen', detail: 'Online-Terminvergabe der Kommune nutzen. Bringen Sie alle Unterlagen im Original mit.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag aufnehmen lassen', detail: 'Die Behörde erfasst Ihre Daten, nimmt zwei Fingerabdrücke, die Unterschrift und das Lichtbild auf. Sie entscheiden, ob die Online-Ausweisfunktion eingeschaltet bleibt - sie ist standardmäßig aktiv.', akteur: 'Behörde' },
      { nr: 4, titel: 'Gebühr zahlen', detail: 'Zahlung meist sofort, in vielen Ämtern nur mit Karte.', akteur: 'Bürger' },
      { nr: 5, titel: 'Herstellung in der Bundesdruckerei', detail: 'Der Ausweis wird zentral produziert. Der PIN-Brief mit der fünfstelligen Transport-PIN kommt separat per Post an Ihre Meldeadresse.', akteur: 'Behörde' },
      { nr: 6, titel: 'Abholen und aktivieren', detail: 'Abholung persönlich mit dem alten Dokument. Die Behörde entwertet den alten Ausweis. Setzen Sie anschließend die Transport-PIN in eine selbstgewählte sechsstellige PIN um - per AusweisApp oder direkt im Amt.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 1 Personalausweisgesetz - Ausweispflicht',
      '§ 5, 6 Personalausweisgesetz - Ausweismuster, Gültigkeitsdauer',
      '§ 9 Personalausweisgesetz - Fingerabdrücke',
      'Personalausweisverordnung (PAuswV)',
      'EU-Verordnung 2019/1157 über die Sicherheit der Personalausweise',
    ],
    online: {
      moeglich: false,
      hinweis: 'Die Erstbeantragung und jede Neuausstellung erfordern persönliches Erscheinen wegen Fingerabdrücken und Unterschrift. Online möglich sind nur Terminvereinbarung, Lichtbildübermittlung und in manchen Kommunen die Statusabfrage, ob der Ausweis abholbereit ist.',
    },
    haeufigeFehler: [
      'Papierfoto mitbringen - seit Mai 2025 nicht mehr zulässig.',
      'Den alten Ausweis zur Abholung vergessen - ohne Entwertung des alten Dokuments keine Aushändigung.',
      'Den PIN-Brief wegwerfen und später die Online-Ausweisfunktion nicht nutzen können.',
      'Bei Kindern nur mit einem Elternteil erscheinen, obwohl beide sorgeberechtigt sind - dann ist eine schriftliche Einwilligung des anderen nötig.',
      'Zu spät beantragen und kurz vor der Reise auf den teuren Expressweg angewiesen sein.',
    ],
    faq: [
      { frage: 'Ich brauche den Ausweis in drei Tagen. Was geht?', antwort: 'Zwei Wege: der Express-Personalausweis mit 32 Euro Zuschlag, produziert in etwa drei bis vier Werktagen, oder der vorläufige Personalausweis für 10 Euro, sofort im Amt ausgestellt, drei Monate gültig, aber nicht in allen Staaten als Reisedokument anerkannt.' },
      { frage: 'Kann mein Ausweis verlängert werden?', antwort: 'Nein. Personalausweise werden nicht verlängert, sondern immer neu ausgestellt.' },
      { frage: 'Brauchen Kinder einen Personalausweis?', antwort: 'Pflicht ab 16 Jahren. Jüngere Kinder können freiwillig einen erhalten - seit dem Wegfall des Kinderreisepasses zum 1. Januar 2024 ist das oft der günstigste Reiseausweis innerhalb der EU.' },
      { frage: 'Was kostet der Ausweis für einen 20-Jährigen?', antwort: '22,80 Euro, gültig sechs Jahre. Ab dem 24. Geburtstag kostet er 37,00 Euro und gilt zehn Jahre.' },
      { frage: 'Muss ich die Online-Ausweisfunktion nutzen?', antwort: 'Nein, aber seit 2017 ist sie bei allen neuen Ausweisen dauerhaft eingeschaltet. Sie können sie einfach ungenutzt lassen; abschalten ist nicht mehr vorgesehen.' },
    ],
    verwandt: ['reisepass', 'ausweis-verlust', 'eid-online-ausweisfunktion', 'wohnsitz-anmeldung'],
    eskalation: 'Bei Staatsangehörigkeitszweifeln, bei Namensfragen mit Auslandsbezug, bei Passversagungsgründen oder bei Sorgerechtsstreit über Kinderausweise an die Sachbearbeitung weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Gebühren und Verfahren sind bundeseinheitlich in der Personalausweisverordnung geregelt und gelten in jeder Kommune gleich.' },
    stand: '2026-08',
  },
  {
    id: 'reisepass',
    cluster: 'melde-ausweis',
    name: 'Reisepass beantragen',
    sprechName: 'Reisepass beantragen',
    synonyme: ['reisepass', 'pass', 'pässe', 'reisepässe', 'pass beantragen', 'passantrag', 'reisepass für kind', 'kinderreisepass', 'express pass', 'expresspass', 'pass abgelaufen', 'urlaub pass', 'reisedokument', 'pass für die reise'],
    leikaBezug: 'Reisepass - Ausstellung (LeiKa 99011014)',
    kurzbeschreibung: 'Der Reisepass ist das Reisedokument für Staaten außerhalb der EU. Er wird persönlich beantragt, enthält biometrische Merkmale und ist zehn Jahre gültig, bei Personen unter 24 Jahren sechs Jahre.',
    zustaendigkeit: {
      stelle: 'Bürgeramt oder Passbehörde am Hauptwohnsitz, im Ausland die deutsche Auslandsvertretung',
      ebene: 'kommunal',
      hinweis: 'Bei Beantragung außerhalb der Wohnsitzgemeinde fällt eine Unzuständigkeitsgebühr an; die Behörde kann die Bearbeitung zudem ablehnen.',
    },
    voraussetzungen: [
      'Deutsche Staatsangehörigkeit.',
      'Persönliches Erscheinen; Fingerabdrücke sind ab dem 6. Lebensjahr verpflichtend.',
      'Bei Minderjährigen: Einwilligung aller Sorgeberechtigten.',
      'Keine Passversagungsgründe nach § 7 PassG, etwa Entziehung wegen erheblicher Gefährdung innerer oder äußerer Belange.',
    ],
    unterlagen: [
      { was: 'Bisheriger Reisepass oder Personalausweis', pflicht: true },
      { was: 'Digitales biometrisches Lichtbild', pflicht: true, hinweis: 'Wie beim Personalausweis seit 1. Mai 2025 ausschließlich digital.' },
      { was: 'Geburtsurkunde bei Erstbeantragung', pflicht: false },
      { was: 'Urkunde bei Namensänderung', pflicht: false },
      { was: 'Bei Kindern: Geburtsurkunde und Einwilligung beider Sorgeberechtigten', pflicht: false },
    ],
    gebuehren: [
      { position: 'Reisepass ab 24 Jahren, 32 Seiten, 10 Jahre gültig', betrag: '70,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Reisepass unter 24 Jahren, 6 Jahre gültig', betrag: '37,50 Euro', art: 'bundeseinheitlich' },
      { position: 'Zusatzgebühr für 48 Seiten (Vielreisepass)', betrag: '22,00 Euro zusätzlich', art: 'bundeseinheitlich' },
      { position: 'Express-Reisepass', betrag: '32,00 Euro zusätzlich', art: 'bundeseinheitlich', hinweis: 'Herstellung in der Regel drei bis vier Werktage.' },
      { position: 'Vorläufiger Reisepass', betrag: '26,00 Euro', art: 'bundeseinheitlich', hinweis: 'Sofort im Amt ausgestellt, maximal ein Jahr gültig, ohne Chip. Die USA akzeptieren ihn nur mit Visum, da er nicht am Visa-Waiver-Programm teilnimmt.' },
      { position: 'Beantragung bei unzuständiger Behörde', betrag: '13,00 Euro zusätzlich', art: 'bundeseinheitlich' },
    ],
    fristen: [
      'Keine Antragsfrist, aber viele Zielstaaten verlangen eine Restgültigkeit von sechs Monaten über das Reiseende hinaus.',
      'Beantragung bei Ferienreisen mindestens acht Wochen vorher.',
      'Abholung binnen drei Monaten nach Fertigstellung.',
    ],
    bearbeitungsdauer: 'Drei bis sechs Wochen im Regelfall, in Hauptzeiten vor den Sommerferien länger. Express drei bis vier Werktage, vorläufiger Pass sofort.',
    ablauf: [
      { nr: 1, titel: 'Reiseziel und Passanforderungen prüfen', detail: 'Klären Sie Restgültigkeit, freie Seiten für Visa und ob ein elektronischer Pass verlangt wird. Die Reise- und Sicherheitshinweise des Auswärtigen Amts nennen die Anforderungen je Land.', akteur: 'Bürger' },
      { nr: 2, titel: 'Digitales Lichtbild erstellen lassen', detail: 'Fotostudio mit digitaler Übermittlung oder Terminal im Amt.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag persönlich stellen', detail: 'Erfassung von Lichtbild, Unterschrift und zwei Fingerabdrücken. Entscheiden Sie über 32 oder 48 Seiten und über Express.', akteur: 'Bürger' },
      { nr: 4, titel: 'Herstellung und Prüfung', detail: 'Die Bundesdruckerei produziert den Pass. Die Behörde prüft vorab Identität und Staatsangehörigkeit.', akteur: 'Behörde' },
      { nr: 5, titel: 'Abholen', detail: 'Persönlich mit dem alten Pass. Bei Kindern ist die Abholung durch einen Sorgeberechtigten möglich.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 1 Passgesetz - Passpflicht',
      '§ 4, 5 Passgesetz - Passmuster und Gültigkeitsdauer',
      '§ 7 Passgesetz - Passversagung',
      'Passverordnung (PassV) und Auslandskostenverordnung',
    ],
    online: {
      moeglich: false,
      hinweis: 'Persönliche Vorsprache ist zwingend. Online möglich sind Terminvergabe, Lichtbildübermittlung und teilweise die Abfrage des Bearbeitungsstands.',
    },
    haeufigeFehler: [
      'Erst kurz vor der Reise beantragen.',
      'Restgültigkeit des Passes für das Zielland nicht prüfen.',
      'Für die USA einen vorläufigen Reisepass beantragen - damit entfällt die visumfreie Einreise.',
      'Bei Kindern annehmen, es gäbe noch den Kinderreisepass - er wurde zum 1. Januar 2024 abgeschafft.',
      'Vergessen, dass ein Reisepass den Personalausweis nicht ersetzt: die Ausweispflicht verlangt nur eines von beiden, für die Online-Ausweisfunktion braucht es aber den Personalausweis.',
    ],
    faq: [
      { frage: 'Was gilt für Kinder seit dem Wegfall des Kinderreisepasses?', antwort: 'Kinder brauchen einen eigenen elektronischen Reisepass für 37,50 Euro, sechs Jahre gültig, oder für Reisen innerhalb der EU und in viele europäische Staaten einen Personalausweis für 22,80 Euro. Alte Kinderreisepässe bleiben bis zum aufgedruckten Ablaufdatum gültig, werden aber nicht mehr verlängert.' },
      { frage: 'Reicht der Personalausweis für den Urlaub?', antwort: 'Für die EU, den Schengenraum und einige weitere europäische Staaten wie die Türkei bei Pauschalreisen ja. Für die meisten Fernziele brauchen Sie den Reisepass.' },
      { frage: 'Ich habe den Pass verloren, die Reise ist morgen.', antwort: 'Verlust anzeigen, dann vorläufigen Reisepass beantragen - er wird sofort ausgestellt. Prüfen Sie, ob das Zielland ihn akzeptiert.' },
      { frage: 'Kann ich beide Dokumente gleichzeitig beantragen?', antwort: 'Ja, Personalausweis und Reisepass im selben Termin. Das Lichtbild kann für beide verwendet werden.' },
    ],
    verwandt: ['personalausweis', 'ausweis-verlust', 'meldebescheinigung'],
    eskalation: 'Bei Passversagungsgründen, Doppelstaatlern, Namensführung nach ausländischem Recht oder Zweifeln an der Staatsangehörigkeit an die Passbehörde weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Passgebühren sind bundeseinheitlich; nur die Terminvergabe unterscheidet sich kommunal.' },
    stand: '2026-08',
  },
  {
    id: 'ausweis-verlust',
    cluster: 'melde-ausweis',
    name: 'Verlust oder Diebstahl von Ausweis und Pass melden',
    sprechName: 'Verlust von Ausweis oder Pass melden',
    synonyme: ['ausweis verloren', 'pass verloren', 'ausweis gestohlen', 'pass gestohlen', 'verlustanzeige', 'ausweis weg', 'dokument verloren', 'sperren ausweis'],
    leikaBezug: 'Personalausweis - Verlustanzeige (LeiKa 99011001)',
    kurzbeschreibung: 'Der Verlust eines Ausweisdokuments ist unverzüglich der Ausweisbehörde anzuzeigen. Die Online-Ausweisfunktion wird gesperrt und ein neues Dokument beantragt. Bei Diebstahl kommt die Anzeige bei der Polizei hinzu.',
    zustaendigkeit: {
      stelle: 'Ausweis- oder Passbehörde am Hauptwohnsitz; bei Diebstahl zusätzlich jede Polizeidienststelle; im Ausland die deutsche Auslandsvertretung',
      ebene: 'kommunal',
      hinweis: 'Die Sperrung der Online-Ausweisfunktion ist rund um die Uhr über die Sperrhotline 116 116 möglich.',
    },
    voraussetzungen: [
      'Sie können Angaben zum verlorenen Dokument machen: Art, möglichst Nummer, Zeitpunkt und Umstände des Verlusts.',
      'Persönliches Erscheinen für die Neuausstellung.',
    ],
    unterlagen: [
      { was: 'Ein anderes Ausweisdokument zur Identitätsfeststellung', pflicht: false, hinweis: 'Ist keines vorhanden, kann eine Geburtsurkunde oder ein Zeuge helfen; die Behörde ermittelt anhand des Registers.' },
      { was: 'Polizeiliche Anzeigebestätigung bei Diebstahl', pflicht: false, hinweis: 'Dringend empfohlen, weil sie bei Identitätsmissbrauch entlastet.' },
      { was: 'Digitales biometrisches Lichtbild für das Ersatzdokument', pflicht: true },
    ],
    gebuehren: [
      { position: 'Verlustanzeige und Sperrung', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Die Sperrung über 116 116 ist ebenfalls kostenfrei.' },
      { position: 'Neuausstellung Personalausweis', betrag: '37,00 Euro beziehungsweise 22,80 Euro unter 24 Jahren', art: 'bundeseinheitlich' },
      { position: 'Neuausstellung Reisepass', betrag: '70,00 Euro beziehungsweise 37,50 Euro unter 24 Jahren', art: 'bundeseinheitlich' },
      { position: 'Wiederholter Verlust', betrag: 'Zuschlag möglich', art: 'kommunal', hinweis: 'Manche Behörden erheben bei mehrfachem Verlust eine erhöhte Gebühr wegen erhöhten Verwaltungsaufwands.' },
    ],
    fristen: [
      'Unverzüglich, das heißt ohne schuldhaftes Zögern.',
      'Taucht das Dokument wieder auf, ist auch das der Behörde zu melden - ein einmal als verloren gemeldeter Ausweis bleibt jedoch ungültig und ist abzugeben.',
    ],
    bearbeitungsdauer: 'Sperrung sofort. Ersatzdokument wie bei der Neubeantragung, drei bis sechs Wochen, Express drei bis vier Werktage, vorläufiges Dokument sofort.',
    ablauf: [
      { nr: 1, titel: 'Online-Ausweisfunktion sofort sperren', detail: 'Rufen Sie die Sperrhotline 116 116 an - kostenfrei, rund um die Uhr. Sie brauchen dafür das Sperrkennwort aus dem PIN-Brief oder Ihre persönlichen Daten.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bei Diebstahl Anzeige erstatten', detail: 'Polizeiliche Anzeige, auch online über die Internetwache der Länder möglich. Die Bestätigung schützt Sie, wenn mit dem Dokument Verträge geschlossen werden.', akteur: 'Bürger' },
      { nr: 3, titel: 'Verlust der Ausweisbehörde anzeigen', detail: 'Das Dokument wird zur Sachfahndung ausgeschrieben und im Register als ungültig geführt.', akteur: 'Bürger' },
      { nr: 4, titel: 'Ersatzdokument beantragen', detail: 'Im selben Termin. Bei dringendem Reisebedarf vorläufiges Dokument verlangen.', akteur: 'Bürger' },
      { nr: 5, titel: 'Weitere Stellen informieren', detail: 'Bank, Arbeitgeber und Vermieter informieren, wenn im Dokument weitere Unterlagen steckten. Bei Verdacht auf Identitätsmissbrauch eine Selbstauskunft bei der SCHUFA einholen.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 27 Personalausweisgesetz - Anzeigepflicht bei Verlust',
      '§ 15 Passgesetz - Verlust und Abhandenkommen',
      '§ 10 Abs. 5 Personalausweisgesetz - Sperrung des elektronischen Identitätsnachweises',
    ],
    online: {
      moeglich: true,
      hinweis: 'Die Sperrung der eID ist telefonisch über 116 116 und teilweise online möglich; einige Kommunen bieten die Verlustanzeige als Online-Formular an. Das Ersatzdokument erfordert dennoch persönliches Erscheinen.',
    },
    haeufigeFehler: [
      'Nur zur Polizei gehen und die Ausweisbehörde nicht informieren.',
      'Die Sperrung der Online-Ausweisfunktion vergessen.',
      'Ein wiedergefundenes Dokument weiterverwenden - es ist ungültig.',
      'Bei geplanter Reise zu spät reagieren und den vorläufigen Pass nicht mehr rechtzeitig bekommen.',
    ],
    faq: [
      { frage: 'Was kostet die Sperrung?', antwort: 'Nichts. Sowohl die Sperrhotline 116 116 als auch die Anzeige bei der Behörde sind kostenfrei.' },
      { frage: 'Ich habe den Ausweis wiedergefunden - kann ich die Neubeantragung stoppen?', antwort: 'Nur solange das neue Dokument noch nicht in Produktion ist. Der als verloren gemeldete Ausweis bleibt in jedem Fall ungültig.' },
      { frage: 'Verlust im Ausland - was tun?', antwort: 'Deutsche Botschaft oder Konsulat kontaktieren. Dort erhalten Sie einen Reiseausweis als Passersatz, meist für die direkte Rückreise.' },
    ],
    verwandt: ['personalausweis', 'reisepass', 'eid-online-ausweisfunktion'],
    eskalation: 'Bei Verdacht auf Identitätsmissbrauch, bei Verlust im Ausland oder bei fehlender Identitätsfeststellung an die Sachbearbeitung oder Polizei weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundeseinheitlich; nur Zuschläge bei wiederholtem Verlust sind kommunal unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'meldebescheinigung',
    cluster: 'melde-ausweis',
    name: 'Meldebescheinigung beantragen',
    sprechName: 'Meldebescheinigung beantragen',
    synonyme: ['meldebescheinigung', 'meldebestätigung', 'wohnsitzbescheinigung', 'aufenthaltsbescheinigung', 'nachweis wohnsitz', 'erweiterte meldebescheinigung', 'lebensbescheinigung'],
    leikaBezug: 'Meldebescheinigung - Ausstellung (LeiKa 99083016)',
    kurzbeschreibung: 'Die Meldebescheinigung weist amtlich nach, dass und seit wann Sie an einer bestimmten Anschrift gemeldet sind. Sie wird für Eheschließungen, Bankgeschäfte, Gerichte, Rentenanträge oder ausländische Behörden verlangt.',
    zustaendigkeit: {
      stelle: 'Bürgeramt oder Meldebehörde des Wohnorts',
      ebene: 'kommunal',
      hinweis: 'Ausgestellt werden kann nur für die eigene Person oder mit Vollmacht; für Kinder durch die Sorgeberechtigten.',
    },
    voraussetzungen: [
      'Sie sind in der Gemeinde gemeldet.',
      'Identitätsnachweis oder Vollmacht bei Vertretung.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Vollmacht und Ausweiskopie bei Vertretung', pflicht: false },
      { was: 'Angabe des Verwendungszwecks', pflicht: false, hinweis: 'Für manche Zwecke - Eheschließung, Rente - ist die erweiterte Bescheinigung mit Familienstand und Staatsangehörigkeit nötig.' },
    ],
    gebuehren: [
      { position: 'Einfache Meldebescheinigung', betrag: 'etwa 5 bis 12 Euro', art: 'kommunal' },
      { position: 'Erweiterte Meldebescheinigung', betrag: 'etwa 8 bis 15 Euro', art: 'kommunal' },
      { position: 'Bescheinigung für Rentenzwecke oder Eheschließung', betrag: 'häufig gebührenfrei', art: 'kommunal', hinweis: 'Viele Gebührensatzungen sehen Befreiungen für bestimmte Zwecke vor - fragen Sie danach.' },
    ],
    fristen: ['Keine Frist. Empfänger verlangen häufig eine Bescheinigung, die nicht älter als drei oder sechs Monate ist.'],
    bearbeitungsdauer: 'Sofort bei Vorsprache, bei schriftlicher oder Online-Beantragung meist zwei bis fünf Werktage per Post.',
    ablauf: [
      { nr: 1, titel: 'Art der Bescheinigung klären', detail: 'Einfache Bescheinigung enthält Name, Geburtsdatum, Anschriften und Einzugsdatum. Die erweiterte enthält zusätzlich Familienstand, Staatsangehörigkeit, Religionszugehörigkeit und Angaben zu Ehegatten und Kindern.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag stellen', detail: 'Vor Ort, schriftlich oder über das kommunale Serviceportal.', akteur: 'Bürger' },
      { nr: 3, titel: 'Gebühr entrichten', detail: 'Bei Online-Anträgen meist per Kartenzahlung oder Lastschrift.', akteur: 'Bürger' },
      { nr: 4, titel: 'Bescheinigung erhalten', detail: 'Ausdruck mit Siegel und Unterschrift; für das Ausland gegebenenfalls mit Apostille oder Übersetzung.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 18 Bundesmeldegesetz - Melde- und Aufenthaltsbescheinigung',
      '§ 44 ff. Bundesmeldegesetz - Melderegisterauskunft',
      'Kommunale Gebührensatzungen',
    ],
    online: {
      moeglich: true,
      hinweis: 'In vielen Kommunen über das Serviceportal mit eID oder BundID; Versand per Post oder als elektronisches Dokument mit qualifizierter Signatur.',
      voraussetzungen: ['Online-Ausweisfunktion oder Konto im Serviceportal'],
    },
    haeufigeFehler: [
      'Die einfache statt der erweiterten Bescheinigung holen und dafür ein zweites Mal kommen müssen.',
      'Nicht nach der Gebührenbefreiung für Renten- und Eheschließungszwecke fragen.',
      'Für Auslandszwecke die Apostille vergessen.',
    ],
    faq: [
      { frage: 'Was ist der Unterschied zur Anmeldebestätigung?', antwort: 'Die Anmeldebestätigung erhalten Sie kostenfrei bei der Anmeldung und dokumentiert nur diesen Vorgang. Die Meldebescheinigung ist eine eigenständige, gebührenpflichtige Urkunde über den aktuellen Meldestatus.' },
      { frage: 'Kann ich eine Bescheinigung über frühere Wohnsitze bekommen?', antwort: 'Ja, als erweiterte Bescheinigung oder als historische Auskunft aus dem Melderegister, soweit die Daten noch gespeichert sind.' },
    ],
    verwandt: ['wohnsitz-anmeldung', 'auskunftssperre', 'fuehrungszeugnis'],
    eskalation: 'Bei Auskunftssperren, bei Bescheinigungen über Dritte oder bei Anforderungen ausländischer Behörden an die Sachbearbeitung weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Der Inhalt ist bundesrechtlich vorgegeben, die Gebühr setzt jede Kommune selbst fest. Nennen Sie Beträge daher immer als Richtwert.' },
    stand: '2026-08',
  },
  {
    id: 'fuehrungszeugnis',
    cluster: 'melde-ausweis',
    name: 'Führungszeugnis beantragen',
    sprechName: 'Führungszeugnis beantragen',
    synonyme: ['führungszeugnis', 'polizeiliches führungszeugnis', 'erweitertes führungszeugnis', 'straffreiheit', 'vorstrafen', 'bundeszentralregister', 'zeugnis für arbeitgeber', 'belegart o', 'belegart n'],
    leikaBezug: 'Führungszeugnis - Beantragung (LeiKa 99026001)',
    kurzbeschreibung: 'Das Führungszeugnis ist ein Auszug aus dem Bundeszentralregister über strafrechtliche Verurteilungen. Es wird beim Bürgeramt oder online beim Bundesamt für Justiz beantragt und je nach Belegart an die Privatperson oder direkt an eine Behörde geschickt.',
    zustaendigkeit: {
      stelle: 'Bürgeramt der Wohnsitzgemeinde als Antragsstelle, ausgestellt vom Bundesamt für Justiz in Bonn',
      ebene: 'bund',
      hinweis: 'Die Kommune nimmt nur den Antrag entgegen; Inhalt und Versand verantwortet das Bundesamt für Justiz.',
    },
    voraussetzungen: [
      'Sie sind mindestens 14 Jahre alt.',
      'Sie beantragen das Zeugnis für sich selbst - Führungszeugnisse über Dritte gibt es nicht.',
      'Für ein erweitertes Führungszeugnis brauchen Sie eine schriftliche Aufforderung der Stelle, die es verlangt, mit Hinweis auf § 30a BZRG.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass mit Meldebescheinigung', pflicht: true },
      { was: 'Bei erweitertem Führungszeugnis: schriftliche Aufforderung des Trägers', pflicht: false, hinweis: 'Muss den Zweck nennen, etwa ehrenamtliche oder berufliche Tätigkeit mit Kindern und Jugendlichen.' },
      { was: 'Bei Belegart O: vollständige Anschrift der empfangenden Behörde und Verwendungszweck', pflicht: false },
    ],
    gebuehren: [
      { position: 'Führungszeugnis jeder Art', betrag: '13,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Gebührenbefreiung bei Ehrenamt', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Für unentgeltliche ehrenamtliche Tätigkeit auf Antrag; die Bestätigung des Vereins ist beizufügen. Die Befreiung erteilt das Bundesamt für Justiz.' },
    ],
    fristen: [
      'Keine Antragsfrist. Empfänger verlangen meist ein Zeugnis, das bei Vorlage nicht älter als drei Monate ist.',
      'Widerspruch gegen den Inhalt ist binnen eines Monats beim Bundesamt für Justiz möglich.',
    ],
    bearbeitungsdauer: 'Im Regelfall ein bis zwei Wochen bis zur Zustellung, bei Online-Antrag oft schneller. Bei Auslandsbezug oder Registerprüfung bis zu vier Wochen.',
    ablauf: [
      { nr: 1, titel: 'Belegart bestimmen', detail: 'Belegart N ist das einfache Zeugnis für Privatpersonen und Arbeitgeber. Belegart O geht direkt an eine Behörde. Belegart P ist das erweiterte Zeugnis für Behörden, Belegart PE das erweiterte für Privatpersonen bei Tätigkeit mit Minderjährigen.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag stellen', detail: 'Online beim Bundesamt für Justiz mit Online-Ausweisfunktion oder persönlich im Bürgeramt.', akteur: 'Bürger' },
      { nr: 3, titel: 'Gebühr zahlen', detail: 'Online per Kartenzahlung, im Amt bar oder mit Karte.', akteur: 'Bürger' },
      { nr: 4, titel: 'Registerabgleich', detail: 'Das Bundesamt für Justiz prüft die Eintragungen im Bundeszentralregister und wendet die Tilgungs- und Aufnahmefristen an.', akteur: 'Behörde' },
      { nr: 5, titel: 'Zustellung', detail: 'Bei Belegart N per Post an Ihre Meldeadresse. Bei Belegart O direkt an die Behörde - Sie können vorab Einsicht bei einem Amtsgericht verlangen.', akteur: 'Behörde' },
    ],
    rechtsgrundlagen: [
      '§ 30 Bundeszentralregistergesetz - Antrag auf Führungszeugnis',
      '§ 30a Bundeszentralregistergesetz - Erweitertes Führungszeugnis',
      '§ 32 Bundeszentralregistergesetz - Inhalt des Führungszeugnisses',
      '§ 34 ff. Bundeszentralregistergesetz - Fristen für die Aufnahme',
    ],
    online: {
      moeglich: true,
      hinweis: 'Vollständig online über das Portal des Bundesamts für Justiz - der einzige Weg ohne Behördengang. Voraussetzung ist ein Personalausweis mit freigeschalteter Online-Ausweisfunktion samt Kartenleser oder Smartphone.',
      voraussetzungen: ['Online-Ausweisfunktion mit PIN', 'AusweisApp oder NFC-Smartphone'],
    },
    haeufigeFehler: [
      'Das erweiterte Führungszeugnis ohne schriftliche Aufforderung beantragen - es wird dann nicht ausgestellt.',
      'Belegart O wählen, aber die Behördenanschrift nicht kennen.',
      'Annehmen, geringfügige Verurteilungen stünden nie drin - nach § 32 BZRG werden Geldstrafen bis 90 Tagessätze bei einmaliger Verurteilung nicht aufgenommen, darüber hinaus schon.',
      'Die Gebührenbefreiung für das Ehrenamt nicht beantragen.',
    ],
    faq: [
      { frage: 'Wie lange sind Einträge sichtbar?', antwort: 'Die Tilgungsfristen betragen je nach Strafe drei, fünf, zehn oder fünfzehn Jahre. Geldstrafen bis 90 Tagessätze und Jugendstrafen unter bestimmten Bedingungen werden bei erstmaliger Verurteilung gar nicht aufgenommen.' },
      { frage: 'Kann mein Arbeitgeber es selbst beantragen?', antwort: 'Nein. Nur Sie selbst können es beantragen; der Arbeitgeber kann die Vorlage verlangen.' },
      { frage: 'Was ist der Unterschied zwischen einfachem und erweitertem Zeugnis?', antwort: 'Das erweiterte enthält zusätzlich bestimmte Sexual- und Jugendschutzdelikte ohne die sonst geltenden Ausnahmen. Es ist Pflicht für Tätigkeiten mit Kindern und Jugendlichen.' },
      { frage: 'Ich lebe im Ausland - geht das auch?', antwort: 'Ja, über das Online-Portal des Bundesamts für Justiz oder schriftlich mit amtlich beglaubigter Unterschrift, etwa durch die deutsche Auslandsvertretung.' },
    ],
    verwandt: ['gewerbeanmeldung', 'meldebescheinigung', 'gewerbezentralregister'],
    eskalation: 'Bei Widerspruch gegen Eintragungen, bei Einsichtnahme über das Amtsgericht oder bei Auslandssachverhalten an das Bundesamt für Justiz verweisen.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht, überall identisch - die 13 Euro gelten in jeder Kommune.' },
    stand: '2026-08',
  },
  {
    id: 'eid-online-ausweisfunktion',
    cluster: 'melde-ausweis',
    name: 'Online-Ausweisfunktion aktivieren oder PIN zurücksetzen',
    sprechName: 'Online-Ausweisfunktion und Ausweis-PIN',
    synonyme: ['eid', 'online ausweisfunktion', 'ausweis pin', 'pin vergessen', 'pin zurücksetzen', 'ausweisapp', 'digitale identität', 'pin brief', 'transport pin', 'nfc ausweis', 'bundid'],
    leikaBezug: 'Personalausweis - Online-Ausweisfunktion (LeiKa 99011001)',
    kurzbeschreibung: 'Mit der Online-Ausweisfunktion weisen Sie sich digital gegenüber Behörden und Unternehmen aus. Sie ist bei allen seit 2017 ausgestellten Personalausweisen eingeschaltet; nötig sind nur die selbstgesetzte sechsstellige PIN und die AusweisApp.',
    zustaendigkeit: {
      stelle: 'Bürgeramt oder Personalausweisbehörde am Wohnort; PIN-Rücksetzbrief über das Bundesministerium des Innern',
      ebene: 'kommunal',
      hinweis: 'Jede Personalausweisbehörde kann helfen, nicht nur die des Hauptwohnsitzes.',
    },
    voraussetzungen: [
      'Personalausweis, elektronischer Aufenthaltstitel oder eID-Karte für Unionsbürger.',
      'Für die Nutzung: NFC-fähiges Smartphone oder Kartenlesegerät und die AusweisApp.',
      'Persönliches Erscheinen, wenn die PIN vor Ort neu gesetzt werden soll.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder elektronischer Aufenthaltstitel', pflicht: true },
      { was: 'PIN-Brief mit Transport-PIN und Sperrkennwort', pflicht: false, hinweis: 'Nur nötig, wenn Sie die PIN selbst zu Hause erstmals setzen wollen.' },
    ],
    gebuehren: [
      { position: 'PIN-Neusetzung im Bürgeramt', betrag: '0,00 bis 6,00 Euro', art: 'kommunal', hinweis: 'Die meisten Kommunen setzen die PIN gebührenfrei zurück.' },
      { position: 'PIN-Rücksetzbrief per Post', betrag: '0,00 Euro', art: 'bundeseinheitlich', hinweis: 'Kostenfrei über die Website des Bundes anzufordern, Zustellung binnen weniger Werktage.' },
      { position: 'Entsperrung nach dreimaliger Falscheingabe', betrag: '0,00 bis 6,00 Euro', art: 'kommunal' },
    ],
    fristen: ['Keine. Die Funktion bleibt über die gesamte Gültigkeitsdauer des Ausweises nutzbar.'],
    bearbeitungsdauer: 'Im Amt sofort. PIN-Rücksetzbrief in der Regel binnen einer Woche.',
    ablauf: [
      { nr: 1, titel: 'Status prüfen', detail: 'Öffnen Sie die AusweisApp und lesen Sie den Ausweis aus. Die App zeigt, ob die Funktion aktiviert ist und ob eine sechsstellige PIN gesetzt wurde.', akteur: 'Bürger' },
      { nr: 2, titel: 'Transport-PIN umsetzen', detail: 'Haben Sie den PIN-Brief noch, geben Sie die fünfstellige Transport-PIN in der App ein und vergeben eine eigene sechsstellige PIN.', akteur: 'Bürger' },
      { nr: 3, titel: 'PIN-Brief verloren?', detail: 'Fordern Sie kostenfrei einen PIN-Rücksetzbrief über die offizielle Seite des Bundes an oder gehen Sie ins Bürgeramt, wo die PIN sofort neu gesetzt wird.', akteur: 'Bürger' },
      { nr: 4, titel: 'Karte dreimal falsch eingegeben', detail: 'Nach dreimaliger Fehleingabe ist die PIN gesperrt. Die Entsperrung erfolgt mit der PUK aus dem PIN-Brief - die PUK gilt nur zehnmal - oder im Bürgeramt.', akteur: 'Bürger' },
      { nr: 5, titel: 'Nutzen', detail: 'Mit der PIN melden Sie sich bei BundID, ELSTER, Rentenversicherung, Kfz-Portal i-Kfz, dem Führungszeugnis-Portal und vielen Kommunalportalen an.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 10 Personalausweisgesetz - Elektronischer Identitätsnachweis',
      '§ 18 Personalausweisgesetz - Auslesen und Übermittlung',
      'eIDAS-Verordnung (EU) Nr. 910/2014',
      'Onlinezugangsgesetz (OZG)',
    ],
    online: {
      moeglich: true,
      hinweis: 'PIN-Rücksetzbrief und Umsetzen der Transport-PIN gehen vollständig digital. Nur eine sofortige PIN-Neusetzung ohne Brief verlangt den Behördengang.',
      voraussetzungen: ['NFC-Smartphone oder Kartenleser', 'AusweisApp'],
    },
    haeufigeFehler: [
      'Transport-PIN und selbstgesetzte PIN verwechseln - die fünfstellige gilt nur einmal.',
      'Den PIN-Brief entsorgen, weil man ihn für Werbung hält.',
      'NFC am Smartphone deaktiviert lassen oder den Ausweis beim Auslesen zu früh bewegen.',
      'Annehmen, die Funktion sei abgeschaltet - seit Juli 2017 ist sie standardmäßig aktiv.',
    ],
    faq: [
      { frage: 'Was kostet die PIN-Zurücksetzung?', antwort: 'Der Rücksetzbrief per Post ist kostenfrei. Im Bürgeramt setzen die meisten Kommunen die PIN gebührenfrei, einige verlangen bis zu 6 Euro.' },
      { frage: 'Brauche ich ein Kartenlesegerät?', antwort: 'Nein, ein NFC-fähiges Smartphone mit der AusweisApp genügt.' },
      { frage: 'Was ist BundID?', antwort: 'Das zentrale Nutzerkonto des Bundes. Sie melden sich darin mit der Online-Ausweisfunktion, ELSTER-Zertifikat oder Benutzername an und nutzen es für Verwaltungsleistungen von Bund, Ländern und Kommunen.' },
    ],
    verwandt: ['personalausweis', 'fuehrungszeugnis', 'wohnsitz-anmeldung'],
    eskalation: 'Bei technischen Problemen an den eID-Support des Bundes oder bei gesperrter PUK an die Personalausweisbehörde verweisen.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Rechtsrahmen bundeseinheitlich, kleinere Gebühren für die PIN-Neusetzung kommunal unterschiedlich.' },
    stand: '2026-08',
  },
  {
    id: 'wohnungsgeberbestaetigung',
    cluster: 'melde-ausweis',
    name: 'Wohnungsgeberbestätigung ausstellen oder erhalten',
    sprechName: 'Wohnungsgeberbestätigung',
    synonyme: ['wohnungsgeberbestätigung', 'vermieterbescheinigung', 'einzugsbestätigung', 'vermieter bescheinigung', 'wohnungsgeber', 'untermietbescheinigung'],
    leikaBezug: 'Mitwirkung des Wohnungsgebers bei der Anmeldung (LeiKa 99083016)',
    kurzbeschreibung: 'Wer eine Wohnung überlässt, muss dem Einziehenden den Bezug schriftlich oder elektronisch bestätigen. Ohne diese Bestätigung nach § 19 BMG kann sich niemand anmelden.',
    zustaendigkeit: {
      stelle: 'Der Wohnungsgeber selbst - Vermieter, Hausverwaltung, Hauptmieter bei Untermiete oder der Eigentümer bei Selbstbezug',
      ebene: 'sonstige',
      hinweis: 'Die Meldebehörde prüft und kann bei Verweigerung ein Bußgeld gegen den Wohnungsgeber verhängen.',
    },
    voraussetzungen: [
      'Eine Person zieht in eine Wohnung ein oder aus ihr aus.',
      'Der Wohnungsgeber ist der Verfügungsberechtigte oder eine von ihm beauftragte Person.',
    ],
    unterlagen: [
      { was: 'Name und Anschrift des Wohnungsgebers', pflicht: true },
      { was: 'Angabe, ob Einzug oder Auszug, mit Datum', pflicht: true },
      { was: 'Anschrift der Wohnung', pflicht: true },
      { was: 'Namen aller meldepflichtigen Personen', pflicht: true },
      { was: 'Bei Beauftragung: Name und Anschrift des Eigentümers', pflicht: false, hinweis: 'Nötig, wenn eine Hausverwaltung bestätigt.' },
    ],
    gebuehren: [
      { position: 'Ausstellung', betrag: '0,00 Euro', art: 'keine', hinweis: 'Der Wohnungsgeber darf dafür kein Entgelt verlangen.' },
      { position: 'Bußgeld bei Verweigerung oder falscher Bestätigung', betrag: 'bis 1.000 Euro', art: 'bundeseinheitlich', hinweis: 'Bei Gefälligkeitsbestätigungen für Scheinanmeldungen bis 50.000 Euro nach § 54 Abs. 2 BMG.' },
    ],
    fristen: ['Ausstellung binnen zwei Wochen nach dem Ein- oder Auszug.'],
    bearbeitungsdauer: 'Sofort - es handelt sich um ein einfaches Formular.',
    ablauf: [
      { nr: 1, titel: 'Formular besorgen', detail: 'Alle Meldebehörden stellen ein Muster online bereit. Eine formlose Bestätigung mit allen Pflichtangaben genügt ebenfalls.', akteur: 'Bürger' },
      { nr: 2, titel: 'Ausfüllen und unterschreiben lassen', detail: 'Der Wohnungsgeber trägt seine Daten, die Wohnung, das Einzugsdatum und alle einziehenden Personen ein.', akteur: 'Dritte' },
      { nr: 3, titel: 'Bei der Anmeldung vorlegen', detail: 'Original mitbringen; einige Kommunen akzeptieren digitale Übermittlung durch den Wohnungsgeber im Rahmen der elektronischen Wohnsitzanmeldung.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 19 Bundesmeldegesetz - Mitwirkung des Wohnungsgebers',
      '§ 54 Bundesmeldegesetz - Bußgeldvorschriften',
    ],
    online: {
      moeglich: true,
      hinweis: 'Im Rahmen der elektronischen Wohnsitzanmeldung kann der Wohnungsgeber die Bestätigung digital hinterlegen und erhält dafür einen Zuordnungscode.',
    },
    haeufigeFehler: [
      'Den Mietvertrag statt der Bestätigung vorlegen.',
      'Nicht alle einziehenden Personen aufführen - insbesondere Kinder werden oft vergessen.',
      'Als Untermieter vom Hauptmieter keine Bestätigung verlangen - auch er ist Wohnungsgeber.',
      'Als Eigentümer glauben, man brauche keine - man bestätigt sich den Einzug selbst.',
    ],
    faq: [
      { frage: 'Der Vermieter weigert sich. Was nun?', antwort: 'Weisen Sie ihn auf § 19 BMG und das Bußgeld hin. Hilft das nicht, melden Sie sich trotzdem beim Bürgeramt und schildern den Sachverhalt - die Behörde fordert den Wohnungsgeber selbst auf.' },
      { frage: 'Ich wohne bei den Eltern - wer bestätigt?', antwort: 'Der Eigentümer oder Hauptmieter der Wohnung, also in der Regel ein Elternteil.' },
      { frage: 'Braucht man sie auch beim Auszug?', antwort: 'Nur wenn eine Abmeldung nötig ist, also bei Wegzug ins Ausland oder Aufgabe einer Nebenwohnung.' },
    ],
    verwandt: ['wohnsitz-anmeldung', 'wohnsitz-abmeldung'],
    eskalation: 'Bei Verdacht auf Scheinanmeldung oder bei Verweigerung durch den Wohnungsgeber an das Bürgeramt weiterleiten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundeseinheitlich in § 19 BMG geregelt.' },
    stand: '2026-08',
  },
  {
    id: 'auskunftssperre',
    cluster: 'melde-ausweis',
    name: 'Auskunftssperre im Melderegister eintragen lassen',
    sprechName: 'Auskunftssperre im Melderegister',
    synonyme: ['auskunftssperre', 'adresse sperren', 'melderegister sperren', 'übermittlungssperre', 'stalking', 'gewaltschutz adresse', 'daten schützen melderegister', 'werbesperre'],
    leikaBezug: 'Melderegisterauskunft - Auskunftssperre (LeiKa 99083020)',
    kurzbeschreibung: 'Wer bei einer Auskunft aus dem Melderegister eine Gefahr für Leben, Gesundheit oder ähnliche schutzwürdige Interessen befürchtet, kann eine Auskunftssperre beantragen. Daneben gibt es Übermittlungssperren gegen Werbung, Adressbuchverlage, Parteien und Kirchen.',
    zustaendigkeit: {
      stelle: 'Meldebehörde des Wohnorts',
      ebene: 'kommunal',
      hinweis: 'Die Sperre wirkt bundesweit, weil sie im Melderegister vermerkt und bei Umzügen mit übermittelt wird.',
    },
    voraussetzungen: [
      'Für die Auskunftssperre: glaubhafte Darlegung einer Gefahr für Leben, Gesundheit, persönliche Freiheit oder ähnliche schutzwürdige Interessen.',
      'Für Übermittlungssperren: keine Begründung nötig, ein formloser Antrag genügt.',
    ],
    unterlagen: [
      { was: 'Personalausweis oder Reisepass', pflicht: true },
      { was: 'Nachweise zur Gefährdung', pflicht: false, hinweis: 'Anzeigen, Gewaltschutzanordnung, ärztliche Atteste, Schreiben von Frauenhäusern oder Beratungsstellen. Eine schlüssige eigene Schilderung kann genügen.' },
    ],
    gebuehren: [
      { position: 'Auskunftssperre', betrag: '0,00 Euro', art: 'bundeseinheitlich' },
      { position: 'Übermittlungssperren', betrag: '0,00 Euro', art: 'bundeseinheitlich' },
    ],
    fristen: [
      'Die Auskunftssperre gilt zwei Jahre und wird auf Antrag verlängert - die Behörde prüft vor Ablauf und teilt dies mit.',
      'Übermittlungssperren gelten unbefristet bis zum Widerruf.',
    ],
    bearbeitungsdauer: 'Übermittlungssperren sofort. Auskunftssperren nach Prüfung, meist wenige Tage bis Wochen; in akuten Gefährdungslagen sofort.',
    ablauf: [
      { nr: 1, titel: 'Sperrart wählen', detail: 'Auskunftssperre nach § 51 BMG bei Gefährdung; Übermittlungssperren nach § 36, 42, 50 BMG gegen Werbung, Adressbücher, Parteien vor Wahlen, Alters- und Ehejubiläen sowie Religionsgemeinschaften.', akteur: 'Bürger' },
      { nr: 2, titel: 'Antrag stellen', detail: 'Persönlich, schriftlich oder online. Schildern Sie die Gefährdungslage konkret und legen Sie vorhandene Nachweise bei.', akteur: 'Bürger' },
      { nr: 3, titel: 'Prüfung durch die Meldebehörde', detail: 'Die Behörde wägt zwischen Ihrem Schutzinteresse und dem Auskunftsinteresse Dritter ab.', akteur: 'Behörde' },
      { nr: 4, titel: 'Eintragung und Wirkung', detail: 'Anfragen werden künftig nicht mehr automatisch beantwortet; die anfragende Person wird angehört, bevor überhaupt entschieden wird. Behörden und Gerichte erhalten weiterhin Auskunft, soweit erforderlich.', akteur: 'Behörde' },
      { nr: 5, titel: 'Verlängerung im Blick behalten', detail: 'Vor Ablauf der zwei Jahre rechtzeitig verlängern lassen, wenn die Gefährdung fortbesteht.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 51 Bundesmeldegesetz - Auskunftssperren',
      '§ 52 Bundesmeldegesetz - Bedingter Sperrvermerk',
      '§ 36, 42, 50 Bundesmeldegesetz - Übermittlungssperren',
      'Gewaltschutzgesetz (GewSchG)',
    ],
    online: {
      moeglich: true,
      hinweis: 'Übermittlungssperren lassen sich in vielen Kommunen online setzen. Für die Auskunftssperre verlangen die meisten Behörden eine persönliche oder schriftliche Darlegung.',
    },
    haeufigeFehler: [
      'Nur eine Werbesperre setzen, obwohl eine echte Gefährdung vorliegt - die Werbesperre schützt nicht vor Auskünften an Privatpersonen.',
      'Die Verlängerung nach zwei Jahren versäumen.',
      'Vergessen, dass die Sperre nicht gegenüber allen Stellen wirkt - Behörden, Gerichte und öffentlich-rechtliche Stellen erhalten weiter Auskunft.',
    ],
    faq: [
      { frage: 'Bin ich damit unauffindbar?', antwort: 'Nein. Die Sperre verhindert die automatische Auskunft an Private. Behörden, Gerichte, Polizei und Gerichtsvollzieher erhalten weiterhin Daten, soweit sie sie benötigen.' },
      { frage: 'Was ist ein bedingter Sperrvermerk?', antwort: 'Er wird eingetragen, wenn Sie in einer Einrichtung wohnen - Frauenhaus, Klinik, Justizvollzug -, damit diese Einrichtung nicht aus der Anschrift ableitbar ist.' },
      { frage: 'Wie schnell wirkt die Sperre?', antwort: 'In akuten Gefährdungslagen trägt die Behörde sie sofort ein; die endgültige Entscheidung folgt.' },
    ],
    verwandt: ['meldebescheinigung', 'wohnsitz-anmeldung'],
    eskalation: 'Bei akuter Gefährdung sofort an die Meldebehörde und parallel an Polizei oder Gewaltschutzberatung weiterleiten, keine Wartezeit zumuten.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundeseinheitlich im Bundesmeldegesetz geregelt.' },
    stand: '2026-08',
  },
];
