/** Stufe 2: Leistungen des Clusters "Steuern und kommunale Abgaben". */
export const LEISTUNGEN = [
  {
    id: 'grundsteuer',
    cluster: 'steuern-abgaben',
    name: 'Grundsteuer und Grundsteuerbescheid',
    sprechName: 'Grundsteuer',
    synonyme: ['grundsteuer', 'grundsteuerbescheid', 'grundsteuerreform', 'grundsteuerwert', 'messbetrag', 'hebesatz', 'grundsteuererklärung', 'einheitswert'],
    leikaBezug: 'Grundsteuer - Festsetzung (LeiKa 99102010)',
    kurzbeschreibung: 'Die Grundsteuer wird seit 1. Januar 2025 nach neuem Recht erhoben. Drei Schritte greifen ineinander: Das Finanzamt stellt den Grundsteuerwert fest und setzt den Messbetrag fest, die Gemeinde wendet ihren Hebesatz an und erlässt den Grundsteuerbescheid.',
    zustaendigkeit: {
      stelle: 'Finanzamt für Grundsteuerwert- und Messbescheid, Gemeinde beziehungsweise Stadtkasse für den Grundsteuerbescheid',
      ebene: 'kommunal',
      hinweis: 'Das ist der zentrale Punkt: Wer die Bemessung angreifen will, muss sich an das Finanzamt wenden. Ein Widerspruch bei der Gemeinde gegen die Höhe der Bemessung geht ins Leere.',
    },
    voraussetzungen: [
      'Sie sind Eigentümerin oder Eigentümer eines Grundstücks, einer Wohnung oder eines Betriebs der Land- und Forstwirtschaft zum Stichtag 1. Januar des Jahres.',
      'Bei Eigentumswechsel bleibt der zum 1. Januar eingetragene Eigentümer für das ganze Jahr Steuerschuldner; die Aufteilung erfolgt zivilrechtlich im Kaufvertrag.',
    ],
    unterlagen: [
      { was: 'Grundsteuerwertbescheid und Grundsteuermessbescheid des Finanzamts', pflicht: true, hinweis: 'Grundlage jeder Pruefung - ohne diese Bescheide laesst sich der Grundsteuerbescheid der Gemeinde nicht nachvollziehen.' },
      { was: 'Grundbuchauszug und Flurstücksdaten', pflicht: false },
      { was: 'Wohn- und Nutzflächen, Baujahr, Bodenrichtwert', pflicht: false, hinweis: 'Für die Erklärung und für die Prüfung des Bescheids.' },
    ],
    gebuehren: [
      { position: 'Grundsteuer B für bebaute und unbebaute Grundstücke', betrag: 'Grundsteuerwert mal Steuermesszahl mal kommunaler Hebesatz', art: 'kommunal', hinweis: 'Die Hebesätze liegen je nach Gemeinde etwa zwischen 100 und über 1.000 Prozent. Die Belastung hat sich mit der Reform für viele Objekte verschoben - manche zahlen mehr, andere weniger.' },
      { position: 'Grundsteuer A für land- und forstwirtschaftliches Vermögen', betrag: 'eigener Hebesatz', art: 'kommunal' },
      { position: 'Grundsteuer C für baureife unbebaute Grundstücke', betrag: 'erhöhter Hebesatz möglich', art: 'kommunal', hinweis: 'Optional; Gemeinden können damit Bauland mobilisieren.' },
      { position: 'Widerspruch und Einspruch', betrag: '0,00 Euro', art: 'keine' },
    ],
    fristen: [
      'Einspruch gegen Grundsteuerwert- und Messbescheid beim Finanzamt: ein Monat ab Bekanntgabe.',
      'Widerspruch gegen den Grundsteuerbescheid der Gemeinde: ein Monat - aber nur gegen Fehler der Gemeinde, etwa den falschen Hebesatz oder die falsche Person.',
      'Zahlungstermine: in der Regel 15. Februar, 15. Mai, 15. August und 15. November; auf Antrag Jahreszahlung zum 1. Juli.',
      'Anzeige von Änderungen - Bebauung, Abriss, Nutzungsänderung - beim Finanzamt bis 31. Januar des Folgejahres.',
    ],
    bearbeitungsdauer: 'Bescheide ergehen im Rahmen der jährlichen Veranlagung. Einsprüche beim Finanzamt dauern häufig mehrere Monate.',
    ablauf: [
      { nr: 1, titel: 'Die drei Bescheide auseinanderhalten', detail: 'Grundsteuerwertbescheid und Grundsteuermessbescheid kommen vom Finanzamt, der Grundsteuerbescheid von der Gemeinde. Fehler in Fläche, Baujahr oder Bodenrichtwert sind Sache des Finanzamts.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bescheide prüfen', detail: 'Vergleichen Sie Wohnfläche, Grundstücksgröße, Baujahr und Gebäudeart mit der Realität. Übertragungsfehler aus der Erklärung sind häufig.', akteur: 'Bürger' },
      { nr: 3, titel: 'Rechtsbehelf einlegen', detail: 'Gegen die Feststellung beim Finanzamt Einspruch, gegen Gemeindefehler Widerspruch. Beides binnen eines Monats, beides kostenfrei.', akteur: 'Bürger' },
      { nr: 4, titel: 'Zahlungspflicht beachten', detail: 'Einspruch und Widerspruch haben keine aufschiebende Wirkung. Beantragen Sie zusätzlich Aussetzung der Vollziehung, wenn Sie nicht zahlen wollen - sonst laufen Säumniszuschläge auf.', akteur: 'Bürger' },
      { nr: 5, titel: 'Änderungen melden', detail: 'Bauliche Veränderungen, Abriss, Nutzungsänderungen und Eigentumswechsel sind dem Finanzamt anzuzeigen.', akteur: 'Bürger' },
      { nr: 6, titel: 'Erlass prüfen', detail: 'Bei erheblicher Ertragsminderung vermieteter Objekte oder bei Denkmälern kommt ein teilweiser Erlass in Betracht - Antrag bis 31. März des Folgejahres bei der Gemeinde.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Grundsteuergesetz (GrStG)',
      'Bewertungsgesetz, Siebenter Abschnitt - Grundsteuerwerte',
      'Landesgrundsteuergesetze der Länder mit abweichenden Modellen - Bayern, Baden-Württemberg, Hessen, Niedersachsen, Hamburg',
      '§ 32 bis 34 GrStG - Erlass der Grundsteuer',
      'Abgabenordnung für das Einspruchsverfahren',
    ],
    online: { moeglich: true, hinweis: 'Grundsteuererklärungen und Einsprüche laufen über ELSTER; kommunale Bescheide und Lastschriftmandate häufig über das Serviceportal der Gemeinde.' },
    haeufigeFehler: [
      'Bei der Gemeinde gegen die Bemessungsgrundlage widersprechen - zuständig ist das Finanzamt.',
      'Die Monatsfrist verstreichen lassen.',
      'Einspruch einlegen und die Zahlung einstellen, ohne Aussetzung der Vollziehung zu beantragen.',
      'Änderungen am Gebäude nicht anzeigen.',
      'Den Erlassantrag bei Ertragsminderung übersehen.',
    ],
    faq: [
      { frage: 'Warum zahle ich seit 2025 mehr?', antwort: 'Die Reform hat die Bemessungsgrundlagen neu ermittelt. Die Gemeinden sollten die Hebesätze aufkommensneutral anpassen, was nicht überall gelungen ist. Innerhalb einer Gemeinde verschiebt sich die Last zwischen Grundstücksarten - manche zahlen mehr, andere weniger.' },
      { frage: 'Können Vermieter die Grundsteuer umlegen?', antwort: 'Ja, sie gehört nach der Betriebskostenverordnung zu den umlagefähigen Betriebskosten.' },
      { frage: 'Ich habe das Haus im Juni verkauft.', antwort: 'Steuerschuldner für das ganze Jahr bleibt, wer am 1. Januar Eigentümer war. Die Aufteilung regeln Käufer und Verkäufer im Kaufvertrag.' },
      { frage: 'Welches Modell gilt bei mir?', antwort: 'Die meisten Länder nutzen das Bundesmodell. Bayern, Baden-Württemberg, Hessen, Niedersachsen und Hamburg haben eigene Modelle mit anderen Bemessungsgrundlagen - vor allem Fläche statt Wert.' },
    ],
    verwandt: ['bauantrag', 'zweitwohnungsteuer', 'gewerbesteuer'],
    eskalation: 'Bei Bewertungsfehlern, Erlassanträgen oder Erbengemeinschaften an Finanzamt beziehungsweise Steuerberatung verweisen.',
    belastbarkeit: { quelle: 'landesrecht-variiert', hinweis: 'Bundesmodell und fünf Landesmodelle nebeneinander, dazu kommunale Hebesätze - konkrete Beträge nie ohne Ortsbezug nennen.' },
    stand: '2026-08',
  },
  {
    id: 'zweitwohnungsteuer',
    cluster: 'steuern-abgaben',
    name: 'Zweitwohnungsteuer anmelden',
    sprechName: 'Zweitwohnungsteuer',
    synonyme: ['zweitwohnungsteuer', 'zweitwohnsitzsteuer', 'nebenwohnung steuer', 'studentenbude steuer', 'zweitwohnung anmelden steuer'],
    leikaBezug: 'Zweitwohnungsteuer - Anmeldung (LeiKa 99114010)',
    kurzbeschreibung: 'Viele Gemeinden erheben auf Nebenwohnungen eine Aufwandsteuer. Sie knüpft an die melderechtliche Nebenwohnung an und bemisst sich meist nach der Jahreskaltmiete.',
    zustaendigkeit: {
      stelle: 'Steueramt oder Stadtkasse der Gemeinde, in der die Nebenwohnung liegt',
      ebene: 'kommunal',
      hinweis: 'Nicht jede Gemeinde erhebt die Steuer - besonders verbreitet ist sie in Universitäts- und Tourismusstädten.',
    },
    voraussetzungen: [
      'Sie haben in der Gemeinde eine Nebenwohnung im melderechtlichen Sinne.',
      'Die Wohnung dient dem persönlichen Lebensbedarf - reine Kapitalanlagen ohne Eigennutzung sind meist nicht steuerpflichtig.',
      'Häufige Befreiungen: Wohnungen von Verheirateten oder Verpartnerten, die aus beruflichen Gründen getrennt wohnen - das hat das Bundesverfassungsgericht vorgegeben -, Wohnungen in Pflegeeinrichtungen, teils Wohnungen von Auszubildenden mit geringem Einkommen.',
    ],
    unterlagen: [
      { was: 'Steuererklärung beziehungsweise Anmeldeformular der Gemeinde', pflicht: true },
      { was: 'Mietvertrag mit Angabe der Kaltmiete', pflicht: true },
      { was: 'Meldebestätigung', pflicht: false },
      { was: 'Bei Befreiungsanträgen: Heiratsurkunde und Meldebescheinigung der Hauptwohnung des Ehegatten', pflicht: false },
    ],
    gebuehren: [
      { position: 'Zweitwohnungsteuer', betrag: 'meist 8 bis 20 Prozent der Jahreskaltmiete', art: 'kommunal', hinweis: 'Einige Gemeinden bemessen nach Wohnfläche oder mit gestaffelten Pauschalen.' },
    ],
    fristen: [
      'Anmeldung meist binnen ein bis drei Monaten nach Begründung der Nebenwohnung.',
      'Abmeldung bei Aufgabe der Wohnung unverzüglich.',
      'Widerspruch gegen den Steuerbescheid: ein Monat.',
    ],
    bearbeitungsdauer: 'Bescheid meist binnen weniger Wochen; die Steuer wird jährlich oder quartalsweise erhoben.',
    ablauf: [
      { nr: 1, titel: 'Prüfen, ob die Gemeinde die Steuer erhebt', detail: 'Ein Blick in die Satzung der Gemeinde oder eine Nachfrage beim Steueramt genügt.', akteur: 'Bürger' },
      { nr: 2, titel: 'Melderechtliche Zuordnung prüfen', detail: 'Hauptwohnung ist die vorwiegend genutzte Wohnung. Wer die Zuordnung anpassen kann und will, sollte das melderechtlich sauber und wahrheitsgemäß tun - Scheinangaben sind eine Ordnungswidrigkeit.', akteur: 'Bürger' },
      { nr: 3, titel: 'Befreiung prüfen', detail: 'Vor allem die Befreiung für berufsbedingte Zweitwohnungen von Verheirateten wird häufig übersehen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Anmelden und Bescheid prüfen', detail: 'Kontrollieren Sie die zugrunde gelegte Kaltmiete und den Zeitraum.', akteur: 'Bürger' },
      { nr: 5, titel: 'Steuerliche Absetzbarkeit prüfen', detail: 'Bei doppelter Haushaltsführung sind Zweitwohnungsteuer und Miete bis zu bestimmten Grenzen als Werbungskosten absetzbar.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      'Artikel 105 Abs. 2a Grundgesetz - örtliche Aufwandsteuern',
      'Kommunalabgabengesetze der Länder',
      'Kommunale Zweitwohnungsteuersatzungen',
      '§ 21, 22 Bundesmeldegesetz - Haupt- und Nebenwohnung',
      '§ 9 Abs. 1 Satz 3 Nr. 5 Einkommensteuergesetz - doppelte Haushaltsführung',
    ],
    online: { moeglich: true, hinweis: 'An- und Abmeldung in vielen Gemeinden online möglich.' },
    haeufigeFehler: [
      'Die Nebenwohnung anmelden und die Steuerpflicht nicht bedenken.',
      'Die Befreiung für berufsbedingte Zweitwohnungen Verheirateter nicht beantragen.',
      'Bei Auszug die Abmeldung vergessen.',
      'Die Absetzbarkeit bei doppelter Haushaltsführung nicht nutzen.',
    ],
    faq: [
      { frage: 'Muss ich als Studentin zahlen?', antwort: 'Wenn Sie am Studienort eine Nebenwohnung führen und die Gemeinde die Steuer erhebt, grundsätzlich ja. Manche Satzungen sehen Befreiungen für Auszubildende mit geringem Einkommen vor - fragen Sie nach.' },
      { frage: 'Wie hoch ist die Steuer?', antwort: 'Meist 8 bis 20 Prozent der Jahreskaltmiete, je nach Satzung. Bei 400 Euro Kaltmiete monatlich sind das grob 380 bis 960 Euro im Jahr.' },
      { frage: 'Ich wohne beruflich getrennt von meiner Ehefrau.', antwort: 'Dann greift regelmäßig eine Befreiung - das Bundesverfassungsgericht hat die Besteuerung solcher Erwerbszweitwohnungen von Verheirateten für unvereinbar mit Artikel 6 Grundgesetz erklärt.' },
    ],
    verwandt: ['wohnsitz-anmeldung', 'grundsteuer'],
    eskalation: 'Bei Befreiungsanträgen, Nachforderungen für zurückliegende Jahre oder Streit über die Wohnungszuordnung an das Steueramt weiterleiten.',
    belastbarkeit: { quelle: 'kommunal-variiert', hinweis: 'Rein kommunale Steuer - Existenz, Höhe und Befreiungen ausschließlich nach örtlicher Satzung.' },
    stand: '2026-08',
  },
  {
    id: 'gewerbesteuer',
    cluster: 'steuern-abgaben',
    name: 'Gewerbesteuer und Gewerbesteuerbescheid',
    sprechName: 'Gewerbesteuer',
    synonyme: ['gewerbesteuer', 'gewerbesteuerbescheid', 'gewerbeertrag', 'messbetrag gewerbe', 'hebesatz gewerbe', 'gewerbesteuervorauszahlung'],
    leikaBezug: 'Gewerbesteuer - Festsetzung (LeiKa 99102015)',
    kurzbeschreibung: 'Die Gewerbesteuer belastet den Gewerbeertrag. Das Finanzamt setzt den Messbetrag fest, die Gemeinde wendet ihren Hebesatz an. Einzelunternehmen und Personengesellschaften haben einen Freibetrag von 24.500 Euro.',
    zustaendigkeit: {
      stelle: 'Finanzamt für den Gewerbesteuermessbescheid, Gemeinde für den Gewerbesteuerbescheid',
      ebene: 'kommunal',
    },
    voraussetzungen: [
      'Betrieb eines stehenden Gewerbes im Inland.',
      'Freiberufler und Land- und Forstwirte unterliegen nicht der Gewerbesteuer.',
      'Kapitalgesellschaften sind stets gewerbesteuerpflichtig, ohne Freibetrag.',
    ],
    unterlagen: [
      { was: 'Gewerbesteuererklärung über ELSTER', pflicht: true, hinweis: 'Pflicht bei Gewerbeertrag über dem Freibetrag; Kapitalgesellschaften immer.' },
      { was: 'Gewinnermittlung - Einnahmen-Überschuss-Rechnung oder Bilanz', pflicht: true },
      { was: 'Gewerbesteuermessbescheid', pflicht: false },
    ],
    gebuehren: [
      { position: 'Freibetrag für Einzelunternehmen und Personengesellschaften', betrag: '24.500 Euro Gewerbeertrag', art: 'bundeseinheitlich' },
      { position: 'Steuermesszahl', betrag: '3,5 Prozent', art: 'bundeseinheitlich' },
      { position: 'Hebesatz der Gemeinde', betrag: 'mindestens 200 Prozent, üblich 250 bis 500 Prozent', art: 'kommunal', hinweis: 'In Großstädten häufig über 400 Prozent, in kleinen Gemeinden teils bei 250.' },
      { position: 'Anrechnung auf die Einkommensteuer', betrag: 'das 4-fache des Messbetrags', art: 'bundeseinheitlich', hinweis: 'Bei natürlichen Personen wird die Gewerbesteuer nach § 35 EStG weitgehend auf die Einkommensteuer angerechnet - bis zu einem Hebesatz von etwa 400 Prozent wirkt sie damit fast neutral.' },
    ],
    fristen: [
      'Gewerbesteuererklärung: gleiche Frist wie die Einkommensteuererklärung, regelmäßig 31. Juli des Folgejahres, mit steuerlicher Beratung deutlich später.',
      'Vorauszahlungen: 15. Februar, 15. Mai, 15. August, 15. November.',
      'Einspruch gegen den Messbescheid beim Finanzamt: ein Monat.',
      'Widerspruch gegen den Gemeindebescheid: ein Monat, aber nur bei Fehlern der Gemeinde.',
    ],
    bearbeitungsdauer: 'Veranlagung meist wenige Monate nach Abgabe der Erklärung.',
    ablauf: [
      { nr: 1, titel: 'Gewerbeertrag ermitteln', detail: 'Ausgangspunkt ist der Gewinn, korrigiert um Hinzurechnungen nach § 8 GewStG - etwa ein Viertel der Finanzierungsentgelte über dem Freibetrag - und Kürzungen nach § 9 GewStG, insbesondere für Grundbesitz.', akteur: 'Bürger' },
      { nr: 2, titel: 'Erklärung abgeben', detail: 'Elektronisch über ELSTER.', akteur: 'Bürger' },
      { nr: 3, titel: 'Messbescheid prüfen', detail: 'Fehler in der Bemessung sind beim Finanzamt anzugreifen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Gemeindebescheid und Zahlung', detail: 'Die Gemeinde multipliziert Messbetrag und Hebesatz und setzt Vorauszahlungen für Folgejahre fest.', akteur: 'Behörde' },
      { nr: 5, titel: 'Vorauszahlungen anpassen', detail: 'Läuft das Geschäft schlechter, beantragen Sie eine Herabsetzung der Vorauszahlungen - das verbessert die Liquidität sofort.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 2 Gewerbesteuergesetz - Steuergegenstand',
      '§ 8, 9 GewStG - Hinzurechnungen und Kürzungen',
      '§ 11 GewStG - Steuermesszahl und Freibetrag',
      '§ 16 GewStG - Hebesatz',
      '§ 35 Einkommensteuergesetz - Anrechnung auf die Einkommensteuer',
    ],
    online: { moeglich: true, hinweis: 'Erklärung über ELSTER; kommunale Bescheide und Zahlungen häufig über das Serviceportal.' },
    haeufigeFehler: [
      'Bei der Gemeinde gegen die Höhe des Messbetrags widersprechen.',
      'Den Freibetrag von 24.500 Euro bei Kapitalgesellschaften erwarten - dort gibt es ihn nicht.',
      'Vorauszahlungen bei sinkendem Gewinn nicht anpassen lassen.',
      'Die Anrechnung auf die Einkommensteuer übersehen und die Belastung überschätzen.',
    ],
    faq: [
      { frage: 'Ab wann zahle ich Gewerbesteuer?', antwort: 'Als Einzelunternehmen oder Personengesellschaft ab einem Gewerbeertrag über 24.500 Euro im Jahr. Kapitalgesellschaften ab dem ersten Euro.' },
      { frage: 'Wie hoch ist die Belastung?', antwort: 'Messbetrag ist 3,5 Prozent des Ertrags über dem Freibetrag, multipliziert mit dem Hebesatz der Gemeinde. Bei 400 Prozent Hebesatz sind das effektiv 14 Prozent des Gewerbeertrags - bei natürlichen Personen weitgehend auf die Einkommensteuer anrechenbar.' },
      { frage: 'Zahlen Freiberufler Gewerbesteuer?', antwort: 'Nein. Freiberufliche Einkünfte nach § 18 EStG unterliegen nicht der Gewerbesteuer - deshalb ist die Abgrenzung so wichtig.' },
    ],
    verwandt: ['gewerbeanmeldung', 'steuerliche-erfassung', 'grundsteuer'],
    eskalation: 'Bei Abgrenzungsfragen zwischen Gewerbe und freiem Beruf, Betriebsaufspaltungen oder Zerlegung auf mehrere Gemeinden an Finanzamt und Steuerberatung verweisen.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesgesetz mit kommunalem Hebesatz - die Belastung hängt stark vom Standort ab.' },
    stand: '2026-08',
  },
  {
    id: 'steuer-identifikationsnummer',
    cluster: 'steuern-abgaben',
    name: 'Steuerliche Identifikationsnummer erhalten oder erneut mitteilen lassen',
    sprechName: 'Steuer-Identifikationsnummer',
    synonyme: ['steuer id', 'steueridentifikationsnummer', 'idnr', 'steuernummer vergessen', 'identifikationsnummer', 'steuer-id verloren', 'tin'],
    leikaBezug: 'Steuerliche Identifikationsnummer - Mitteilung (LeiKa 99102001)',
    kurzbeschreibung: 'Die elfstellige Steuer-Identifikationsnummer wird jeder in Deutschland gemeldeten Person einmalig zugeteilt und bleibt lebenslang gleich. Sie wird für Lohnsteuer, Kindergeld, Bankkonten und viele Anträge gebraucht.',
    zustaendigkeit: {
      stelle: 'Bundeszentralamt für Steuern; Finanzämter und Meldebehörden können ebenfalls Auskunft geben',
      ebene: 'bund',
    },
    voraussetzungen: [
      'Meldung mit Wohnsitz in Deutschland - die Zuteilung erfolgt automatisch, bei Neugeborenen wenige Wochen nach der Geburt.',
      'Auskunft nur an die betroffene Person selbst oder gesetzliche Vertreter.',
    ],
    unterlagen: [
      { was: 'Name, Geburtsdatum, Geburtsort und aktuelle Meldeadresse', pflicht: true },
      { was: 'Bei Kindern: Angaben der Sorgeberechtigten', pflicht: false },
    ],
    gebuehren: [
      { position: 'Zuteilung und erneute Mitteilung', betrag: '0,00 Euro', art: 'keine' },
    ],
    fristen: ['Keine. Die Nummer gilt lebenslang und wird 20 Jahre nach dem Tod gelöscht.'],
    bearbeitungsdauer: 'Bei Online-Anforderung beim Bundeszentralamt für Steuern in der Regel zwei bis vier Wochen per Post - aus Datenschutzgründen erfolgt keine Auskunft per E-Mail oder Telefon.',
    ablauf: [
      { nr: 1, titel: 'Zuerst in eigenen Unterlagen suchen', detail: 'Die Nummer steht auf jeder Lohnsteuerbescheinigung, jedem Einkommensteuerbescheid, dem Informationsschreiben des Bundeszentralamts und häufig auf Kindergeldbescheiden.', akteur: 'Bürger' },
      { nr: 2, titel: 'Erneute Mitteilung anfordern', detail: 'Über das Eingabeformular auf der Seite des Bundeszentralamts für Steuern. Der Versand erfolgt ausschließlich per Post an die gemeldete Adresse.', akteur: 'Bürger' },
      { nr: 3, titel: 'Alternativ beim Finanzamt fragen', detail: 'Das Finanzamt kann sie Ihnen bei persönlicher Vorsprache mit Ausweis mitteilen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Nicht verwechseln', detail: 'Die Steuer-Identifikationsnummer ist elfstellig und personenbezogen. Die Steuernummer ist betriebs- oder veranlagungsbezogen und ändert sich bei Umzug oder Zuständigkeitswechsel.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 139a bis 139d Abgabenordnung - Identifikationsmerkmale',
      'Steueridentifikationsnummerverordnung',
    ],
    online: { moeglich: true, hinweis: 'Anforderung online möglich, Zustellung ausschließlich per Post aus Datenschutzgründen.' },
    haeufigeFehler: [
      'Steuer-ID und Steuernummer verwechseln.',
      'Annehmen, die Nummer ändere sich bei Umzug oder Heirat - sie bleibt gleich.',
      'Für Neugeborene eine gesonderte Beantragung erwarten - sie kommt automatisch.',
      'Auskunft per Telefon erwarten.',
    ],
    faq: [
      { frage: 'Wo finde ich meine Steuer-ID am schnellsten?', antwort: 'Auf der Lohnsteuerbescheinigung, dem letzten Steuerbescheid oder dem Informationsschreiben des Bundeszentralamts für Steuern.' },
      { frage: 'Ändert sie sich beim Umzug?', antwort: 'Nein, sie ist lebenslang gleich. Nur die Steuernummer des Finanzamts kann sich ändern.' },
      { frage: 'Mein Kind hat keine Nummer bekommen.', antwort: 'Sie wird automatisch nach der Geburtsanzeige zugeteilt und per Post zugestellt. Kommt sie nicht, fordern Sie sie beim Bundeszentralamt für Steuern an.' },
    ],
    verwandt: ['kindergeld', 'steuerliche-erfassung', 'wohnsitz-anmeldung'],
    eskalation: 'Bei doppelt vergebenen Nummern oder Problemen nach Zuzug an das Bundeszentralamt für Steuern verweisen.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht, bundesweit identisch und kostenfrei.' },
    stand: '2026-08',
  },
  {
    id: 'einkommensteuererklaerung',
    cluster: 'steuern-abgaben',
    name: 'Einkommensteuererklärung abgeben',
    sprechName: 'Einkommensteuererklärung',
    synonyme: ['steuererklärung', 'einkommensteuererklärung', 'steuererklärung abgeben', 'lohnsteuerjahresausgleich', 'steuererklärung frist', 'elster steuererklärung', 'steuern zurückholen', 'steuererklärung machen'],
    leikaBezug: 'Einkommensteuer - Erklärung (LeiKa 99102003)',
    kurzbeschreibung: 'Die Einkommensteuererklärung wird elektronisch über ELSTER beim Finanzamt abgegeben. Pflicht ist sie nur in bestimmten Fällen - freiwillig lohnt sie sich für die meisten Arbeitnehmer, und dafür bleiben vier Jahre Zeit.',
    zustaendigkeit: {
      stelle: 'Finanzamt am Wohnsitz',
      ebene: 'land',
      hinweis: 'Die Steuerverwaltung ist Ländersache, das Einkommensteuerrecht bundeseinheitlich.',
    },
    voraussetzungen: [
      'Pflicht zur Abgabe besteht unter anderem bei: Nebeneinkünften über 410 Euro, Lohnersatzleistungen über 410 Euro (Kurzarbeiter-, Eltern-, Krankengeld - Progressionsvorbehalt), Steuerklassenkombination III/V oder IV mit Faktor, mehreren Arbeitgebern, eingetragenen Freibeträgen, sowie regelmäßig bei Rentnern über dem Grundfreibetrag und bei Selbstständigen.',
      'Freiwillige Abgabe (Antragsveranlagung) steht allen offen.',
      'Elektronische Abgabe über ELSTER ist für Erklärungen mit Gewinneinkünften Pflicht; für Arbeitnehmer dringend empfohlen.',
    ],
    unterlagen: [
      { was: 'ELSTER-Zugang (Zertifikat) oder Online-Ausweisfunktion', pflicht: true },
      { was: 'Steuer-Identifikationsnummer', pflicht: true },
      { was: 'Lohnsteuerbescheinigung', pflicht: false, hinweis: 'Liegt dem Finanzamt elektronisch vor (vorausgefüllte Erklärung); zum Abgleich bereithalten.' },
      { was: 'Belege für Werbungskosten, Sonderausgaben, außergewöhnliche Belastungen, Handwerkerleistungen', pflicht: false, hinweis: 'Seit der Belegvorhaltepflicht nicht mehr mitschicken, aber aufbewahren - das Finanzamt fordert bei Bedarf an.' },
      { was: 'Bescheinigungen über Versicherungen, Spenden, Kapitalerträge', pflicht: false },
    ],
    gebuehren: [
      { position: 'Abgabe der Erklärung', betrag: '0,00 Euro', art: 'keine' },
      { position: 'Verspätungszuschlag bei Pflichtveranlagung', betrag: '0,25 Prozent der festgesetzten Steuer je angefangenem Monat, mindestens 25 Euro monatlich', art: 'bundeseinheitlich', hinweis: 'Wird nach Fristablauf teils zwingend festgesetzt.' },
      { position: 'Steuerberater oder Lohnsteuerhilfeverein', betrag: 'nach Gebührenordnung bzw. Mitgliedsbeitrag (typisch 50 bis 400 Euro)', art: 'sonstige' },
    ],
    fristen: [
      'Pflichtveranlagung ohne Berater: 31. Juli des Folgejahres - für das Steuerjahr 2025 also der 31. Juli 2026.',
      'Mit Steuerberater oder Lohnsteuerhilfeverein: Ende Februar des übernächsten Jahres - für 2025 der 28. Februar 2027.',
      'Freiwillige Abgabe: vier Jahre Zeit - die Erklärung für 2025 kann bis Ende 2029 eingereicht werden.',
      'Einspruch gegen den Steuerbescheid: ein Monat.',
    ],
    bearbeitungsdauer: 'Meist vier bis zwölf Wochen bis zum Bescheid; elektronische Erklärungen werden schneller verarbeitet als Papier.',
    ablauf: [
      { nr: 1, titel: 'Abgabepflicht klären', detail: 'Prüfen Sie, ob einer der Pflichtgründe vorliegt. Rentner erhalten oft erst Jahre später Post vom Finanzamt - die Pflicht bestand trotzdem.', akteur: 'Bürger' },
      { nr: 2, titel: 'ELSTER-Zugang einrichten', detail: 'Registrierung mit Aktivierungscode per Post dauert etwa eine Woche - rechtzeitig vor der Frist anlegen. Alternativ Login mit der Online-Ausweisfunktion.', akteur: 'Bürger' },
      { nr: 3, titel: 'Vorausgefüllte Erklärung abrufen', detail: 'Lohn, Renten, Kranken- und Pflegeversicherungsbeiträge liegen dem Finanzamt elektronisch vor und lassen sich in die Formulare übernehmen.', akteur: 'Bürger' },
      { nr: 4, titel: 'Ausfüllen und absenden', detail: 'Hauptvordruck plus Anlagen (N für Arbeitnehmer, Kind, Vorsorgeaufwand, R für Renten, V für Vermietung, G/S für Gewinneinkünfte). Belege nur aufbewahren, nicht mitsenden.', akteur: 'Bürger' },
      { nr: 5, titel: 'Bescheid prüfen', detail: 'Abweichungen vom eigenen Ansatz sind im Bescheid erläutert. Binnen eines Monats kostenfrei Einspruch einlegen - etwa bei vergessenen oder gestrichenen Posten.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 25, 46 Einkommensteuergesetz - Veranlagung und Pflichtgründe',
      '§ 149 Abgabenordnung - Abgabefristen',
      '§ 152 Abgabenordnung - Verspätungszuschlag',
      '§ 32d, 39 ff. EStG - Kapitalerträge, Lohnsteuerabzugsmerkmale',
    ],
    online: {
      moeglich: true,
      hinweis: 'Vollständig digital über Mein ELSTER (kostenfrei) oder kommerzielle Steuersoftware mit ELSTER-Schnittstelle.',
      voraussetzungen: ['ELSTER-Zertifikat oder Online-Ausweisfunktion'],
    },
    haeufigeFehler: [
      'Die Pflichtveranlagung übersehen - besonders bei Kurzarbeiter- oder Elterngeld über 410 Euro und bei Steuerklasse III/V.',
      'Den ELSTER-Zugang erst am Fristtag beantragen - der Aktivierungscode kommt per Post.',
      'Die freiwillige Erklärung verschenken: Im Schnitt gibt es mehrere hundert Euro zurück.',
      'Belege wegwerfen, obwohl das Finanzamt sie nachfordern kann.',
      'Den Einspruchsmonat verstreichen lassen.',
    ],
    faq: [
      { frage: 'Bis wann muss ich abgeben?', antwort: 'Bei Pflichtveranlagung ohne Berater bis zum 31. Juli des Folgejahres - für 2025 also bis 31. Juli 2026. Mit Berater oder Lohnsteuerhilfeverein bis Ende Februar 2027. Freiwillig haben Sie vier Jahre Zeit.' },
      { frage: 'Muss ich als Rentner eine Erklärung abgeben?', antwort: 'Wenn die steuerpflichtigen Einkünfte über dem Grundfreibetrag liegen, ja. Viele Neurentner rutschen durch Rentenerhöhungen in die Pflicht. Im Zweifel beim Finanzamt nachfragen oder die vereinfachte Veranlagung für Rentner nutzen, wo das Land sie anbietet.' },
      { frage: 'Lohnt sich die freiwillige Abgabe?', antwort: 'Meistens ja - bei Fahrtkosten, Homeoffice, Handwerkerleistungen, Spenden oder schwankendem Lohn. Die durchschnittliche Erstattung liegt bei über 1.000 Euro.' },
      { frage: 'Was passiert bei verspäteter Abgabe?', antwort: 'Verspätungszuschlag von 0,25 Prozent der Steuer je angefangenem Monat, mindestens 25 Euro pro Monat - nach 14 Monaten Verspätung wird er zwingend festgesetzt. Dazu können Zwangsgelder und Schätzungen kommen.' },
    ],
    verwandt: ['steuer-identifikationsnummer', 'steuerklassenwechsel', 'grundsteuer', 'rente-altersrente'],
    eskalation: 'Bei Schätzungsbescheiden, Vollstreckung, Selbstanzeige oder komplexen Einkünften an das Finanzamt beziehungsweise die Steuerberatung verweisen.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Fristen und Zuschläge sind Bundesrecht und gelten überall gleich.' },
    stand: '2026-08',
  },
  {
    id: 'steuerklassenwechsel',
    cluster: 'steuern-abgaben',
    name: 'Steuerklasse wechseln',
    sprechName: 'Steuerklasse wechseln',
    synonyme: ['steuerklasse wechseln', 'steuerklasse ändern', 'steuerklassenwechsel', 'steuerklasse 3 5', 'steuerklasse 4 faktor', 'lohnsteuerklasse', 'steuerklasse nach heirat', 'steuerklasse nach trennung'],
    leikaBezug: 'Lohnsteuerklassenwechsel (LeiKa 99102011)',
    kurzbeschreibung: 'Ehegatten und Lebenspartner können ihre Steuerklassenkombination wechseln - III/V, IV/IV oder IV/IV mit Faktor. Der Antrag läuft über ELSTER oder das Finanzamt, ist kostenfrei und seit 2020 auch mehrfach im Jahr möglich.',
    zustaendigkeit: {
      stelle: 'Finanzamt am Wohnsitz',
      ebene: 'land',
    },
    voraussetzungen: [
      'Für III/V und IV/IV: bestehende Ehe oder eingetragene Lebenspartnerschaft, beide unbeschränkt steuerpflichtig, nicht dauernd getrennt lebend.',
      'Beim Wechsel zu III/V oder zum Faktorverfahren müssen beide Partner den Antrag stellen; der Wechsel zu IV/IV geht auf Antrag nur eines Partners.',
      'Alleinerziehende erhalten Klasse II über den Antrag auf Lohnsteuer-Ermäßigung (Entlastungsbetrag).',
      'Nach der Heirat werden automatisch beide in Klasse IV eingestuft; ein Wechsel ist danach jederzeit möglich.',
    ],
    unterlagen: [
      { was: 'Antrag auf Steuerklassenwechsel bei Ehegatten/Lebenspartnern', pflicht: true, hinweis: 'Über Mein ELSTER oder als Vordruck; bei III/V und Faktor von beiden zu unterschreiben bzw. zu autorisieren.' },
      { was: 'Steuer-Identifikationsnummern beider Partner', pflicht: true },
      { was: 'Beim Faktorverfahren: voraussichtliche Jahresarbeitslöhne beider Partner', pflicht: false },
    ],
    gebuehren: [
      { position: 'Steuerklassenwechsel', betrag: '0,00 Euro', art: 'keine' },
    ],
    fristen: [
      'Antrag bis spätestens 30. November wirkt noch für das laufende Jahr - ab dem Folgemonat der Antragstellung.',
      'Seit 2020 ist der Wechsel mehrfach im Jahr möglich, nicht mehr nur einmal.',
      'Nach Trennung: Im Folgejahr der dauernden Trennung sind die Klassen zwingend zu ändern (I bzw. II).',
    ],
    bearbeitungsdauer: 'Wenige Tage bis zwei Wochen; die neue Klasse gilt ab dem Folgemonat und wird dem Arbeitgeber elektronisch über die ELStAM bereitgestellt (ELStAM = Elektronische LohnSteuerAbzugsMerkmale, die zentrale Datenbank der Abzugsmerkmale).',
    ablauf: [
      { nr: 1, titel: 'Kombination durchrechnen', detail: 'III/V lohnt bei sehr ungleichen Löhnen, führt aber häufig zu Nachzahlungen und zur Pflichtveranlagung. IV/IV mit Faktor verteilt die Steuer verursachungsgerecht. Wichtig: Die Steuerklasse ändert nur den monatlichen Abzug, nicht die Jahressteuer - aber sie beeinflusst Lohnersatzleistungen wie Eltern- und Arbeitslosengeld.', akteur: 'Bürger' },
      { nr: 2, titel: 'Bei geplanter Elternzeit früh handeln', detail: 'Das Elterngeld bemisst sich nach dem Netto der zwölf Monate vor der Geburt bzw. dem Mutterschutz. Ein Wechsel in die günstigere Klasse III zählt nur, wenn er in dieser Zeit überwiegend galt - also mindestens sieben Monate. Deshalb möglichst früh in der Schwangerschaft wechseln.', akteur: 'Bürger' },
      { nr: 3, titel: 'Antrag stellen', detail: 'Über Mein ELSTER (Formular "Steuerklassenwechsel") oder mit dem Papiervordruck beim Finanzamt.', akteur: 'Bürger' },
      { nr: 4, titel: 'Wirkung prüfen', detail: 'Die neue Klasse erscheint auf der nächsten Gehaltsabrechnung. Bei III/V an die Pflicht zur Steuererklärung denken.', akteur: 'Bürger' },
    ],
    rechtsgrundlagen: [
      '§ 38b Einkommensteuergesetz - Steuerklassen',
      '§ 39 Abs. 6 EStG - Steuerklassenwechsel bei Ehegatten',
      '§ 39f EStG - Faktorverfahren',
    ],
    online: {
      moeglich: true,
      hinweis: 'Vollständig über Mein ELSTER; der Papierantrag beim Finanzamt bleibt möglich.',
      voraussetzungen: ['ELSTER-Zertifikat'],
    },
    haeufigeFehler: [
      'Vor der Elternzeit zu spät in Klasse III wechseln - der Elterngeldvorteil greift nur bei überwiegender Geltung im Bemessungszeitraum.',
      'III/V wählen und die Pflicht zur Steuererklärung samt möglicher Nachzahlung übersehen.',
      'Glauben, die Steuerklasse ändere die Jahressteuer - sie verschiebt nur den unterjährigen Abzug.',
      'Nach dauernder Trennung den zwingenden Wechsel zum Jahreswechsel versäumen.',
    ],
    faq: [
      { frage: 'Wie oft darf ich wechseln?', antwort: 'Seit 2020 mehrfach im Jahr. Ein Antrag bis zum 30. November wirkt noch für das laufende Jahr.' },
      { frage: 'Welche Kombination ist die beste?', antwort: 'Bei ähnlichen Einkommen IV/IV. Bei sehr ungleichen Einkommen bringt III/V monatlich mehr Netto für den Besserverdienenden, erzwingt aber die Steuererklärung und endet oft mit Nachzahlung. IV/IV mit Faktor ist die genaueste Variante.' },
      { frage: 'Beeinflusst die Steuerklasse das Elterngeld?', antwort: 'Ja, erheblich - Elterngeld, Arbeitslosengeld, Kranken- und Mutterschaftsgeld bemessen sich nach dem Netto. Ein rechtzeitiger Wechsel kann das Elterngeld deutlich erhöhen; er muss im Bemessungszeitraum überwiegen.' },
      { frage: 'Was passiert nach der Hochzeit?', antwort: 'Beide erhalten automatisch Klasse IV. Wollen Sie III/V oder das Faktorverfahren, stellen Sie gemeinsam den Wechselantrag.' },
    ],
    verwandt: ['einkommensteuererklaerung', 'elterngeld', 'eheschliessung', 'steuer-identifikationsnummer'],
    eskalation: 'Bei Trennungsjahr-Fragen, grenzüberschreitenden Ehen oder Streit über die Kombination an Finanzamt oder Steuerberatung verweisen.',
    belastbarkeit: { quelle: 'bundesrecht', hinweis: 'Bundesrecht, überall gleich; nur die Bearbeitungswege der Finanzämter unterscheiden sich.' },
    stand: '2026-08',
  },
];
