/**
 * Stufe 1 der Wissensbasis: fachliche Cluster entlang der Lebenslagen des
 * Leistungskatalogs (LeiKa), wie sie die Behoerdennummer 115 im Erstkontakt
 * verwendet.
 *
 * Das "grundsatzwissen" ist bewusst die grobe Ebene: Es beantwortet, was in
 * diesem Bereich im Regelfall gilt, bevor die konkrete Leistung feststeht.
 * Der Voice-Bot liest es vor, sobald er den Bereich erkannt hat, und laesst
 * den Anrufer erst danach per Ziffernwahl praezisieren.
 */
export const CLUSTER = [
  {
    id: 'melde-ausweis',
    name: 'Melde- und Ausweisangelegenheiten',
    sprechName: 'Melde- und Ausweisangelegenheiten',
    lebenslagen: ['Umzug', 'Ausweisdokumente', 'Wohnsitz'],
    stichworte: [
      'anmelden', 'ummelden', 'abmelden', 'ummeldung', 'anmeldung', 'wohnsitz', 'wohnung',
      'umgezogen', 'umzug', 'einwohnermeldeamt', 'bürgeramt', 'bürgerbüro', 'meldebescheinigung',
      'personalausweis', 'ausweis', 'perso', 'reisepass', 'pass', 'passfoto', 'führungszeugnis',
      'melderegister', 'meldebestätigung', 'zweitwohnsitz', 'hauptwohnsitz', 'nebenwohnsitz',
      'wohnungsgeberbestätigung', 'ausweis verloren', 'pass abgelaufen', 'eid', 'ausweis-pin',
      'pässe', 'reisepässe', 'urlaub', 'reisedokument', 'ins ausland reisen', 'fliegen', 'verreisen',
    ],
    grundsatzwissen: {
      kurz: 'Melde- und Ausweisangelegenheiten laufen fast immer über das Bürgeramt Ihrer Wohnsitzgemeinde und setzen persönliches Erscheinen mit einem gültigen Ausweisdokument voraus.',
      zustaendigkeit: 'Bürgeramt, Bürgerbüro oder Einwohnermeldeamt der Gemeinde, in der Sie wohnen oder einziehen. Bei Pässen und Ausweisen ist der Hauptwohnsitz maßgeblich.',
      faustregeln: [
        'Für die Anmeldung nach einem Umzug haben Sie zwei Wochen Zeit (§ 17 Bundesmeldegesetz).',
        'Innerhalb Deutschlands gibt es keine Abmeldung beim Wegzug - Sie melden sich nur am neuen Ort an; abgemeldet wird nur bei Wegzug ins Ausland oder bei Aufgabe einer Nebenwohnung.',
        'Der Vermieter muss Ihnen eine Wohnungsgeberbestätigung ausstellen, spätestens zwei Wochen nach Einzug.',
        'Ausweisdokumente sind höchstpersönlich zu beantragen; Fingerabdrücke sind im Personalausweis und Reisepass Pflicht.',
        'Für Ausweisdokumente brauchen Sie ein biometrisches Lichtbild, das seit Mai 2025 digital übermittelt werden muss - Papierfotos werden nicht mehr angenommen.',
        'Ein abgelaufener Ausweis ist keine Ordnungswidrigkeit an sich - die Ausweispflicht verlangt aber ein gültiges Dokument; Bußgelder sind möglich.',
      ],
      typischeUnterlagen: [
        'Gültiger Personalausweis oder Reisepass',
        'Bei Anmeldung: Wohnungsgeberbestätigung des Vermieters',
        'Bei Ausweisdokumenten: biometrisches Lichtbild (digital übermittelt)',
        'Bei Kindern: Geburtsurkunde und Einverständnis beider Sorgeberechtigten',
      ],
      typischeFristen: [
        'Anmeldung nach Einzug: 2 Wochen',
        'Abmeldung bei Wegzug ins Ausland: frühestens 1 Woche vor, spätestens 2 Wochen nach Auszug',
        'Ausstellungsdauer Ausweis/Pass: 3 bis 6 Wochen (Express deutlich kürzer)',
      ],
      typischeKosten: 'An- und Ummeldung sind kostenfrei. Ausweisdokumente kosten bundeseinheitlich (Personalausweis 37,00 Euro, Reisepass 70,00 Euro), Bescheinigungen aus dem Melderegister kosten kommunal meist 5 bis 15 Euro.',
      onlineWege: [
        'Elektronische Wohnsitzanmeldung über BundID in einem wachsenden Teil der Kommunen',
        'Melde- und Aufenthaltsbescheinigungen vielerorts über das kommunale Serviceportal',
        'Führungszeugnis vollständig online über das Portal des Bundesamts für Justiz mit eID',
        'Terminvereinbarung fast überall online - ohne Termin oft keine Bearbeitung',
      ],
      rechtsrahmen: [
        'Bundesmeldegesetz (BMG)',
        'Personalausweisgesetz (PAuswG)',
        'Passgesetz (PassG)',
        'Bundeszentralregistergesetz (BZRG)',
      ],
      haeufigeIrrtuemer: [
        'Man muss sich beim alten Wohnort abmelden - falsch, innerhalb Deutschlands nicht.',
        'Der Mietvertrag reicht als Nachweis - nein, verlangt wird die Wohnungsgeberbestätigung.',
        'Kinderreisepässe gibt es noch - nein, sie sind seit dem 1. Januar 2024 abgeschafft.',
      ],
    },
  },
  {
    id: 'kfz-verkehr',
    name: 'Kraftfahrzeug und Verkehr',
    sprechName: 'Kraftfahrzeug und Verkehr',
    lebenslagen: ['Fahrzeug', 'Führerschein', 'Straßenverkehr'],
    stichworte: [
      'auto', 'kfz', 'fahrzeug', 'zulassen', 'zulassung', 'zulassungsstelle', 'kennzeichen',
      'nummernschild', 'wunschkennzeichen', 'ummelden auto', 'abmelden auto', 'stilllegen',
      'außer betrieb', 'führerschein', 'fahrerlaubnis', 'lappen', 'umtausch führerschein',
      'internationaler führerschein', 'anwohnerparken', 'bewohnerparkausweis', 'parkausweis',
      'feinstaubplakette', 'umweltplakette', 'hu', 'tüv', 'halter', 'motorrad', 'anhänger',
      'saisonkennzeichen', 'kurzzeitkennzeichen', 'rotes kennzeichen', 'schwerbehindertenparkausweis',
    ],
    grundsatzwissen: {
      kurz: 'Fahrzeugangelegenheiten erledigt die Kfz-Zulassungsbehörde des Kreises oder der kreisfreien Stadt, Fahrerlaubnisse die Fahrerlaubnisbehörde - beide sitzen meist im selben Landratsamt oder Straßenverkehrsamt.',
      zustaendigkeit: 'Zulassungsbehörde am Wohnsitz des Halters oder am Standort des Fahrzeugs; Fahrerlaubnisbehörde am Hauptwohnsitz.',
      faustregeln: [
        'Ohne gültige Hauptuntersuchung und ohne eVB-Nummer der Versicherung wird kein Fahrzeug zugelassen.',
        'Zulassungsbescheinigung Teil I ist der frühere Fahrzeugschein, Teil II der frühere Fahrzeugbrief.',
        'Seit der vierten Stufe von i-Kfz lassen sich Zulassung, Umschreibung, Halterwechsel und Außerbetriebsetzung online erledigen, wenn die Papiere die Sicherheitscodes tragen.',
        'Die Kfz-Steuer wird beim Zulassen automatisch per SEPA-Lastschriftmandat eingezogen; ohne Mandat keine Zulassung.',
        'Führerscheine der alten Papier- und Kartenformate müssen bis 19. Januar 2033 gestaffelt in EU-Kartenführerscheine umgetauscht werden.',
        'Bei Fahrzeugkauf haftet der Verkäufer bis zur Umschreibung mit - deshalb Veräußerungsanzeige nicht vergessen.',
      ],
      typischeUnterlagen: [
        'Personalausweis oder Reisepass mit Meldebescheinigung',
        'Zulassungsbescheinigung Teil I und Teil II',
        'eVB-Nummer der Kfz-Versicherung',
        'Nachweis der letzten Hauptuntersuchung',
        'SEPA-Lastschriftmandat für die Kfz-Steuer',
      ],
      typischeFristen: [
        'Umschreibung nach Halterwechsel: unverzüglich, in der Praxis sofort nach Kauf',
        'Ummeldung nach Umzug: unverzüglich nach der Wohnsitzanmeldung',
        'Hauptuntersuchung: alle 24 Monate, Neufahrzeuge nach 36 Monaten',
      ],
      typischeKosten: 'Zulassungsvorgänge kosten nach Gebührenordnung für Maßnahmen im Straßenverkehr meist 12 bis 60 Euro, dazu Schilder für etwa 20 bis 35 Euro. Führerscheinumtausch liegt bei rund 25 bis 30 Euro.',
      onlineWege: [
        'i-Kfz-Portal der Zulassungsbehörde für Zulassung, Umschreibung und Außerbetriebsetzung',
        'Wunschkennzeichen-Reservierung online, meist gegen kleine Gebühr',
        'Terminbuchung bei der Zulassungsstelle - in Ballungsräumen Wochen im Voraus',
      ],
      rechtsrahmen: [
        'Fahrzeug-Zulassungsverordnung (FZV)',
        'Straßenverkehrs-Zulassungs-Ordnung (StVZO)',
        'Fahrerlaubnis-Verordnung (FeV)',
        'Gebührenordnung für Maßnahmen im Straßenverkehr (GebOSt)',
      ],
      haeufigeIrrtuemer: [
        'Der Verkäufer meldet das Auto ab, damit ist alles erledigt - nein, der Käufer muss umschreiben.',
        'Die Versicherung kümmert sich um die Zulassung - nein, sie liefert nur die eVB-Nummer.',
        'Ein außer Betrieb gesetztes Fahrzeug darf noch bewegt werden - nein, nur mit Kurzzeitkennzeichen.',
      ],
    },
  },
  {
    id: 'familie-kinder',
    name: 'Familie, Kinder und Erziehung',
    sprechName: 'Familie, Kinder und Erziehung',
    lebenslagen: ['Geburt', 'Kinderbetreuung', 'Familienleistungen'],
    stichworte: [
      'geburt', 'geburtsurkunde', 'baby', 'kind', 'kinder', 'kindergeld', 'elterngeld',
      'elternzeit', 'kita', 'kindergarten', 'krippe', 'betreuungsplatz', 'kitagutschein',
      'unterhaltsvorschuss', 'vaterschaft', 'vaterschaftsanerkennung', 'sorgerecht',
      'sorgeerklärung', 'jugendamt', 'namensänderung kind', 'mutterschutz', 'kinderzuschlag',
      'alleinerziehend', 'pflegekind', 'adoption', 'beistandschaft',
    ],
    grundsatzwissen: {
      kurz: 'Familienleistungen verteilen sich auf drei Stellen: Standesamt für Personenstand, Jugendamt für Betreuung und Sorge, Familienkasse und Elterngeldstelle für Geldleistungen.',
      zustaendigkeit: 'Standesamt des Geburtsortes, Jugendamt der Wohnsitzgemeinde, Familienkasse der Bundesagentur für Arbeit, Elterngeldstelle des Landes oder Kreises.',
      faustregeln: [
        'Die Geburt wird binnen einer Woche beim Standesamt des Geburtsortes angezeigt; bei Klinikgeburten übernimmt das meist die Klinik.',
        'Kindergeld wird nur noch für sechs Monate rückwirkend gezahlt - stellen Sie den Antrag zügig.',
        'Elterngeld wird ebenfalls nur drei Monate rückwirkend gezahlt und setzt die Geburtsurkunde mit Verwendungszweck Elterngeld voraus.',
        'Sind die Eltern nicht miteinander verheiratet, entsteht das gemeinsame Sorgerecht erst durch Sorgeerklärungen beim Jugendamt oder Notar.',
        'Für einen Kita-Platz gilt ein Rechtsanspruch ab dem vollendeten ersten Lebensjahr - anzumelden ist meist über ein kommunales Vormerksystem, oft ein Jahr im Voraus.',
        'Beurkundungen beim Jugendamt - Vaterschaft, Unterhalt, Sorgeerklärung - sind kostenfrei.',
      ],
      typischeUnterlagen: [
        'Geburtsurkunde des Kindes, häufig in mehrfacher Ausfertigung mit unterschiedlichem Verwendungszweck',
        'Personalausweise beider Elternteile',
        'Heiratsurkunde oder Vaterschaftsanerkennung',
        'Einkommensnachweise der letzten zwölf Monate vor der Geburt',
        'Bescheinigung der Krankenkasse über Mutterschaftsleistungen',
      ],
      typischeFristen: [
        'Geburtsanzeige: 1 Woche',
        'Kindergeld: 6 Monate rückwirkend',
        'Elterngeld: 3 Monate rückwirkend',
        'Elternzeit beim Arbeitgeber: 7 Wochen vor Beginn anmelden',
      ],
      typischeKosten: 'Beurkundungen beim Jugendamt und die Anzeige der Geburt sind kostenfrei. Urkunden des Standesamts kosten etwa 12 bis 15 Euro je Ausfertigung. Kita-Beiträge sind kommunal geregelt und meist einkommensabhängig.',
      onlineWege: [
        'Kindergeldantrag online bei der Familienkasse',
        'Elterngeld über ElterngeldDigital in den meisten Ländern',
        'Kita-Platzvergabe über kommunale Vormerkportale',
        'Kombinierte Geburtsanzeige über den Onlinedienst mancher Standesämter',
      ],
      rechtsrahmen: [
        'Personenstandsgesetz (PStG)',
        'Bundeselterngeld- und Elternzeitgesetz (BEEG)',
        'Einkommensteuergesetz und Bundeskindergeldgesetz',
        'Achtes Buch Sozialgesetzbuch (SGB VIII)',
        'Unterhaltsvorschussgesetz (UhVorschG)',
      ],
      haeufigeIrrtuemer: [
        'Kindergeld wird automatisch nach der Geburt gezahlt - nein, es ist zu beantragen.',
        'Unverheiratete Väter haben automatisch das Sorgerecht - nein, nur mit Sorgeerklärung.',
        'Eine Geburtsurkunde reicht für alles - in der Praxis brauchen Sie mehrere Ausfertigungen.',
      ],
    },
  },
  {
    id: 'ehe-tod',
    name: 'Eheschließung, Partnerschaft und Sterbefall',
    sprechName: 'Eheschließung und Sterbefall',
    lebenslagen: ['Heirat', 'Trennung', 'Todesfall'],
    stichworte: [
      'heiraten', 'hochzeit', 'ehe', 'eheschließung', 'standesamt', 'trauung', 'aufgebot',
      'ehefähigkeitszeugnis', 'namensänderung ehe', 'scheidung', 'lebenspartnerschaft',
      'sterbefall', 'todesfall', 'gestorben', 'verstorben', 'sterbeurkunde', 'beerdigung',
      'bestattung', 'friedhof', 'grab', 'erbschein', 'nachlass', 'kirchenaustritt',
      'testament', 'urkunde', 'eheurkunde',
    ],
    grundsatzwissen: {
      kurz: 'Alle Personenstandsfälle - Eheschließung, Lebenspartnerschaft, Sterbefall - laufen über das Standesamt; die Bestattung selbst regelt das Landesrecht mit sehr unterschiedlichen Fristen.',
      zustaendigkeit: 'Standesamt am Wohnsitz für die Anmeldung der Eheschließung, Standesamt des Sterbeortes für die Beurkundung des Todes, Friedhofsverwaltung oder Ordnungsamt für die Bestattung.',
      faustregeln: [
        'Die Eheschließung wird beim Standesamt des Wohnsitzes angemeldet, geheiratet werden darf danach bei jedem deutschen Standesamt.',
        'Die Anmeldung ist sechs Monate gültig - zu früh anmelden bringt nichts.',
        'Ein Sterbefall ist spätestens am dritten Werktag nach dem Tod beim Standesamt anzuzeigen.',
        'Sterbeurkunden brauchen Sie mehrfach: für Rentenversicherung, Versicherungen, Banken, Nachlassgericht.',
        'Die Bestattungsfristen sind Landesrecht und liegen meist zwischen vier und zehn Tagen; es gilt in Deutschland Friedhofszwang mit wenigen Ausnahmen.',
        'Der Kirchenaustritt wird je nach Bundesland beim Standesamt oder beim Amtsgericht erklärt und wirkt erst ab dem Folgemonat auf die Kirchensteuer.',
      ],
      typischeUnterlagen: [
        'Gültiger Personalausweis oder Reisepass',
        'Beglaubigter Ausdruck aus dem Geburtenregister, nicht älter als sechs Monate',
        'Erweiterte Meldebescheinigung mit Familienstand',
        'Bei Vorehen: Eheurkunde mit Auflösungsvermerk oder rechtskräftiges Scheidungsurteil',
        'Im Sterbefall: Todesbescheinigung des Arztes, Personalausweis und Urkunden der verstorbenen Person',
      ],
      typischeFristen: [
        'Anzeige eines Sterbefalls: spätestens 3. Werktag',
        'Gültigkeit der Eheanmeldung: 6 Monate',
        'Bestattung: je nach Land meist 4 bis 10 Tage nach Eintritt des Todes',
        'Ausschlagung einer Erbschaft: 6 Wochen ab Kenntnis',
      ],
      typischeKosten: 'Anmeldung der Eheschließung etwa 40 bis 90 Euro je nach Konstellation, jede Urkunde etwa 12 bis 15 Euro, Trauung außerhalb der Amtsräume oder am Wochenende mit deutlichem Zuschlag. Bestattungskosten trägt die Familie; bei Mittellosigkeit springt das Sozialamt ein.',
      onlineWege: [
        'Voranmeldung der Eheschließung über kommunale Portale',
        'Urkundenbestellung beim Standesamt online',
        'Terminvergabe für Trauungen online',
      ],
      rechtsrahmen: [
        'Personenstandsgesetz (PStG)',
        'Bürgerliches Gesetzbuch, Buch 4 (Familienrecht) und Buch 5 (Erbrecht)',
        'Bestattungsgesetze der Länder',
        'Kirchenaustrittsgesetze der Länder',
      ],
      haeufigeIrrtuemer: [
        'Man kann spontan heiraten - nein, ohne Anmeldung und Prüfung der Ehefähigkeit geht nichts.',
        'Die Sterbeurkunde stellt der Arzt aus - nein, der Arzt stellt die Todesbescheinigung, die Urkunde kommt vom Standesamt.',
        'Der Kirchenaustritt wirkt sofort - nein, für die Kirchensteuer meist ab dem Folgemonat.',
      ],
    },
  },
  {
    id: 'arbeit-soziales',
    name: 'Arbeit, Soziales und Existenzsicherung',
    sprechName: 'Arbeit und Soziales',
    lebenslagen: ['Arbeitslosigkeit', 'Existenzsicherung', 'Behinderung', 'Wohnen'],
    stichworte: [
      'arbeitslos', 'arbeitslosengeld', 'alg', 'bürgergeld', 'hartz', 'grundsicherung',
      'jobcenter', 'arbeitsagentur', 'sozialamt', 'sozialhilfe', 'wohngeld', 'mietzuschuss',
      'lastenzuschuss', 'schwerbehindertenausweis', 'behinderung', 'grad der behinderung',
      'gdb', 'versorgungsamt', 'bildung und teilhabe', 'but', 'pflegegrad', 'pflege',
      'rente', 'grundsicherung im alter', 'kinderzuschlag', 'schulden', 'wohnberechtigungsschein',
      'gehalt', 'lohn', 'kündigung', 'gekündigt', 'entlassen', 'job verloren', 'arbeitgeber',
      'existenzminimum', 'notlage', 'kein einkommen', 'miete kann ich nicht zahlen', 'aufstocken',
      'kein geld', 'habe kein geld', 'mittellos', 'pleite', 'kann nichts bezahlen', 'brauche geld',
    ],
    grundsatzwissen: {
      kurz: 'Sozialleistungen sind fast immer antragsgebunden, einkommensabhängig und beginnen frühestens im Monat der Antragstellung - deshalb gilt: lieber formlos sofort beantragen und Unterlagen nachreichen.',
      zustaendigkeit: 'Jobcenter für Bürgergeld, Agentur für Arbeit für Arbeitslosengeld, Sozialamt der Kommune für Hilfe zum Lebensunterhalt und Grundsicherung im Alter, Wohngeldstelle der Kommune, Versorgungsamt für Schwerbehindertenausweise.',
      faustregeln: [
        'Kein Antrag, kein Geld - Sozialleistungen wirken grundsätzlich nicht rückwirkend, sondern ab Antragsmonat.',
        'Ein formloser Antrag per Schreiben, Mail oder Telefon wahrt das Datum; das Formular können Sie nachreichen.',
        'Arbeitslos melden müssen Sie sich spätestens am ersten Tag der Arbeitslosigkeit, arbeitsuchend bereits drei Monate vor Vertragsende oder binnen drei Tagen nach Kenntnis.',
        'Wer Sozialleistungen bezieht, ist mitwirkungspflichtig: Änderungen von Einkommen, Wohnsituation und Vermögen sind unverzüglich anzuzeigen.',
        'Gegen jeden Bescheid können Sie binnen eines Monats Widerspruch einlegen; Widerspruch und Klage im Sozialrecht sind gerichtskostenfrei.',
        'Wohngeld und Bürgergeld schließen sich aus - wer Bürgergeld bezieht, bekommt kein Wohngeld und umgekehrt.',
      ],
      typischeUnterlagen: [
        'Personalausweis und Meldebescheinigung',
        'Einkommensnachweise aller Haushaltsmitglieder',
        'Mietvertrag und aktuelle Nebenkostenabrechnung',
        'Kontoauszüge der letzten drei bis sechs Monate',
        'Bescheide über andere Sozialleistungen',
      ],
      typischeFristen: [
        'Arbeitsuchendmeldung: 3 Monate vor Ende des Arbeitsverhältnisses',
        'Arbeitslosmeldung: spätestens am ersten Tag der Arbeitslosigkeit',
        'Widerspruch gegen Bescheide: 1 Monat',
        'Weiterbewilligungsantrag Bürgergeld: etwa 2 Monate vor Ablauf des Bewilligungszeitraums',
      ],
      typischeKosten: 'Anträge auf Sozialleistungen sind kostenfrei, ebenso Widerspruchsverfahren. Der Schwerbehindertenausweis wird gebührenfrei ausgestellt.',
      onlineWege: [
        'jobcenter.digital und arbeitsagentur.de für Bürgergeld und Arbeitslosengeld',
        'Wohngeldantrag über Landesportale in vielen Bundesländern',
        'Schwerbehindertenantrag über die Portale der Versorgungsverwaltung',
      ],
      rechtsrahmen: [
        'Zweites Buch Sozialgesetzbuch (SGB II) - Bürgergeld',
        'Drittes Buch Sozialgesetzbuch (SGB III) - Arbeitsförderung',
        'Neuntes Buch Sozialgesetzbuch (SGB IX) - Rehabilitation und Teilhabe',
        'Zwölftes Buch Sozialgesetzbuch (SGB XII) - Sozialhilfe',
        'Wohngeldgesetz (WoGG)',
      ],
      haeufigeIrrtuemer: [
        'Man bekommt Leistungen rückwirkend ab Eintritt der Notlage - nein, ab Antragstellung.',
        'Wer ein Auto besitzt, bekommt kein Bürgergeld - ein angemessenes Fahrzeug bleibt geschützt.',
        'Widerspruch kostet Geld - nein, das sozialrechtliche Vorverfahren ist kostenfrei.',
      ],
    },
  },
  {
    id: 'gewerbe-wirtschaft',
    name: 'Gewerbe, Wirtschaft und Selbstständigkeit',
    sprechName: 'Gewerbe und Wirtschaft',
    lebenslagen: ['Existenzgründung', 'Unternehmen', 'Gaststätte'],
    stichworte: [
      'gewerbe', 'gewerbeanmeldung', 'gewerbeschein', 'selbstständig', 'selbständig',
      'firma', 'unternehmen', 'gründen', 'gründung', 'gewerbeamt', 'gewerbeummeldung',
      'gewerbeabmeldung', 'reisegewerbe', 'gaststätte', 'schankerlaubnis', 'restaurant',
      'imbiss', 'handwerksrolle', 'handwerkskammer', 'ihk', 'freiberufler', 'kleingewerbe',
      'gewerbezentralregister', 'führungszeugnis behörde', 'steuernummer', 'finanzamt',
      'gewerbesteuer', 'marktstand', 'sondernutzung', 'makler', 'bewachungsgewerbe',
      'betrieb', 'betrieb schließen', 'betrieb aufgeben', 'geschäftsaufgabe', 'laden eröffnen',
      'geschäft', 'betriebsstätte', 'gewerbetreibender', 'nebenberuflich selbstständig',
    ],
    grundsatzwissen: {
      kurz: 'Wer selbstständig gewerblich tätig wird, meldet das Gewerbe beim Gewerbeamt an - das löst automatisch Meldungen an Finanzamt, IHK oder Handwerkskammer und Berufsgenossenschaft aus.',
      zustaendigkeit: 'Gewerbeamt oder Ordnungsamt der Gemeinde, in der die Betriebsstätte liegt. Für erlaubnispflichtige Gewerbe zusätzlich Fachbehörden.',
      faustregeln: [
        'Freie Berufe - Ärzte, Anwälte, Künstler, viele beratende Tätigkeiten - melden kein Gewerbe an, sondern nur beim Finanzamt.',
        'Die Anmeldung muss bei Aufnahme der Tätigkeit erfolgen, nicht später; rückwirkende Anmeldungen sind möglich, aber bußgeldbewehrt.',
        'Bestimmte Gewerbe sind erlaubnispflichtig: Gaststätten, Bewachung, Makler, Arbeitnehmerüberlassung, Spielhallen, Personenbeförderung.',
        'Zulassungspflichtige Handwerke nach Anlage A der Handwerksordnung setzen die Eintragung in die Handwerksrolle voraus - meist mit Meisterbrief.',
        'Nach der Gewerbeanmeldung folgt binnen eines Monats der Fragebogen zur steuerlichen Erfassung über ELSTER.',
        'Die IHK-Mitgliedschaft ist Pflicht, Kleinunternehmen sind aber beitragsfrei gestellt.',
      ],
      typischeUnterlagen: [
        'Personalausweis oder Reisepass, bei Nicht-EU-Bürgern Aufenthaltstitel mit Erwerbserlaubnis',
        'Bei erlaubnispflichtigen Gewerben: Führungszeugnis zur Vorlage bei einer Behörde und Auskunft aus dem Gewerbezentralregister',
        'Bei Handwerk: Handwerkskarte oder Ausnahmebewilligung',
        'Bei juristischen Personen: Handelsregisterauszug und Gesellschaftsvertrag',
      ],
      typischeFristen: [
        'Gewerbeanmeldung: mit Aufnahme der Tätigkeit',
        'Fragebogen zur steuerlichen Erfassung: 1 Monat nach Anmeldung',
        'Anmeldung bei der Berufsgenossenschaft: 1 Woche nach Gründung',
        'Gewerbeabmeldung: bei Betriebsaufgabe unverzüglich',
      ],
      typischeKosten: 'Die Gewerbeanmeldung kostet je nach kommunaler Satzung etwa 20 bis 65 Euro, Ummeldung und Abmeldung etwas weniger. Gaststättenerlaubnisse liegen deutlich höher, oft 200 bis 1.000 Euro.',
      onlineWege: [
        'Gewerbeanmeldung online über kommunale Portale und den bundesweiten Einheitlichen Ansprechpartner',
        'Fragebogen zur steuerlichen Erfassung ausschließlich elektronisch über ELSTER',
        'Auskunft aus dem Gewerbezentralregister online beim Bundesamt für Justiz',
      ],
      rechtsrahmen: [
        'Gewerbeordnung (GewO)',
        'Handwerksordnung (HwO)',
        'Gaststättengesetze der Länder',
        'Abgabenordnung (AO)',
      ],
      haeufigeIrrtuemer: [
        'Ein Kleingewerbe muss nicht angemeldet werden - doch, jede gewerbliche Tätigkeit ist anzuzeigen.',
        'Mit dem Gewerbeschein habe ich eine Steuernummer - nein, die kommt separat vom Finanzamt.',
        'Der Gewerbeschein ist eine Erlaubnis - nein, er ist nur eine Empfangsbestätigung der Anzeige.',
      ],
    },
  },
  {
    id: 'bauen-wohnen',
    name: 'Bauen, Wohnen und Grundstücke',
    sprechName: 'Bauen und Wohnen',
    lebenslagen: ['Bauvorhaben', 'Immobilie', 'Wohnraum'],
    stichworte: [
      'bauen', 'bauantrag', 'baugenehmigung', 'bauamt', 'bauvoranfrage', 'anbau', 'carport',
      'garage', 'gartenhaus', 'wintergarten', 'dachausbau', 'nutzungsänderung', 'abriss',
      'denkmalschutz', 'denkmal', 'bebauungsplan', 'grundbuch', 'grundsteuer', 'einheitswert',
      'wohnberechtigungsschein', 'wbs', 'sozialwohnung', 'abgeschlossenheitsbescheinigung',
      'schwarzbau', 'stellplatz', 'baulast', 'vermessung', 'liegenschaftskataster',
    ],
    grundsatzwissen: {
      kurz: 'Bauen ist Landesrecht: Die Landesbauordnung entscheidet, ob Ihr Vorhaben genehmigungspflichtig, verfahrensfrei oder nur anzeigepflichtig ist - die untere Bauaufsichtsbehörde des Kreises setzt das um.',
      zustaendigkeit: 'Untere Bauaufsichtsbehörde beim Landkreis oder der kreisfreien Stadt; Bauanträge werden über die Gemeinde eingereicht, die das gemeindliche Einvernehmen erteilt.',
      faustregeln: [
        'Verfahrensfrei heißt nicht regelfrei: Auch ein genehmigungsfreies Gartenhaus muss Abstandsflächen, Bebauungsplan und Nachbarrecht einhalten.',
        'Bauanträge sind mit wenigen Ausnahmen von einer bauvorlageberechtigten Person - Architekt oder Bauingenieur - zu unterschreiben.',
        'Eine Bauvoranfrage klärt Einzelfragen verbindlich vorab und ist meist drei Jahre gültig - das spart bei unklarer Lage viel Geld.',
        'Baugenehmigungen erlöschen in der Regel, wenn nicht binnen drei Jahren mit dem Bau begonnen wird.',
        'Steht das Gebäude unter Denkmalschutz, brauchen Sie zusätzlich eine denkmalrechtliche Erlaubnis - auch für Fenster, Farbe und Dach.',
        'Die Grundsteuer wird seit 2025 nach neuem Recht erhoben; Grundlage ist der Grundsteuerwert des Finanzamts, den Hebesatz setzt die Gemeinde.',
      ],
      typischeUnterlagen: [
        'Bauantragsformular des Landes in mehrfacher Ausfertigung',
        'Lageplan auf Grundlage der amtlichen Liegenschaftskarte',
        'Bauzeichnungen: Grundrisse, Schnitte, Ansichten, meist im Maßstab 1 zu 100',
        'Baubeschreibung und Berechnung von Brutto-Rauminhalt und Grundflächenzahl',
        'Standsicherheits-, Wärmeschutz- und Entwässerungsnachweise',
        'Nachweis der Bauvorlageberechtigung',
      ],
      typischeFristen: [
        'Gemeindliches Einvernehmen: 2 Monate',
        'Genehmigungsfiktion in vielen Ländern: 3 Monate nach vollständigen Unterlagen',
        'Geltungsdauer der Baugenehmigung: meist 3 Jahre, verlängerbar',
        'Nachbarwiderspruch: 1 Monat nach Zustellung',
      ],
      typischeKosten: 'Baugenehmigungsgebühren richten sich nach den Rohbaukosten und liegen meist bei 0,5 bis 1 Prozent der Bausumme, mindestens etwa 100 Euro. Eine Bauvoranfrage kostet häufig 50 bis 500 Euro.',
      onlineWege: [
        'Digitaler Bauantrag über Landesportale in fast allen Bundesländern',
        'Bebauungspläne und Geoportale online einsehbar',
        'Grundsteuererklärung über ELSTER',
      ],
      rechtsrahmen: [
        'Baugesetzbuch (BauGB)',
        'Landesbauordnungen der Länder',
        'Baunutzungsverordnung (BauNVO)',
        'Grundsteuergesetz (GrStG)',
        'Denkmalschutzgesetze der Länder',
      ],
      haeufigeIrrtuemer: [
        'Auf meinem Grundstück darf ich bauen, was ich will - nein, es gilt der Bebauungsplan.',
        'Ein Gartenhaus unter zehn Kubikmetern ist immer erlaubt - die Grenzen unterscheiden sich je Land erheblich.',
        'Der Nachbar muss zustimmen - nur bei Abweichungen; ansonsten wird er nur beteiligt.',
      ],
    },
  },
  {
    id: 'auslaender-einbuergerung',
    name: 'Aufenthalt, Migration und Einbürgerung',
    sprechName: 'Aufenthalt und Einbürgerung',
    lebenslagen: ['Zuwanderung', 'Aufenthaltstitel', 'Staatsangehörigkeit'],
    stichworte: [
      'aufenthalt', 'aufenthaltstitel', 'aufenthaltserlaubnis', 'niederlassungserlaubnis',
      'ausländerbehörde', 'visum', 'blaue karte', 'blue card', 'einbürgerung', 'staatsangehörigkeit',
      'pass beantragen ausländer', 'verpflichtungserklärung', 'einladung', 'asyl', 'duldung',
      'fiktionsbescheinigung', 'arbeitserlaubnis', 'anerkennung abschluss', 'zeugnisanerkennung',
      'integrationskurs', 'aufenthaltsgestattung', 'daueraufenthalt eu', 'familiennachzug',
    ],
    grundsatzwissen: {
      kurz: 'Aufenthaltsrechtliche Anliegen bearbeitet die Ausländerbehörde am Wohnort; Einbürgerungen laufen über die Einbürgerungsbehörde, die je nach Land bei Kreis, Stadt oder Bezirksregierung sitzt.',
      zustaendigkeit: 'Ausländerbehörde der Kommune oder des Kreises; Auslandsvertretungen für Visa; Einbürgerungsbehörde für Staatsangehörigkeitsfragen.',
      faustregeln: [
        'Anträge auf Verlängerung eines Aufenthaltstitels stellen Sie rechtzeitig vor Ablauf - danach droht illegaler Aufenthalt; bei rechtzeitigem Antrag gilt die Fiktionswirkung.',
        'Seit der Reform vom Juni 2024 ist die Einbürgerung regelmäßig nach fünf Jahren rechtmäßigem Aufenthalt möglich, bei besonderen Integrationsleistungen nach drei Jahren.',
        'Mehrstaatigkeit wird seit derselben Reform grundsätzlich hingenommen - die frühere Aufgabe der alten Staatsangehörigkeit entfällt.',
        'Voraussetzung für die Einbürgerung ist regelmäßig die eigenständige Sicherung des Lebensunterhalts ohne Sozialleistungen.',
        'Sprachnachweis B1 und der Einbürgerungstest sind Standard; für die Blaue Karte EU zählt hingegen das Gehalt und ein anerkannter Hochschulabschluss.',
        'Ausländische Berufsabschlüsse müssen für reglementierte Berufe anerkannt werden - zuständig ist je nach Beruf die Kammer, das Land oder die ZAB.',
      ],
      typischeUnterlagen: [
        'Nationalpass und bisheriger Aufenthaltstitel',
        'Biometrisches Lichtbild',
        'Meldebescheinigung und Mietvertrag',
        'Nachweis über Lebensunterhalt: Arbeitsvertrag, Gehaltsabrechnungen, Steuerbescheide',
        'Nachweis über Krankenversicherung',
        'Sprachzertifikate und Bildungsnachweise',
      ],
      typischeFristen: [
        'Verlängerungsantrag: möglichst 8 Wochen vor Ablauf des Titels',
        'Anzeige des Wohnungswechsels bei der Ausländerbehörde: unverzüglich',
        'Bearbeitungsdauer Einbürgerung: häufig 12 bis 24 Monate',
      ],
      typischeKosten: 'Aufenthaltserlaubnis meist 100 Euro, Niederlassungserlaubnis 113 bis 147 Euro, Blaue Karte EU 100 Euro, Einbürgerung 255 Euro für Erwachsene und 51 Euro für miteingebürgerte Kinder. Die Verpflichtungserklärung kostet 29 Euro.',
      onlineWege: [
        'Online-Terminvergabe der Ausländerbehörden, teilweise mit Warteliste',
        'Digitale Antragsassistenten mehrerer Länder für Aufenthalt und Einbürgerung',
        'Anerkennungsportal des Bundes für ausländische Berufsqualifikationen',
      ],
      rechtsrahmen: [
        'Aufenthaltsgesetz (AufenthG)',
        'Aufenthaltsverordnung (AufenthV)',
        'Staatsangehörigkeitsgesetz (StAG)',
        'Freizügigkeitsgesetz/EU',
        'Berufsqualifikationsfeststellungsgesetz (BQFG)',
      ],
      haeufigeIrrtuemer: [
        'Nach acht Jahren wird man automatisch eingebürgert - nein, es gilt ein Antragsverfahren, seit 2024 in der Regel nach fünf Jahren.',
        'Mit einem Touristenvisum darf man arbeiten - nein, die Erwerbstätigkeit muss der Titel erlauben.',
        'Die Fiktionsbescheinigung ist ein Aufenthaltstitel - sie sichert nur den Status bis zur Entscheidung.',
      ],
    },
  },
  {
    id: 'umwelt-abfall-tiere',
    name: 'Umwelt, Abfall und Tiere',
    sprechName: 'Umwelt, Abfall und Tiere',
    lebenslagen: ['Abfallentsorgung', 'Tierhaltung', 'Umwelt'],
    stichworte: [
      'müll', 'abfall', 'sperrmüll', 'mülltonne', 'restmüll', 'biotonne', 'gelber sack',
      'wertstoffhof', 'recyclinghof', 'grünschnitt', 'entsorgung', 'schadstoffmobil',
      'hund', 'hundesteuer', 'hundemarke', 'listenhund', 'kampfhund', 'katze', 'tierhaltung',
      'baum fällen', 'baumfällgenehmigung', 'baumschutz', 'fundbüro', 'fundsache', 'gefunden',
      'lärm', 'ruhestörung', 'schrottauto', 'wespennest', 'taubenplage',
    ],
    grundsatzwissen: {
      kurz: 'Abfall, Tierhaltung und Ortsbild sind klassisch kommunale Themen - hier entscheiden Satzungen der Gemeinde oder des Kreises, weshalb sich Regeln und Preise von Ort zu Ort deutlich unterscheiden.',
      zustaendigkeit: 'Abfallwirtschaftsbetrieb oder Entsorgungsbetrieb des Kreises, Steueramt der Gemeinde für die Hundesteuer, Ordnungsamt für Tierhaltung und Lärm, Untere Naturschutzbehörde für Baumfällungen.',
      faustregeln: [
        'Es gilt ein Anschluss- und Benutzungszwang für die kommunale Abfallentsorgung - Restmülltonnen sind Pflicht, nicht Wahl.',
        'Sperrmüll wird auf Abruf abgeholt; die Zahl der Freiabholungen pro Jahr steht in der Abfallsatzung.',
        'Die Hundesteuer ist binnen zwei Wochen bis einem Monat nach Aufnahme des Hundes anzumelden - Fristen setzt die kommunale Satzung.',
        'Der zweite und jeder weitere Hund kostet fast überall deutlich mehr, Listenhunde ein Vielfaches.',
        'Baumfällungen auf dem eigenen Grundstück brauchen sehr oft eine Genehmigung nach kommunaler Baumschutzsatzung, gemessen am Stammumfang in einem Meter Höhe.',
        'Von 1. März bis 30. September gilt bundesweit das Rückschnittverbot für Hecken und Gehölze nach Bundesnaturschutzgesetz.',
      ],
      typischeUnterlagen: [
        'Personalausweis und Adressnachweis',
        'Bei Hunden: Nachweis über Chip und Impfung, bei Listenhunden Wesenstest und Sachkundenachweis',
        'Bei Baumfällung: Lageplan, Fotos, Angabe von Baumart und Stammumfang',
        'Bei Sperrmüll: Kundennummer des Abfallbetriebs',
      ],
      typischeFristen: [
        'Hundesteuer-Anmeldung: meist 2 Wochen bis 1 Monat',
        'Sperrmüllabholung: Vorlauf typischerweise 1 bis 6 Wochen',
        'Fundsachen: 6 Monate Aufbewahrung, danach Anspruch des Finders',
        'Rückschnittverbot: 1. März bis 30. September',
      ],
      typischeKosten: 'Hundesteuer je nach Gemeinde etwa 30 bis 180 Euro im Jahr für den ersten Hund. Abfallgebühren richten sich nach Tonnengröße und Leerungsrhythmus. Baumfällgenehmigungen kosten oft 20 bis 100 Euro, teils mit Ersatzpflanzung als Auflage.',
      onlineWege: [
        'Sperrmüllanmeldung und Abfallkalender über die Portale der Entsorger',
        'Hundesteuer-Anmeldung über kommunale Serviceportale',
        'Fundsachen-Recherche in Online-Fundbüros',
      ],
      rechtsrahmen: [
        'Kreislaufwirtschaftsgesetz (KrWG)',
        'Kommunale Abfall-, Hundesteuer- und Baumschutzsatzungen',
        'Bundesnaturschutzgesetz (BNatSchG)',
        'Landeshundegesetze',
      ],
      haeufigeIrrtuemer: [
        'Wer keinen Müll produziert, braucht keine Tonne - der Anschlusszwang gilt trotzdem.',
        'Auf dem eigenen Grundstück darf ich jeden Baum fällen - meist nein.',
        'Ein gefundenes Handy darf man behalten - nein, ab 10 Euro Wert besteht Anzeigepflicht.',
      ],
    },
  },
  {
    id: 'ordnung-bussgeld',
    name: 'Ordnung, Bußgeld und öffentlicher Raum',
    sprechName: 'Ordnung und Bußgeld',
    lebenslagen: ['Ordnungswidrigkeit', 'Veranstaltung', 'Sicherheit'],
    stichworte: [
      'bußgeld', 'bußgeldbescheid', 'knöllchen', 'strafzettel', 'verwarnung', 'einspruch',
      'punkte', 'flensburg', 'fahrverbot', 'blitzer', 'anhörungsbogen', 'ordnungsamt',
      'veranstaltung', 'straßenfest', 'demonstration', 'versammlung', 'sondernutzung',
      'sondernutzungserlaubnis', 'umzug anmelden', 'container', 'gerüst', 'halteverbot',
      'waffenbesitzkarte', 'jagdschein', 'kleiner waffenschein', 'sperrzeit', 'lärmschutz',
    ],
    grundsatzwissen: {
      kurz: 'Ordnungsangelegenheiten liegen beim Ordnungsamt der Gemeinde oder der Bußgeldstelle des Kreises - entscheidend sind hier meist kurze Rechtsbehelfsfristen von genau zwei Wochen.',
      zustaendigkeit: 'Ordnungsamt der Gemeinde, zentrale Bußgeldstelle des Kreises oder des Landes, Versammlungsbehörde für Demonstrationen, Straßenbaulastträger für Sondernutzungen.',
      faustregeln: [
        'Gegen einen Bußgeldbescheid haben Sie genau zwei Wochen ab Zustellung Zeit für den Einspruch - die Frist ist eine Ausschlussfrist.',
        'Ein Anhörungsbogen ist noch kein Bescheid; Angaben zur Person sind Pflicht, Angaben zur Sache nicht.',
        'Eine Verwarnung mit Verwarnungsgeld bis 55 Euro wird erst mit Ihrer Zahlung wirksam - danach ist sie nicht mehr angreifbar.',
        'Als Halter müssen Sie nicht sagen, wer gefahren ist, es kann aber ein Fahrtenbuch angeordnet werden.',
        'Versammlungen unter freiem Himmel sind spätestens 48 Stunden vor Bekanntgabe anzumelden - Spontanversammlungen bleiben zulässig.',
        'Jede Nutzung öffentlicher Straßen über den Gemeingebrauch hinaus - Container, Gerüst, Umzugswagen, Außengastronomie - braucht eine Sondernutzungserlaubnis.',
      ],
      typischeUnterlagen: [
        'Bescheid oder Anhörungsbogen mit Aktenzeichen',
        'Personalausweis',
        'Bei Veranstaltungen: Lageplan, Ablaufplan, Sicherheitskonzept, Nachweis der Haftpflichtversicherung',
        'Bei Halteverbotszonen: Zeitraum, Länge des Bereichs, Fahrzeugdaten',
      ],
      typischeFristen: [
        'Einspruch gegen Bußgeldbescheid: 2 Wochen',
        'Rückmeldung auf Anhörungsbogen: meist 1 Woche, keine Ausschlussfrist',
        'Anmeldung einer Versammlung: 48 Stunden vor Bekanntgabe',
        'Antrag auf Halteverbotszone: mindestens 7 bis 14 Tage vorher',
      ],
      typischeKosten: 'Verwarnungsgelder bis 55 Euro, Bußgelder nach bundeseinheitlichem Bußgeldkatalog zuzüglich 28,50 Euro Gebühren und Auslagen bei Bescheiden. Sondernutzungserlaubnisse kosten kommunal meist 20 bis 300 Euro, Halteverbotszonen etwa 30 bis 150 Euro.',
      onlineWege: [
        'Online-Zahlung von Verwarnungs- und Bußgeldern über kommunale Portale',
        'Digitale Anmeldung von Veranstaltungen und Sondernutzungen',
        'Punkteauskunft aus dem Fahreignungsregister online beim Kraftfahrt-Bundesamt',
      ],
      rechtsrahmen: [
        'Gesetz über Ordnungswidrigkeiten (OWiG)',
        'Straßenverkehrsgesetz und Bußgeldkatalog-Verordnung',
        'Versammlungsgesetze des Bundes und der Länder',
        'Straßen- und Wegegesetze der Länder',
      ],
      haeufigeIrrtuemer: [
        'Wenn ich nicht reagiere, verjährt das - nein, der Bescheid wird bestandskräftig und vollstreckbar.',
        'Ein Foto ohne erkennbares Gesicht ist wertlos - die Behörde kann weiter ermitteln.',
        'Einspruch verschlechtert nie die Lage - im Gerichtsverfahren sind höhere Geldbußen möglich.',
      ],
    },
  },
  {
    id: 'steuern-abgaben',
    name: 'Steuern und kommunale Abgaben',
    sprechName: 'Steuern und Abgaben',
    lebenslagen: ['Steuern', 'Abgaben', 'Gebühren'],
    stichworte: [
      'steuer', 'steuern', 'finanzamt', 'steuererklärung', 'steuernummer', 'steuer-id',
      'identifikationsnummer', 'grundsteuer', 'hundesteuer', 'zweitwohnungsteuer',
      'zweitwohnungssteuer', 'gewerbesteuer', 'vergnügungssteuer', 'kirchensteuer',
      'lohnsteuer', 'steuerklasse', 'freistellungsbescheinigung', 'stundung', 'ratenzahlung',
      'mahnung', 'vollstreckung', 'säumniszuschlag', 'abgabenbescheid', 'elster',
    ],
    grundsatzwissen: {
      kurz: 'Steuerangelegenheiten teilen sich auf: Einkommen-, Lohn- und Umsatzsteuer beim Finanzamt des Landes, Grund-, Hunde-, Zweitwohnung- und Gewerbesteuer als kommunale Abgaben bei der Stadtkasse.',
      zustaendigkeit: 'Finanzamt am Wohnsitz beziehungsweise am Ort der Geschäftsleitung; Steueramt oder Stadtkasse der Gemeinde für kommunale Steuern.',
      faustregeln: [
        'Gegen jeden Steuer- und Abgabenbescheid können Sie binnen eines Monats Einspruch oder Widerspruch einlegen.',
        'Der Einspruch hemmt nicht die Zahlungspflicht - dafür brauchen Sie zusätzlich die Aussetzung der Vollziehung.',
        'Bei der Grundsteuer wirken drei Stellen zusammen: Das Finanzamt setzt Grundsteuerwert und Messbetrag fest, die Gemeinde wendet den Hebesatz an.',
        'Fehler im Grundsteuerwertbescheid müssen beim Finanzamt gerügt werden - ein Widerspruch bei der Gemeinde geht ins Leere.',
        'Stundung und Ratenzahlung sind bei erheblicher Härte möglich, werden aber üblicherweise verzinst.',
        'Die steuerliche Identifikationsnummer ist lebenslang gültig und wird nicht neu vergeben; sie lässt sich beim Bundeszentralamt für Steuern erneut mitteilen.',
      ],
      typischeUnterlagen: [
        'Bescheid mit Steuernummer oder Kassenzeichen',
        'Einkommens- und Vermögensnachweise bei Stundungsanträgen',
        'Grundbuchauszug und Flurstücksdaten bei der Grundsteuer',
        'Nachweise über Wohnsitze bei der Zweitwohnungsteuer',
      ],
      typischeFristen: [
        'Einspruch beim Finanzamt: 1 Monat',
        'Widerspruch gegen kommunale Abgabenbescheide: 1 Monat',
        'Einkommensteuererklärung bei Pflichtveranlagung: 31. Juli des Folgejahres',
        'Festsetzungsverjährung: regelmäßig 4 Jahre',
      ],
      typischeKosten: 'Verfahren beim Finanzamt und im kommunalen Widerspruchsverfahren sind gebührenfrei. Säumniszuschläge betragen 1 Prozent des rückständigen Betrags je angefangenem Monat.',
      onlineWege: [
        'ELSTER für Steuererklärungen, Einsprüche und den Fragebogen zur steuerlichen Erfassung',
        'Kommunale Serviceportale für An- und Abmeldung von Hunde- und Zweitwohnungsteuer',
        'Online-Abfrage der Steuer-Identifikationsnummer beim Bundeszentralamt für Steuern',
      ],
      rechtsrahmen: [
        'Abgabenordnung (AO)',
        'Grundsteuergesetz (GrStG) und Landesgrundsteuergesetze',
        'Kommunalabgabengesetze der Länder',
        'Gewerbesteuergesetz (GewStG)',
      ],
      haeufigeIrrtuemer: [
        'Wer Einspruch einlegt, muss erstmal nicht zahlen - falsch ohne Aussetzung der Vollziehung.',
        'Die Gemeinde hat die Grundsteuer falsch berechnet - meist liegt der Fehler im Bescheid des Finanzamts.',
        'Die Steuer-ID ändert sich beim Umzug - nein, sie bleibt lebenslang gleich.',
      ],
    },
  },
  {
    id: 'bildung-kultur',
    name: 'Bildung, Schule und Kultur',
    sprechName: 'Bildung und Schule',
    lebenslagen: ['Schule', 'Ausbildung', 'Studium'],
    stichworte: [
      'schule', 'einschulung', 'schulanmeldung', 'schulwechsel', 'schulamt', 'schülerticket',
      'schülerbeförderung', 'bafög', 'ausbildung', 'studium', 'bibliothek', 'büchereiausweis',
      'volkshochschule', 'vhs', 'ferienbetreuung', 'hort', 'ganztag', 'zeugnisanerkennung',
      'schulpflicht', 'lernmittel', 'schulbuch', 'nachteilsausgleich', 'sonderpädagogisch',
      'eingeschult', 'einschulen', 'schulkind', 'schulanfang', 'erstklässler', 'grundschule',
      'kommt in die schule', 'schulbeginn', 'weiterführende schule', 'gymnasium', 'abitur',
    ],
    grundsatzwissen: {
      kurz: 'Schule ist Landesrecht mit kommunaler Trägerschaft: Das Land regelt Unterricht und Schulpflicht, die Kommune stellt Gebäude, Schülerbeförderung und Betreuung.',
      zustaendigkeit: 'Staatliches Schulamt und Schulleitung für schulische Fragen, Schulverwaltungsamt der Kommune für Beförderung und Betreuung, BAföG-Amt beim Studierendenwerk oder Kreis.',
      faustregeln: [
        'Die Schulpflicht beginnt in den meisten Ländern für Kinder, die bis zum 30. Juni oder 30. September sechs Jahre alt werden.',
        'Zur Einschulung lädt die zuständige Grundschule etwa ein Jahr vorher ein - die Anmeldung ist Pflicht, nicht Angebot.',
        'Für eine andere als die zuständige Sprengelschule brauchen Sie einen Gestattungsantrag mit Begründung.',
        'Schülerbeförderung wird ab bestimmten Mindestentfernungen übernommen, meist zwei Kilometer in der Grundschule und drei bis vier Kilometer weiterführend.',
        'BAföG wird ab dem Antragsmonat gezahlt, nicht rückwirkend - der formlose Antrag sichert den Monat.',
        'Die schulärztliche Untersuchung vor der Einschulung ist in fast allen Ländern verpflichtend.',
      ],
      typischeUnterlagen: [
        'Geburtsurkunde des Kindes',
        'Personalausweis der Sorgeberechtigten und Meldebescheinigung',
        'Nachweis über Masernimpfung nach Masernschutzgesetz',
        'Bei BAföG: Einkommensnachweise der Eltern aus dem vorletzten Kalenderjahr',
        'Bei Schulwechsel: letztes Zeugnis und Abmeldebestätigung',
      ],
      typischeFristen: [
        'Schulanmeldung: meist Herbst des Vorjahres',
        'BAföG: Zahlung ab Antragsmonat, Weiterförderung 2 Monate vorher beantragen',
        'Widerspruch gegen Schulentscheidungen: 1 Monat',
      ],
      typischeKosten: 'Der Schulbesuch an öffentlichen Schulen ist kostenfrei. Lernmittel sind je nach Land frei oder gegen Eigenanteil, Betreuungs- und Essensbeiträge sind kommunal und meist einkommensabhängig. BAföG ist für Schüler Zuschuss, für Studierende zur Hälfte zinsloses Darlehen.',
      onlineWege: [
        'Schulanmeldung über kommunale Bildungsportale in wachsender Zahl',
        'BAföG-Antrag über BAföG Digital',
        'Anträge auf Bildung und Teilhabe über Jobcenter- und Kommunalportale',
      ],
      rechtsrahmen: [
        'Schulgesetze der Länder',
        'Bundesausbildungsförderungsgesetz (BAföG)',
        'Masernschutzgesetz und Infektionsschutzgesetz',
        'Zehntes Buch Sozialgesetzbuch für Verfahrensfragen',
      ],
      haeufigeIrrtuemer: [
        'Ich kann mein Kind an jeder beliebigen Schule anmelden - meist gilt der Schulsprengel.',
        'BAföG bekommt man rückwirkend ab Semesterbeginn - nur ab Antragsmonat.',
        'Schulbücher sind überall kostenlos - je nach Land gibt es Eigenanteile.',
      ],
    },
  },
];

export const CLUSTER_BY_ID = Object.fromEntries(CLUSTER.map((c) => [c.id, c]));
